// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: api/xtravel/v1/account.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AccountService_AccountLogin_FullMethodName = "/xtravel.v1.AccountService/AccountLogin"
)

// AccountServiceClient is the client API for AccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AccountService 登录相关。
// 对应原项目 app/api/controller/v1/account/LoginController.php
// 路由分组：app/api/route/account.php 里的 Route::group('/v1/login', ...)
// ⚠️ 所以路径是 /v1/login/xxx，**不是** /account/xxx。
type AccountServiceClient interface {
	// 账号/密码、手机验证码登录
	// 原: LoginController::account
	//
	//	$params = (new LoginAccountValidate())->post()->goCheck();
	//	$params['app_id'] = 1;
	//	$result = LoginLogic::login($params);
	//	if (false === $result) return $this->fail(LoginLogic::getError());
	//	return $this->data($result);          // <- data() = success('', $data, 1, 0)
	//
	// 免登录（LoginController::$notNeedLogin 含 'account'）。
	AccountLogin(ctx context.Context, in *AccountLoginRequest, opts ...grpc.CallOption) (*AccountLoginReply, error)
}

type accountServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountServiceClient(cc grpc.ClientConnInterface) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) AccountLogin(ctx context.Context, in *AccountLoginRequest, opts ...grpc.CallOption) (*AccountLoginReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccountLoginReply)
	err := c.cc.Invoke(ctx, AccountService_AccountLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServiceServer is the server API for AccountService service.
// All implementations must embed UnimplementedAccountServiceServer
// for forward compatibility.
//
// AccountService 登录相关。
// 对应原项目 app/api/controller/v1/account/LoginController.php
// 路由分组：app/api/route/account.php 里的 Route::group('/v1/login', ...)
// ⚠️ 所以路径是 /v1/login/xxx，**不是** /account/xxx。
type AccountServiceServer interface {
	// 账号/密码、手机验证码登录
	// 原: LoginController::account
	//
	//	$params = (new LoginAccountValidate())->post()->goCheck();
	//	$params['app_id'] = 1;
	//	$result = LoginLogic::login($params);
	//	if (false === $result) return $this->fail(LoginLogic::getError());
	//	return $this->data($result);          // <- data() = success('', $data, 1, 0)
	//
	// 免登录（LoginController::$notNeedLogin 含 'account'）。
	AccountLogin(context.Context, *AccountLoginRequest) (*AccountLoginReply, error)
	mustEmbedUnimplementedAccountServiceServer()
}

// UnimplementedAccountServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAccountServiceServer struct{}

func (UnimplementedAccountServiceServer) AccountLogin(context.Context, *AccountLoginRequest) (*AccountLoginReply, error) {
	return nil, status.Error(codes.Unimplemented, "method AccountLogin not implemented")
}
func (UnimplementedAccountServiceServer) mustEmbedUnimplementedAccountServiceServer() {}
func (UnimplementedAccountServiceServer) testEmbeddedByValue()                        {}

// UnsafeAccountServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountServiceServer will
// result in compilation errors.
type UnsafeAccountServiceServer interface {
	mustEmbedUnimplementedAccountServiceServer()
}

func RegisterAccountServiceServer(s grpc.ServiceRegistrar, srv AccountServiceServer) {
	// If the following call panics, it indicates UnimplementedAccountServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AccountService_ServiceDesc, srv)
}

func _AccountService_AccountLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).AccountLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_AccountLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).AccountLogin(ctx, req.(*AccountLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountService_ServiceDesc is the grpc.ServiceDesc for AccountService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xtravel.v1.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AccountLogin",
			Handler:    _AccountService_AccountLogin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/xtravel/v1/account.proto",
}
