// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/xtravel/v1/account.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AccountLoginRequest 对应 LoginAccountValidate 的规则：
//
//	'terminal' => 'require|in:1,2,3,4,5,6',
//	'scene'    => 'require|in:1,2|checkConfig',
//	'account'  => 'require',
//	// password 在 checkConfig 里按 scene 动态要求
//
// ⚠️ 校验顺序与错误信息必须与 PHP 一致（见 message 定义），
// 否则前端拿到的提示会变。字段名是 **snake-free 的小写单词**，原样透传。
type AccountLoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 1 微信小程序 / 2 微信公众号 / 3 手机H5 / 4 电脑PC / 5 苹果app / 6 安卓app
	Terminal int32 `protobuf:"varint,1,opt,name=terminal,proto3" json:"terminal,omitempty"`
	// 1 账号密码 / 2 手机验证码
	Scene   int32  `protobuf:"varint,2,opt,name=scene,proto3" json:"scene,omitempty"`
	Account string `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	// scene=1 时必填
	Password string `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	// 图形验证码 ID。scene=1 时必填。
	// ⚠️ json_name 必须是 `captchaId`（小写 d）—— 原实现读的是 $data['captchaId']，
	//
	//	用 protojson 默认的 `captchaId` 恰好一致，但仍显式写死以免以后被改名。
	CaptchaId string `protobuf:"bytes,5,opt,name=captcha_id,json=captchaId,proto3" json:"captcha_id,omitempty"`
	// 图形验证码内容。scene=1 时使用。
	Captcha string `protobuf:"bytes,6,opt,name=captcha,proto3" json:"captcha,omitempty"`
	// 手机验证码。scene=2 时必填（对应 $data['code']）。
	Code          string `protobuf:"bytes,7,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountLoginRequest) Reset() {
	*x = AccountLoginRequest{}
	mi := &file_api_xtravel_v1_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountLoginRequest) ProtoMessage() {}

func (x *AccountLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_xtravel_v1_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountLoginRequest.ProtoReflect.Descriptor instead.
func (*AccountLoginRequest) Descriptor() ([]byte, []int) {
	return file_api_xtravel_v1_account_proto_rawDescGZIP(), []int{0}
}

func (x *AccountLoginRequest) GetTerminal() int32 {
	if x != nil {
		return x.Terminal
	}
	return 0
}

func (x *AccountLoginRequest) GetScene() int32 {
	if x != nil {
		return x.Scene
	}
	return 0
}

func (x *AccountLoginRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *AccountLoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AccountLoginRequest) GetCaptchaId() string {
	if x != nil {
		return x.CaptchaId
	}
	return ""
}

func (x *AccountLoginRequest) GetCaptcha() string {
	if x != nil {
		return x.Captcha
	}
	return ""
}

func (x *AccountLoginRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// AccountLoginReply 对应 LoginLogic::login 的返回值：
//
//	return ['nickname'=>$userInfo['nickname'], 'sn'=>$userInfo['sn'],
//	        'mobile'=>$userInfo['mobile'], 'avatar'=>$avatar, 'token'=>$userInfo['token']];
//
// ⚠️ 五个键都是**全小写单词**（没有下划线也没有驼峰），json_name 原样即可。
// ⚠️ nickname / sn / mobile 取自 **$userInfo（token 缓存里的值）**，不是 $user。
type AccountLoginReply struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Nickname string                 `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	// x_user.sn 是 bigint(20)。protojson 会把 int64 输出成字符串，
	// 由 httpx.unquoteInt64 还原成数字（原契约里是数字）。
	Sn     uint64 `protobuf:"varint,2,opt,name=sn,proto3" json:"sn,omitempty"`
	Mobile string `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	// 已经过 FileService::getFileUrl 处理（完整 URL 原样返回，相对路径拼域名）
	Avatar        string `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Token         string `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountLoginReply) Reset() {
	*x = AccountLoginReply{}
	mi := &file_api_xtravel_v1_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountLoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountLoginReply) ProtoMessage() {}

func (x *AccountLoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_xtravel_v1_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountLoginReply.ProtoReflect.Descriptor instead.
func (*AccountLoginReply) Descriptor() ([]byte, []int) {
	return file_api_xtravel_v1_account_proto_rawDescGZIP(), []int{1}
}

func (x *AccountLoginReply) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *AccountLoginReply) GetSn() uint64 {
	if x != nil {
		return x.Sn
	}
	return 0
}

func (x *AccountLoginReply) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *AccountLoginReply) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *AccountLoginReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_api_xtravel_v1_account_proto protoreflect.FileDescriptor

const file_api_xtravel_v1_account_proto_rawDesc = "" +
	"\n" +
	"\x1capi/xtravel/v1/account.proto\x12\n" +
	"xtravel.v1\x1a\x1cgoogle/api/annotations.proto\"\xca\x01\n" +
	"\x13AccountLoginRequest\x12\x1a\n" +
	"\bterminal\x18\x01 \x01(\x05R\bterminal\x12\x14\n" +
	"\x05scene\x18\x02 \x01(\x05R\x05scene\x12\x18\n" +
	"\aaccount\x18\x03 \x01(\tR\aaccount\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x1d\n" +
	"\n" +
	"captcha_id\x18\x05 \x01(\tR\tcaptchaId\x12\x18\n" +
	"\acaptcha\x18\x06 \x01(\tR\acaptcha\x12\x12\n" +
	"\x04code\x18\a \x01(\tR\x04code\"\x85\x01\n" +
	"\x11AccountLoginReply\x12\x1a\n" +
	"\bnickname\x18\x01 \x01(\tR\bnickname\x12\x0e\n" +
	"\x02sn\x18\x02 \x01(\x04R\x02sn\x12\x16\n" +
	"\x06mobile\x18\x03 \x01(\tR\x06mobile\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12\x14\n" +
	"\x05token\x18\x05 \x01(\tR\x05token2~\n" +
	"\x0eAccountService\x12l\n" +
	"\fAccountLogin\x12\x1f.xtravel.v1.AccountLoginRequest\x1a\x1d.xtravel.v1.AccountLoginReply\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/login/accountB2Z0github.com/lixiaoping4258/ymkj/api/xtravel/v1;v1b\x06proto3"

var (
	file_api_xtravel_v1_account_proto_rawDescOnce sync.Once
	file_api_xtravel_v1_account_proto_rawDescData []byte
)

func file_api_xtravel_v1_account_proto_rawDescGZIP() []byte {
	file_api_xtravel_v1_account_proto_rawDescOnce.Do(func() {
		file_api_xtravel_v1_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_xtravel_v1_account_proto_rawDesc), len(file_api_xtravel_v1_account_proto_rawDesc)))
	})
	return file_api_xtravel_v1_account_proto_rawDescData
}

var file_api_xtravel_v1_account_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_xtravel_v1_account_proto_goTypes = []any{
	(*AccountLoginRequest)(nil), // 0: xtravel.v1.AccountLoginRequest
	(*AccountLoginReply)(nil),   // 1: xtravel.v1.AccountLoginReply
}
var file_api_xtravel_v1_account_proto_depIdxs = []int32{
	0, // 0: xtravel.v1.AccountService.AccountLogin:input_type -> xtravel.v1.AccountLoginRequest
	1, // 1: xtravel.v1.AccountService.AccountLogin:output_type -> xtravel.v1.AccountLoginReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_xtravel_v1_account_proto_init() }
func file_api_xtravel_v1_account_proto_init() {
	if File_api_xtravel_v1_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_xtravel_v1_account_proto_rawDesc), len(file_api_xtravel_v1_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_xtravel_v1_account_proto_goTypes,
		DependencyIndexes: file_api_xtravel_v1_account_proto_depIdxs,
		MessageInfos:      file_api_xtravel_v1_account_proto_msgTypes,
	}.Build()
	File_api_xtravel_v1_account_proto = out.File
	file_api_xtravel_v1_account_proto_goTypes = nil
	file_api_xtravel_v1_account_proto_depIdxs = nil
}
