// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.35.1
// source: api/xtravel/v1/account.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationAccountServiceAccountLogin = "/xtravel.v1.AccountService/AccountLogin"

type AccountServiceHTTPServer interface {
	// AccountLogin 账号/密码、手机验证码登录
	// 原: LoginController::account
	//   $params = (new LoginAccountValidate())->post()->goCheck();
	//   $params['app_id'] = 1;
	//   $result = LoginLogic::login($params);
	//   if (false === $result) return $this->fail(LoginLogic::getError());
	//   return $this->data($result);          // <- data() = success('', $data, 1, 0)
	//
	// 免登录（LoginController::$notNeedLogin 含 'account'）。
	AccountLogin(context.Context, *AccountLoginRequest) (*AccountLoginReply, error)
}

func RegisterAccountServiceHTTPServer(s *http.Server, srv AccountServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/login/account", _AccountService_AccountLogin0_HTTP_Handler(srv))
}

func _AccountService_AccountLogin0_HTTP_Handler(srv AccountServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AccountLoginRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAccountServiceAccountLogin)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AccountLogin(ctx, req.(*AccountLoginRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AccountLoginReply)
		return ctx.Result(200, reply)
	}
}

type AccountServiceHTTPClient interface {
	// AccountLogin 账号/密码、手机验证码登录
	// 原: LoginController::account
	//   $params = (new LoginAccountValidate())->post()->goCheck();
	//   $params['app_id'] = 1;
	//   $result = LoginLogic::login($params);
	//   if (false === $result) return $this->fail(LoginLogic::getError());
	//   return $this->data($result);          // <- data() = success('', $data, 1, 0)
	//
	// 免登录（LoginController::$notNeedLogin 含 'account'）。
	AccountLogin(ctx context.Context, req *AccountLoginRequest, opts ...http.CallOption) (rsp *AccountLoginReply, err error)
}

type AccountServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewAccountServiceHTTPClient(client *http.Client) AccountServiceHTTPClient {
	return &AccountServiceHTTPClientImpl{client}
}

// AccountLogin 账号/密码、手机验证码登录
// 原: LoginController::account
//
//	$params = (new LoginAccountValidate())->post()->goCheck();
//	$params['app_id'] = 1;
//	$result = LoginLogic::login($params);
//	if (false === $result) return $this->fail(LoginLogic::getError());
//	return $this->data($result);          // <- data() = success('', $data, 1, 0)
//
// 免登录（LoginController::$notNeedLogin 含 'account'）。
func (c *AccountServiceHTTPClientImpl) AccountLogin(ctx context.Context, in *AccountLoginRequest, opts ...http.CallOption) (*AccountLoginReply, error) {
	var out AccountLoginReply
	pattern := "/v1/login/account"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAccountServiceAccountLogin))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
