// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.35.1
// source: api/xtravel/v1/article.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationArticleServiceGetArticleAbout = "/xtravel.v1.ArticleService/GetArticleAbout"
const OperationArticleServiceGetArticleLicenses = "/xtravel.v1.ArticleService/GetArticleLicenses"

type ArticleServiceHTTPServer interface {
	// GetArticleAbout 关于我们
	//
	// 原实现 ArticleLogic::about()：
	//
	//	$data = ['title' => '关于我们'];
	//	$result = Article::where(['cid'=>1,'is_show'=>1])
	//	    ->whereRaw('delete_time is null')->order('sort','desc')
	//	    ->field('id,title')->select();
	//	$data['lists'] = $result->toArray();
	//	return $data;
	//
	// ⚠️ 需登录！ArticleController::$notNeedLogin = ['lists','cate','detail'] ——
	//    **about / licenses 都不在里面**。凭"这是关于页面"的直觉会标反。
	GetArticleAbout(context.Context, *GetArticleAboutRequest) (*ArticleListReply, error)
	// GetArticleLicenses 资质证照
	//
	// 原实现 ArticleLogic::license()：与 about 同构，只是 cid=3、title='资质证照'。
	// ⚠️ 同样**需登录**。
	GetArticleLicenses(context.Context, *GetArticleLicensesRequest) (*ArticleListReply, error)
}

func RegisterArticleServiceHTTPServer(s *http.Server, srv ArticleServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/article/about", _ArticleService_GetArticleAbout0_HTTP_Handler(srv))
	r.GET("/v1/article/licenses", _ArticleService_GetArticleLicenses0_HTTP_Handler(srv))
}

func _ArticleService_GetArticleAbout0_HTTP_Handler(srv ArticleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetArticleAboutRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationArticleServiceGetArticleAbout)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetArticleAbout(ctx, req.(*GetArticleAboutRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ArticleListReply)
		return ctx.Result(200, reply)
	}
}

func _ArticleService_GetArticleLicenses0_HTTP_Handler(srv ArticleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetArticleLicensesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationArticleServiceGetArticleLicenses)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetArticleLicenses(ctx, req.(*GetArticleLicensesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ArticleListReply)
		return ctx.Result(200, reply)
	}
}

type ArticleServiceHTTPClient interface {
	// GetArticleAbout 关于我们
	//
	// 原实现 ArticleLogic::about()：
	//
	//	$data = ['title' => '关于我们'];
	//	$result = Article::where(['cid'=>1,'is_show'=>1])
	//	    ->whereRaw('delete_time is null')->order('sort','desc')
	//	    ->field('id,title')->select();
	//	$data['lists'] = $result->toArray();
	//	return $data;
	//
	// ⚠️ 需登录！ArticleController::$notNeedLogin = ['lists','cate','detail'] ——
	//    **about / licenses 都不在里面**。凭"这是关于页面"的直觉会标反。
	GetArticleAbout(ctx context.Context, req *GetArticleAboutRequest, opts ...http.CallOption) (rsp *ArticleListReply, err error)
	// GetArticleLicenses 资质证照
	//
	// 原实现 ArticleLogic::license()：与 about 同构，只是 cid=3、title='资质证照'。
	// ⚠️ 同样**需登录**。
	GetArticleLicenses(ctx context.Context, req *GetArticleLicensesRequest, opts ...http.CallOption) (rsp *ArticleListReply, err error)
}

type ArticleServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewArticleServiceHTTPClient(client *http.Client) ArticleServiceHTTPClient {
	return &ArticleServiceHTTPClientImpl{client}
}

// GetArticleAbout 关于我们
//
// 原实现 ArticleLogic::about()：
//
//	$data = ['title' => '关于我们'];
//	$result = Article::where(['cid'=>1,'is_show'=>1])
//	    ->whereRaw('delete_time is null')->order('sort','desc')
//	    ->field('id,title')->select();
//	$data['lists'] = $result->toArray();
//	return $data;
//
// ⚠️ 需登录！ArticleController::$notNeedLogin = ['lists','cate','detail'] ——
//
//	**about / licenses 都不在里面**。凭"这是关于页面"的直觉会标反。
func (c *ArticleServiceHTTPClientImpl) GetArticleAbout(ctx context.Context, in *GetArticleAboutRequest, opts ...http.CallOption) (*ArticleListReply, error) {
	var out ArticleListReply
	pattern := "/v1/article/about"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationArticleServiceGetArticleAbout))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetArticleLicenses 资质证照
//
// 原实现 ArticleLogic::license()：与 about 同构，只是 cid=3、title='资质证照'。
// ⚠️ 同样**需登录**。
func (c *ArticleServiceHTTPClientImpl) GetArticleLicenses(ctx context.Context, in *GetArticleLicensesRequest, opts ...http.CallOption) (*ArticleListReply, error) {
	var out ArticleListReply
	pattern := "/v1/article/licenses"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationArticleServiceGetArticleLicenses))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
