// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/xtravel/v1/article.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetArticleAboutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleAboutRequest) Reset() {
	*x = GetArticleAboutRequest{}
	mi := &file_api_xtravel_v1_article_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleAboutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleAboutRequest) ProtoMessage() {}

func (x *GetArticleAboutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_xtravel_v1_article_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleAboutRequest.ProtoReflect.Descriptor instead.
func (*GetArticleAboutRequest) Descriptor() ([]byte, []int) {
	return file_api_xtravel_v1_article_proto_rawDescGZIP(), []int{0}
}

type GetArticleLicensesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleLicensesRequest) Reset() {
	*x = GetArticleLicensesRequest{}
	mi := &file_api_xtravel_v1_article_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleLicensesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleLicensesRequest) ProtoMessage() {}

func (x *GetArticleLicensesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_xtravel_v1_article_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleLicensesRequest.ProtoReflect.Descriptor instead.
func (*GetArticleLicensesRequest) Descriptor() ([]byte, []int) {
	return file_api_xtravel_v1_article_proto_rawDescGZIP(), []int{1}
}

// ArticleListReply 对应 `['title' => ..., 'lists' => $result->toArray()]`。
type ArticleListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Lists         []*ArticleItem         `protobuf:"bytes,2,rep,name=lists,proto3" json:"lists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleListReply) Reset() {
	*x = ArticleListReply{}
	mi := &file_api_xtravel_v1_article_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleListReply) ProtoMessage() {}

func (x *ArticleListReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_xtravel_v1_article_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleListReply.ProtoReflect.Descriptor instead.
func (*ArticleListReply) Descriptor() ([]byte, []int) {
	return file_api_xtravel_v1_article_proto_rawDescGZIP(), []int{2}
}

func (x *ArticleListReply) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ArticleListReply) GetLists() []*ArticleItem {
	if x != nil {
		return x.Lists
	}
	return nil
}

// ArticleItem 对应 `->field('id,title')` 的两列。
type ArticleItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// x_article.id 是 int(11)，PHP 的 toArray() 会输出**数字**
	Id            int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleItem) Reset() {
	*x = ArticleItem{}
	mi := &file_api_xtravel_v1_article_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleItem) ProtoMessage() {}

func (x *ArticleItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_xtravel_v1_article_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleItem.ProtoReflect.Descriptor instead.
func (*ArticleItem) Descriptor() ([]byte, []int) {
	return file_api_xtravel_v1_article_proto_rawDescGZIP(), []int{3}
}

func (x *ArticleItem) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ArticleItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

var File_api_xtravel_v1_article_proto protoreflect.FileDescriptor

const file_api_xtravel_v1_article_proto_rawDesc = "" +
	"\n" +
	"\x1capi/xtravel/v1/article.proto\x12\n" +
	"xtravel.v1\x1a\x1cgoogle/api/annotations.proto\"\x18\n" +
	"\x16GetArticleAboutRequest\"\x1b\n" +
	"\x19GetArticleLicensesRequest\"W\n" +
	"\x10ArticleListReply\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12-\n" +
	"\x05lists\x18\x02 \x03(\v2\x17.xtravel.v1.ArticleItemR\x05lists\"3\n" +
	"\vArticleItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title2\xf9\x01\n" +
	"\x0eArticleService\x12n\n" +
	"\x0fGetArticleAbout\x12\".xtravel.v1.GetArticleAboutRequest\x1a\x1c.xtravel.v1.ArticleListReply\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/article/about\x12w\n" +
	"\x12GetArticleLicenses\x12%.xtravel.v1.GetArticleLicensesRequest\x1a\x1c.xtravel.v1.ArticleListReply\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/article/licensesB2Z0github.com/lixiaoping4258/ymkj/api/xtravel/v1;v1b\x06proto3"

var (
	file_api_xtravel_v1_article_proto_rawDescOnce sync.Once
	file_api_xtravel_v1_article_proto_rawDescData []byte
)

func file_api_xtravel_v1_article_proto_rawDescGZIP() []byte {
	file_api_xtravel_v1_article_proto_rawDescOnce.Do(func() {
		file_api_xtravel_v1_article_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_xtravel_v1_article_proto_rawDesc), len(file_api_xtravel_v1_article_proto_rawDesc)))
	})
	return file_api_xtravel_v1_article_proto_rawDescData
}

var file_api_xtravel_v1_article_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_xtravel_v1_article_proto_goTypes = []any{
	(*GetArticleAboutRequest)(nil),    // 0: xtravel.v1.GetArticleAboutRequest
	(*GetArticleLicensesRequest)(nil), // 1: xtravel.v1.GetArticleLicensesRequest
	(*ArticleListReply)(nil),          // 2: xtravel.v1.ArticleListReply
	(*ArticleItem)(nil),               // 3: xtravel.v1.ArticleItem
}
var file_api_xtravel_v1_article_proto_depIdxs = []int32{
	3, // 0: xtravel.v1.ArticleListReply.lists:type_name -> xtravel.v1.ArticleItem
	0, // 1: xtravel.v1.ArticleService.GetArticleAbout:input_type -> xtravel.v1.GetArticleAboutRequest
	1, // 2: xtravel.v1.ArticleService.GetArticleLicenses:input_type -> xtravel.v1.GetArticleLicensesRequest
	2, // 3: xtravel.v1.ArticleService.GetArticleAbout:output_type -> xtravel.v1.ArticleListReply
	2, // 4: xtravel.v1.ArticleService.GetArticleLicenses:output_type -> xtravel.v1.ArticleListReply
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_xtravel_v1_article_proto_init() }
func file_api_xtravel_v1_article_proto_init() {
	if File_api_xtravel_v1_article_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_xtravel_v1_article_proto_rawDesc), len(file_api_xtravel_v1_article_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_xtravel_v1_article_proto_goTypes,
		DependencyIndexes: file_api_xtravel_v1_article_proto_depIdxs,
		MessageInfos:      file_api_xtravel_v1_article_proto_msgTypes,
	}.Build()
	File_api_xtravel_v1_article_proto = out.File
	file_api_xtravel_v1_article_proto_goTypes = nil
	file_api_xtravel_v1_article_proto_depIdxs = nil
}
