// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: api/xtravel/v1/article.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ArticleService_GetArticleAbout_FullMethodName    = "/xtravel.v1.ArticleService/GetArticleAbout"
	ArticleService_GetArticleLicenses_FullMethodName = "/xtravel.v1.ArticleService/GetArticleLicenses"
)

// ArticleServiceClient is the client API for ArticleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ArticleService 文章/协议。
// 对应原项目 app/api/controller/v1/article/ArticleController.php
// 路由分组 app/api/route/article.php：Route::group('/v1/article', ...)
//
// ⚠️⚠️ 原文该文件里 **6 条路由是注释掉的**（cate / lists / collect / addCollect /
// cancelCollect / 以及重复的 detail），**只有 3 条是活的**：
//
//	Route::get('about',    [ArticleController::class, 'about']);
//	Route::get('licenses', [ArticleController::class, 'license']);   // ← 方法名是 license，路径是 licenses
//	Route::get('detail',   [ArticleController::class, 'detail']);
//
// 统计路由数时必须**排除注释行**，否则分母虚高（我第一版就把它算成 9 条）。
type ArticleServiceClient interface {
	// 关于我们
	//
	// 原实现 ArticleLogic::about()：
	//
	//	$data = ['title' => '关于我们'];
	//	$result = Article::where(['cid'=>1,'is_show'=>1])
	//	    ->whereRaw('delete_time is null')->order('sort','desc')
	//	    ->field('id,title')->select();
	//	$data['lists'] = $result->toArray();
	//	return $data;
	//
	// ⚠️ 需登录！ArticleController::$notNeedLogin = ['lists','cate','detail'] ——
	//
	//	**about / licenses 都不在里面**。凭"这是关于页面"的直觉会标反。
	GetArticleAbout(ctx context.Context, in *GetArticleAboutRequest, opts ...grpc.CallOption) (*ArticleListReply, error)
	// 资质证照
	//
	// 原实现 ArticleLogic::license()：与 about 同构，只是 cid=3、title='资质证照'。
	// ⚠️ 同样**需登录**。
	GetArticleLicenses(ctx context.Context, in *GetArticleLicensesRequest, opts ...grpc.CallOption) (*ArticleListReply, error)
}

type articleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewArticleServiceClient(cc grpc.ClientConnInterface) ArticleServiceClient {
	return &articleServiceClient{cc}
}

func (c *articleServiceClient) GetArticleAbout(ctx context.Context, in *GetArticleAboutRequest, opts ...grpc.CallOption) (*ArticleListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArticleListReply)
	err := c.cc.Invoke(ctx, ArticleService_GetArticleAbout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleServiceClient) GetArticleLicenses(ctx context.Context, in *GetArticleLicensesRequest, opts ...grpc.CallOption) (*ArticleListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArticleListReply)
	err := c.cc.Invoke(ctx, ArticleService_GetArticleLicenses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArticleServiceServer is the server API for ArticleService service.
// All implementations must embed UnimplementedArticleServiceServer
// for forward compatibility.
//
// ArticleService 文章/协议。
// 对应原项目 app/api/controller/v1/article/ArticleController.php
// 路由分组 app/api/route/article.php：Route::group('/v1/article', ...)
//
// ⚠️⚠️ 原文该文件里 **6 条路由是注释掉的**（cate / lists / collect / addCollect /
// cancelCollect / 以及重复的 detail），**只有 3 条是活的**：
//
//	Route::get('about',    [ArticleController::class, 'about']);
//	Route::get('licenses', [ArticleController::class, 'license']);   // ← 方法名是 license，路径是 licenses
//	Route::get('detail',   [ArticleController::class, 'detail']);
//
// 统计路由数时必须**排除注释行**，否则分母虚高（我第一版就把它算成 9 条）。
type ArticleServiceServer interface {
	// 关于我们
	//
	// 原实现 ArticleLogic::about()：
	//
	//	$data = ['title' => '关于我们'];
	//	$result = Article::where(['cid'=>1,'is_show'=>1])
	//	    ->whereRaw('delete_time is null')->order('sort','desc')
	//	    ->field('id,title')->select();
	//	$data['lists'] = $result->toArray();
	//	return $data;
	//
	// ⚠️ 需登录！ArticleController::$notNeedLogin = ['lists','cate','detail'] ——
	//
	//	**about / licenses 都不在里面**。凭"这是关于页面"的直觉会标反。
	GetArticleAbout(context.Context, *GetArticleAboutRequest) (*ArticleListReply, error)
	// 资质证照
	//
	// 原实现 ArticleLogic::license()：与 about 同构，只是 cid=3、title='资质证照'。
	// ⚠️ 同样**需登录**。
	GetArticleLicenses(context.Context, *GetArticleLicensesRequest) (*ArticleListReply, error)
	mustEmbedUnimplementedArticleServiceServer()
}

// UnimplementedArticleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArticleServiceServer struct{}

func (UnimplementedArticleServiceServer) GetArticleAbout(context.Context, *GetArticleAboutRequest) (*ArticleListReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetArticleAbout not implemented")
}
func (UnimplementedArticleServiceServer) GetArticleLicenses(context.Context, *GetArticleLicensesRequest) (*ArticleListReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetArticleLicenses not implemented")
}
func (UnimplementedArticleServiceServer) mustEmbedUnimplementedArticleServiceServer() {}
func (UnimplementedArticleServiceServer) testEmbeddedByValue()                        {}

// UnsafeArticleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArticleServiceServer will
// result in compilation errors.
type UnsafeArticleServiceServer interface {
	mustEmbedUnimplementedArticleServiceServer()
}

func RegisterArticleServiceServer(s grpc.ServiceRegistrar, srv ArticleServiceServer) {
	// If the following call panics, it indicates UnimplementedArticleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ArticleService_ServiceDesc, srv)
}

func _ArticleService_GetArticleAbout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArticleAboutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServiceServer).GetArticleAbout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleService_GetArticleAbout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServiceServer).GetArticleAbout(ctx, req.(*GetArticleAboutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleService_GetArticleLicenses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArticleLicensesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServiceServer).GetArticleLicenses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleService_GetArticleLicenses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServiceServer).GetArticleLicenses(ctx, req.(*GetArticleLicensesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ArticleService_ServiceDesc is the grpc.ServiceDesc for ArticleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArticleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xtravel.v1.ArticleService",
	HandlerType: (*ArticleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetArticleAbout",
			Handler:    _ArticleService_GetArticleAbout_Handler,
		},
		{
			MethodName: "GetArticleLicenses",
			Handler:    _ArticleService_GetArticleLicenses_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/xtravel/v1/article.proto",
}
