// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/xtravel/v1/captcha.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetCaptchaRequest 对应 query 参数 w / h。
//
// ⚠️ 原实现用的是 `$this->request->get('w/d', 150)` —— `/d` 是 ThinkPHP 的
// **强制整数转换**：非数字会变成 0，而 0 触发了"越界回默认值"的分支。
// 所以传 w=abc 与不传 w 的结果相同（都是 150）。Go 侧用 int32 直接接收，
// 非数字会被 Kratos 解析失败 —— 行为差异见下方说明。
type GetCaptchaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	W             int32                  `protobuf:"varint,1,opt,name=w,proto3" json:"w,omitempty"`
	H             int32                  `protobuf:"varint,2,opt,name=h,proto3" json:"h,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCaptchaRequest) Reset() {
	*x = GetCaptchaRequest{}
	mi := &file_api_xtravel_v1_captcha_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCaptchaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCaptchaRequest) ProtoMessage() {}

func (x *GetCaptchaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_xtravel_v1_captcha_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCaptchaRequest.ProtoReflect.Descriptor instead.
func (*GetCaptchaRequest) Descriptor() ([]byte, []int) {
	return file_api_xtravel_v1_captcha_proto_rawDescGZIP(), []int{0}
}

func (x *GetCaptchaRequest) GetW() int32 {
	if x != nil {
		return x.W
	}
	return 0
}

func (x *GetCaptchaRequest) GetH() int32 {
	if x != nil {
		return x.H
	}
	return 0
}

// GetCaptchaReply 对应 CaptchaLogic::getCaptcha 的返回值：
//
//	return ['id' => $id, 'image' => $image];
//
// image 是 `data:image/png;base64,...`（CaptchaBuilder::inline 的格式）。
type GetCaptchaReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id::uuid() 生成的 8-4-4-4-12 十六进制串。前端回传时不透明使用。
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Image         string `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCaptchaReply) Reset() {
	*x = GetCaptchaReply{}
	mi := &file_api_xtravel_v1_captcha_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCaptchaReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCaptchaReply) ProtoMessage() {}

func (x *GetCaptchaReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_xtravel_v1_captcha_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCaptchaReply.ProtoReflect.Descriptor instead.
func (*GetCaptchaReply) Descriptor() ([]byte, []int) {
	return file_api_xtravel_v1_captcha_proto_rawDescGZIP(), []int{1}
}

func (x *GetCaptchaReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetCaptchaReply) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

var File_api_xtravel_v1_captcha_proto protoreflect.FileDescriptor

const file_api_xtravel_v1_captcha_proto_rawDesc = "" +
	"\n" +
	"\x1capi/xtravel/v1/captcha.proto\x12\n" +
	"xtravel.v1\x1a\x1cgoogle/api/annotations.proto\"/\n" +
	"\x11GetCaptchaRequest\x12\f\n" +
	"\x01w\x18\x01 \x01(\x05R\x01w\x12\f\n" +
	"\x01h\x18\x02 \x01(\x05R\x01h\"7\n" +
	"\x0fGetCaptchaReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image2v\n" +
	"\x0eCaptchaService\x12d\n" +
	"\n" +
	"GetCaptcha\x12\x1d.xtravel.v1.GetCaptchaRequest\x1a\x1b.xtravel.v1.GetCaptchaReply\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/common/captchaB2Z0github.com/lixiaoping4258/ymkj/api/xtravel/v1;v1b\x06proto3"

var (
	file_api_xtravel_v1_captcha_proto_rawDescOnce sync.Once
	file_api_xtravel_v1_captcha_proto_rawDescData []byte
)

func file_api_xtravel_v1_captcha_proto_rawDescGZIP() []byte {
	file_api_xtravel_v1_captcha_proto_rawDescOnce.Do(func() {
		file_api_xtravel_v1_captcha_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_xtravel_v1_captcha_proto_rawDesc), len(file_api_xtravel_v1_captcha_proto_rawDesc)))
	})
	return file_api_xtravel_v1_captcha_proto_rawDescData
}

var file_api_xtravel_v1_captcha_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_xtravel_v1_captcha_proto_goTypes = []any{
	(*GetCaptchaRequest)(nil), // 0: xtravel.v1.GetCaptchaRequest
	(*GetCaptchaReply)(nil),   // 1: xtravel.v1.GetCaptchaReply
}
var file_api_xtravel_v1_captcha_proto_depIdxs = []int32{
	0, // 0: xtravel.v1.CaptchaService.GetCaptcha:input_type -> xtravel.v1.GetCaptchaRequest
	1, // 1: xtravel.v1.CaptchaService.GetCaptcha:output_type -> xtravel.v1.GetCaptchaReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_xtravel_v1_captcha_proto_init() }
func file_api_xtravel_v1_captcha_proto_init() {
	if File_api_xtravel_v1_captcha_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_xtravel_v1_captcha_proto_rawDesc), len(file_api_xtravel_v1_captcha_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_xtravel_v1_captcha_proto_goTypes,
		DependencyIndexes: file_api_xtravel_v1_captcha_proto_depIdxs,
		MessageInfos:      file_api_xtravel_v1_captcha_proto_msgTypes,
	}.Build()
	File_api_xtravel_v1_captcha_proto = out.File
	file_api_xtravel_v1_captcha_proto_goTypes = nil
	file_api_xtravel_v1_captcha_proto_depIdxs = nil
}
