// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: api/xtravel/v1/captcha.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CaptchaService_GetCaptcha_FullMethodName = "/xtravel.v1.CaptchaService/GetCaptcha"
)

// CaptchaServiceClient is the client API for CaptchaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CaptchaService 图形验证码。
// 对应原项目 app/api/controller/CaptchaController.php
// 路由在 app/api/route/common.php：Route::get('captcha', [CaptchaController::class, 'index'])
// 分组前缀 v1/common/ -> 完整路径 /v1/common/captcha
//
// ⚠️⚠️ 修正：我第一版按文件名推导成 /v1/captcha，**是错的**。
// 实际要跟踪 Route::group 的前缀（common.php 的 group 是 'v1/common/'）。
type CaptchaServiceClient interface {
	// 获取图形验证码
	//
	// 原实现：
	//
	//	$w = $this->request->get('w/d', 150);
	//	if($w < 1 || $w > 300) { $w = 150; }     // 越界回默认，不是 clamp
	//	$h = $this->request->get('h/d', 40);
	//	if($h < 1 || $h > 300) { $h = 40; }
	//	$result = CaptchaLogic::getCaptcha($w, $h);
	//	return $this->data($result);
	//
	// 免登录（CaptchaController::$notNeedLogin = ['index','captcha']）。
	GetCaptcha(ctx context.Context, in *GetCaptchaRequest, opts ...grpc.CallOption) (*GetCaptchaReply, error)
}

type captchaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCaptchaServiceClient(cc grpc.ClientConnInterface) CaptchaServiceClient {
	return &captchaServiceClient{cc}
}

func (c *captchaServiceClient) GetCaptcha(ctx context.Context, in *GetCaptchaRequest, opts ...grpc.CallOption) (*GetCaptchaReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCaptchaReply)
	err := c.cc.Invoke(ctx, CaptchaService_GetCaptcha_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CaptchaServiceServer is the server API for CaptchaService service.
// All implementations must embed UnimplementedCaptchaServiceServer
// for forward compatibility.
//
// CaptchaService 图形验证码。
// 对应原项目 app/api/controller/CaptchaController.php
// 路由在 app/api/route/common.php：Route::get('captcha', [CaptchaController::class, 'index'])
// 分组前缀 v1/common/ -> 完整路径 /v1/common/captcha
//
// ⚠️⚠️ 修正：我第一版按文件名推导成 /v1/captcha，**是错的**。
// 实际要跟踪 Route::group 的前缀（common.php 的 group 是 'v1/common/'）。
type CaptchaServiceServer interface {
	// 获取图形验证码
	//
	// 原实现：
	//
	//	$w = $this->request->get('w/d', 150);
	//	if($w < 1 || $w > 300) { $w = 150; }     // 越界回默认，不是 clamp
	//	$h = $this->request->get('h/d', 40);
	//	if($h < 1 || $h > 300) { $h = 40; }
	//	$result = CaptchaLogic::getCaptcha($w, $h);
	//	return $this->data($result);
	//
	// 免登录（CaptchaController::$notNeedLogin = ['index','captcha']）。
	GetCaptcha(context.Context, *GetCaptchaRequest) (*GetCaptchaReply, error)
	mustEmbedUnimplementedCaptchaServiceServer()
}

// UnimplementedCaptchaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCaptchaServiceServer struct{}

func (UnimplementedCaptchaServiceServer) GetCaptcha(context.Context, *GetCaptchaRequest) (*GetCaptchaReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCaptcha not implemented")
}
func (UnimplementedCaptchaServiceServer) mustEmbedUnimplementedCaptchaServiceServer() {}
func (UnimplementedCaptchaServiceServer) testEmbeddedByValue()                        {}

// UnsafeCaptchaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CaptchaServiceServer will
// result in compilation errors.
type UnsafeCaptchaServiceServer interface {
	mustEmbedUnimplementedCaptchaServiceServer()
}

func RegisterCaptchaServiceServer(s grpc.ServiceRegistrar, srv CaptchaServiceServer) {
	// If the following call panics, it indicates UnimplementedCaptchaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CaptchaService_ServiceDesc, srv)
}

func _CaptchaService_GetCaptcha_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCaptchaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptchaServiceServer).GetCaptcha(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptchaService_GetCaptcha_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptchaServiceServer).GetCaptcha(ctx, req.(*GetCaptchaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CaptchaService_ServiceDesc is the grpc.ServiceDesc for CaptchaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CaptchaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xtravel.v1.CaptchaService",
	HandlerType: (*CaptchaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCaptcha",
			Handler:    _CaptchaService_GetCaptcha_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/xtravel/v1/captcha.proto",
}
