// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.35.1
// source: api/xtravel/v1/captcha.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationCaptchaServiceGetCaptcha = "/xtravel.v1.CaptchaService/GetCaptcha"

type CaptchaServiceHTTPServer interface {
	// GetCaptcha 获取图形验证码
	//
	// 原实现：
	//
	//	$w = $this->request->get('w/d', 150);
	//	if($w < 1 || $w > 300) { $w = 150; }     // 越界回默认，不是 clamp
	//	$h = $this->request->get('h/d', 40);
	//	if($h < 1 || $h > 300) { $h = 40; }
	//	$result = CaptchaLogic::getCaptcha($w, $h);
	//	return $this->data($result);
	//
	// 免登录（CaptchaController::$notNeedLogin = ['index','captcha']）。
	GetCaptcha(context.Context, *GetCaptchaRequest) (*GetCaptchaReply, error)
}

func RegisterCaptchaServiceHTTPServer(s *http.Server, srv CaptchaServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/common/captcha", _CaptchaService_GetCaptcha0_HTTP_Handler(srv))
}

func _CaptchaService_GetCaptcha0_HTTP_Handler(srv CaptchaServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCaptchaRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCaptchaServiceGetCaptcha)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCaptcha(ctx, req.(*GetCaptchaRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetCaptchaReply)
		return ctx.Result(200, reply)
	}
}

type CaptchaServiceHTTPClient interface {
	// GetCaptcha 获取图形验证码
	//
	// 原实现：
	//
	//	$w = $this->request->get('w/d', 150);
	//	if($w < 1 || $w > 300) { $w = 150; }     // 越界回默认，不是 clamp
	//	$h = $this->request->get('h/d', 40);
	//	if($h < 1 || $h > 300) { $h = 40; }
	//	$result = CaptchaLogic::getCaptcha($w, $h);
	//	return $this->data($result);
	//
	// 免登录（CaptchaController::$notNeedLogin = ['index','captcha']）。
	GetCaptcha(ctx context.Context, req *GetCaptchaRequest, opts ...http.CallOption) (rsp *GetCaptchaReply, err error)
}

type CaptchaServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewCaptchaServiceHTTPClient(client *http.Client) CaptchaServiceHTTPClient {
	return &CaptchaServiceHTTPClientImpl{client}
}

// GetCaptcha 获取图形验证码
//
// 原实现：
//
//	$w = $this->request->get('w/d', 150);
//	if($w < 1 || $w > 300) { $w = 150; }     // 越界回默认，不是 clamp
//	$h = $this->request->get('h/d', 40);
//	if($h < 1 || $h > 300) { $h = 40; }
//	$result = CaptchaLogic::getCaptcha($w, $h);
//	return $this->data($result);
//
// 免登录（CaptchaController::$notNeedLogin = ['index','captcha']）。
func (c *CaptchaServiceHTTPClientImpl) GetCaptcha(ctx context.Context, in *GetCaptchaRequest, opts ...http.CallOption) (*GetCaptchaReply, error) {
	var out GetCaptchaReply
	pattern := "/v1/common/captcha"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCaptchaServiceGetCaptcha))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
