// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.35.1
// source: api/xtravel/v1/common.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationCommonServiceGetConfig = "/xtravel.v1.CommonService/GetConfig"
const OperationCommonServiceGetTradeConfig = "/xtravel.v1.CommonService/GetTradeConfig"

type CommonServiceHTTPServer interface {
	// GetConfig 手续费/交易开关等基础配置
	// 原: ConfigController::index  (免登录)
	GetConfig(context.Context, *GetConfigRequest) (*GetConfigReply, error)
	// GetTradeConfig 交易配置（开关 + 限制时段）
	// 原: IndexController::tradeConfig  (免登录)
	GetTradeConfig(context.Context, *GetTradeConfigRequest) (*GetTradeConfigReply, error)
}

func RegisterCommonServiceHTTPServer(s *http.Server, srv CommonServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/common/config", _CommonService_GetConfig0_HTTP_Handler(srv))
	r.GET("/v1/common/trade/config", _CommonService_GetTradeConfig0_HTTP_Handler(srv))
}

func _CommonService_GetConfig0_HTTP_Handler(srv CommonServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetConfigRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCommonServiceGetConfig)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetConfig(ctx, req.(*GetConfigRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetConfigReply)
		return ctx.Result(200, reply)
	}
}

func _CommonService_GetTradeConfig0_HTTP_Handler(srv CommonServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetTradeConfigRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCommonServiceGetTradeConfig)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetTradeConfig(ctx, req.(*GetTradeConfigRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetTradeConfigReply)
		return ctx.Result(200, reply)
	}
}

type CommonServiceHTTPClient interface {
	// GetConfig 手续费/交易开关等基础配置
	// 原: ConfigController::index  (免登录)
	GetConfig(ctx context.Context, req *GetConfigRequest, opts ...http.CallOption) (rsp *GetConfigReply, err error)
	// GetTradeConfig 交易配置（开关 + 限制时段）
	// 原: IndexController::tradeConfig  (免登录)
	GetTradeConfig(ctx context.Context, req *GetTradeConfigRequest, opts ...http.CallOption) (rsp *GetTradeConfigReply, err error)
}

type CommonServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewCommonServiceHTTPClient(client *http.Client) CommonServiceHTTPClient {
	return &CommonServiceHTTPClientImpl{client}
}

// GetConfig 手续费/交易开关等基础配置
// 原: ConfigController::index  (免登录)
func (c *CommonServiceHTTPClientImpl) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...http.CallOption) (*GetConfigReply, error) {
	var out GetConfigReply
	pattern := "/v1/common/config"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCommonServiceGetConfig))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetTradeConfig 交易配置（开关 + 限制时段）
// 原: IndexController::tradeConfig  (免登录)
func (c *CommonServiceHTTPClientImpl) GetTradeConfig(ctx context.Context, in *GetTradeConfigRequest, opts ...http.CallOption) (*GetTradeConfigReply, error) {
	var out GetTradeConfigReply
	pattern := "/v1/common/trade/config"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCommonServiceGetTradeConfig))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
