// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: api/xtravel/v1/common.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CommonService_GetConfig_FullMethodName        = "/xtravel.v1.CommonService/GetConfig"
	CommonService_GetTradeConfig_FullMethodName   = "/xtravel.v1.CommonService/GetTradeConfig"
	CommonService_GetProtocol_FullMethodName      = "/xtravel.v1.CommonService/GetProtocol"
	CommonService_GetPlatformLists_FullMethodName = "/xtravel.v1.CommonService/GetPlatformLists"
)

// CommonServiceClient is the client API for CommonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CommonService 公共接口。
// 对应原项目 app/api/route/common.php + app/api/controller/v1/common/*。
//
// 路径保持 /v1/common/... 不变，前端无需改动。
//
// ⚠️ 本文件的 json_name 是 camelCase —— 因为原 PHP 源码里这些键就是
// camelCase（'outFee'、'tradeSwitch'、'isOpen'…），不是 DB 列名。
// 对比 user.proto：那边直接透传 DB 行，所以是 snake_case。
// **每个字段都必须对着原 PHP 的实际输出确认，不能套用统一约定。**
type CommonServiceClient interface {
	// 手续费/交易开关等基础配置
	// 原: ConfigController::index  (免登录)
	GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigReply, error)
	// 交易配置（开关 + 限制时段）
	// 原: IndexController::tradeConfig  (免登录)
	GetTradeConfig(ctx context.Context, in *GetTradeConfigRequest, opts ...grpc.CallOption) (*GetTradeConfigReply, error)
	// 服务协议
	//
	// 原实现 IndexLogic::getPolicyByType($type)：
	//
	//	title   => ConfigService::get('agreement', $type . '_title', '')
	//	content => ConfigService::get('agreement', $type . '_content', '')
	//
	// 配置缺失时两个键都是**空字符串**（默认 ”），不是 null。
	// 路由在 common.php（group 'v1/common/'），方法却在 IndexController —— 跨文件。
	// IndexController::$notNeedLogin 含 'policy' -> 免登录。
	GetProtocol(ctx context.Context, in *GetProtocolRequest, opts ...grpc.CallOption) (*GetProtocolReply, error)
	// 第三方平台列表
	//
	// 原实现 OpenAppLogic::getThirdAppsList($state = 1)：
	//
	//	App::where(['state' => $state, 'type' => 2])->field('name,flag')->select()->toArray();
	//
	// type = 2 是硬编码；state 默认 1 但控制器没传参，所以恒为 1。
	GetPlatformLists(ctx context.Context, in *GetPlatformListsRequest, opts ...grpc.CallOption) (*GetPlatformListsReply, error)
}

type commonServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCommonServiceClient(cc grpc.ClientConnInterface) CommonServiceClient {
	return &commonServiceClient{cc}
}

func (c *commonServiceClient) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConfigReply)
	err := c.cc.Invoke(ctx, CommonService_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commonServiceClient) GetTradeConfig(ctx context.Context, in *GetTradeConfigRequest, opts ...grpc.CallOption) (*GetTradeConfigReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTradeConfigReply)
	err := c.cc.Invoke(ctx, CommonService_GetTradeConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commonServiceClient) GetProtocol(ctx context.Context, in *GetProtocolRequest, opts ...grpc.CallOption) (*GetProtocolReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProtocolReply)
	err := c.cc.Invoke(ctx, CommonService_GetProtocol_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commonServiceClient) GetPlatformLists(ctx context.Context, in *GetPlatformListsRequest, opts ...grpc.CallOption) (*GetPlatformListsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlatformListsReply)
	err := c.cc.Invoke(ctx, CommonService_GetPlatformLists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommonServiceServer is the server API for CommonService service.
// All implementations must embed UnimplementedCommonServiceServer
// for forward compatibility.
//
// CommonService 公共接口。
// 对应原项目 app/api/route/common.php + app/api/controller/v1/common/*。
//
// 路径保持 /v1/common/... 不变，前端无需改动。
//
// ⚠️ 本文件的 json_name 是 camelCase —— 因为原 PHP 源码里这些键就是
// camelCase（'outFee'、'tradeSwitch'、'isOpen'…），不是 DB 列名。
// 对比 user.proto：那边直接透传 DB 行，所以是 snake_case。
// **每个字段都必须对着原 PHP 的实际输出确认，不能套用统一约定。**
type CommonServiceServer interface {
	// 手续费/交易开关等基础配置
	// 原: ConfigController::index  (免登录)
	GetConfig(context.Context, *GetConfigRequest) (*GetConfigReply, error)
	// 交易配置（开关 + 限制时段）
	// 原: IndexController::tradeConfig  (免登录)
	GetTradeConfig(context.Context, *GetTradeConfigRequest) (*GetTradeConfigReply, error)
	// 服务协议
	//
	// 原实现 IndexLogic::getPolicyByType($type)：
	//
	//	title   => ConfigService::get('agreement', $type . '_title', '')
	//	content => ConfigService::get('agreement', $type . '_content', '')
	//
	// 配置缺失时两个键都是**空字符串**（默认 ”），不是 null。
	// 路由在 common.php（group 'v1/common/'），方法却在 IndexController —— 跨文件。
	// IndexController::$notNeedLogin 含 'policy' -> 免登录。
	GetProtocol(context.Context, *GetProtocolRequest) (*GetProtocolReply, error)
	// 第三方平台列表
	//
	// 原实现 OpenAppLogic::getThirdAppsList($state = 1)：
	//
	//	App::where(['state' => $state, 'type' => 2])->field('name,flag')->select()->toArray();
	//
	// type = 2 是硬编码；state 默认 1 但控制器没传参，所以恒为 1。
	GetPlatformLists(context.Context, *GetPlatformListsRequest) (*GetPlatformListsReply, error)
	mustEmbedUnimplementedCommonServiceServer()
}

// UnimplementedCommonServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCommonServiceServer struct{}

func (UnimplementedCommonServiceServer) GetConfig(context.Context, *GetConfigRequest) (*GetConfigReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedCommonServiceServer) GetTradeConfig(context.Context, *GetTradeConfigRequest) (*GetTradeConfigReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTradeConfig not implemented")
}
func (UnimplementedCommonServiceServer) GetProtocol(context.Context, *GetProtocolRequest) (*GetProtocolReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProtocol not implemented")
}
func (UnimplementedCommonServiceServer) GetPlatformLists(context.Context, *GetPlatformListsRequest) (*GetPlatformListsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlatformLists not implemented")
}
func (UnimplementedCommonServiceServer) mustEmbedUnimplementedCommonServiceServer() {}
func (UnimplementedCommonServiceServer) testEmbeddedByValue()                       {}

// UnsafeCommonServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommonServiceServer will
// result in compilation errors.
type UnsafeCommonServiceServer interface {
	mustEmbedUnimplementedCommonServiceServer()
}

func RegisterCommonServiceServer(s grpc.ServiceRegistrar, srv CommonServiceServer) {
	// If the following call panics, it indicates UnimplementedCommonServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CommonService_ServiceDesc, srv)
}

func _CommonService_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommonServiceServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommonService_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommonServiceServer).GetConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommonService_GetTradeConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTradeConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommonServiceServer).GetTradeConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommonService_GetTradeConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommonServiceServer).GetTradeConfig(ctx, req.(*GetTradeConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommonService_GetProtocol_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProtocolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommonServiceServer).GetProtocol(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommonService_GetProtocol_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommonServiceServer).GetProtocol(ctx, req.(*GetProtocolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommonService_GetPlatformLists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlatformListsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommonServiceServer).GetPlatformLists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommonService_GetPlatformLists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommonServiceServer).GetPlatformLists(ctx, req.(*GetPlatformListsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CommonService_ServiceDesc is the grpc.ServiceDesc for CommonService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommonService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xtravel.v1.CommonService",
	HandlerType: (*CommonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConfig",
			Handler:    _CommonService_GetConfig_Handler,
		},
		{
			MethodName: "GetTradeConfig",
			Handler:    _CommonService_GetTradeConfig_Handler,
		},
		{
			MethodName: "GetProtocol",
			Handler:    _CommonService_GetProtocol_Handler,
		},
		{
			MethodName: "GetPlatformLists",
			Handler:    _CommonService_GetPlatformLists_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/xtravel/v1/common.proto",
}
