// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/xtravel/v1/common.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_api_xtravel_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_xtravel_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_xtravel_v1_common_proto_rawDescGZIP(), []int{0}
}

type GetConfigReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 手续费配置(%)  原: ConfigService::get('trade','outFee')
	//
	// 用 google.protobuf.Value 是因为原项目这里的类型是不确定的 ——
	// ConfigService 会把 json 字符串 decode 成数组/标量，proto 定不了具体类型。
	OutFee *structpb.Value `protobuf:"bytes,1,opt,name=out_fee,json=outFee,proto3" json:"out_fee,omitempty"`
	// ⚠️ 命名陷阱：原项目这个 key 叫 tradeSwitch，但它的值其实是
	//
	//	TradeConfigService::checkTradeTime() 的**完整返回对象**，不是布尔开关。
	//	为了前端不改，这里保持原样。
	TradeSwitch *TradeTimeStatus `protobuf:"bytes,2,opt,name=trade_switch,json=tradeSwitch,proto3" json:"trade_switch,omitempty"`
	// 求购/兑出限制  原: ConfigService::get('trade','buyOrSaleConfig')
	BuyOrSaleConfig *structpb.Value `protobuf:"bytes,3,opt,name=buy_or_sale_config,json=buyOrSaleConfig,proto3" json:"buy_or_sale_config,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetConfigReply) Reset() {
	*x = GetConfigReply{}
	mi := &file_api_xtravel_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigReply) ProtoMessage() {}

func (x *GetConfigReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_xtravel_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigReply.ProtoReflect.Descriptor instead.
func (*GetConfigReply) Descriptor() ([]byte, []int) {
	return file_api_xtravel_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *GetConfigReply) GetOutFee() *structpb.Value {
	if x != nil {
		return x.OutFee
	}
	return nil
}

func (x *GetConfigReply) GetTradeSwitch() *TradeTimeStatus {
	if x != nil {
		return x.TradeSwitch
	}
	return nil
}

func (x *GetConfigReply) GetBuyOrSaleConfig() *structpb.Value {
	if x != nil {
		return x.BuyOrSaleConfig
	}
	return nil
}

// TradeTimeStatus 对应 app/common/service/TradeConfigService::checkTradeTime()
type TradeTimeStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 全局总开关。原: ConfigService::get('trade','tradeSwitch',0)
	// 注意原项目注释写「0=开启, 1=关闭」，与直觉相反。
	TradeSwitch *structpb.Value `protobuf:"bytes,1,opt,name=trade_switch,json=tradeSwitch,proto3" json:"trade_switch,omitempty"`
	// 当前是否开市 0/1
	IsOpen int32 `protobuf:"varint,2,opt,name=is_open,json=isOpen,proto3" json:"is_open,omitempty"`
	// workday | holiday
	TodayType string `protobuf:"bytes,3,opt,name=today_type,json=todayType,proto3" json:"today_type,omitempty"`
	// 工作日 | 节假日
	TodayTypeStr string `protobuf:"bytes,4,opt,name=today_type_str,json=todayTypeStr,proto3" json:"today_type_str,omitempty"`
	// 当前适用的交易时段
	Periods []*TradePeriod `protobuf:"bytes,5,rep,name=periods,proto3" json:"periods,omitempty"`
	// 给前端展示的文案
	Tips          string `protobuf:"bytes,6,opt,name=tips,proto3" json:"tips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradeTimeStatus) Reset() {
	*x = TradeTimeStatus{}
	mi := &file_api_xtravel_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeTimeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeTimeStatus) ProtoMessage() {}

func (x *TradeTimeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_xtravel_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeTimeStatus.ProtoReflect.Descriptor instead.
func (*TradeTimeStatus) Descriptor() ([]byte, []int) {
	return file_api_xtravel_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *TradeTimeStatus) GetTradeSwitch() *structpb.Value {
	if x != nil {
		return x.TradeSwitch
	}
	return nil
}

func (x *TradeTimeStatus) GetIsOpen() int32 {
	if x != nil {
		return x.IsOpen
	}
	return 0
}

func (x *TradeTimeStatus) GetTodayType() string {
	if x != nil {
		return x.TodayType
	}
	return ""
}

func (x *TradeTimeStatus) GetTodayTypeStr() string {
	if x != nil {
		return x.TodayTypeStr
	}
	return ""
}

func (x *TradeTimeStatus) GetPeriods() []*TradePeriod {
	if x != nil {
		return x.Periods
	}
	return nil
}

func (x *TradeTimeStatus) GetTips() string {
	if x != nil {
		return x.Tips
	}
	return ""
}

type TradePeriod struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         string                 `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           string                 `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradePeriod) Reset() {
	*x = TradePeriod{}
	mi := &file_api_xtravel_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradePeriod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradePeriod) ProtoMessage() {}

func (x *TradePeriod) ProtoReflect() protoreflect.Message {
	mi := &file_api_xtravel_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradePeriod.ProtoReflect.Descriptor instead.
func (*TradePeriod) Descriptor() ([]byte, []int) {
	return file_api_xtravel_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *TradePeriod) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *TradePeriod) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

type GetTradeConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTradeConfigRequest) Reset() {
	*x = GetTradeConfigRequest{}
	mi := &file_api_xtravel_v1_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTradeConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTradeConfigRequest) ProtoMessage() {}

func (x *GetTradeConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_xtravel_v1_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTradeConfigRequest.ProtoReflect.Descriptor instead.
func (*GetTradeConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_xtravel_v1_common_proto_rawDescGZIP(), []int{4}
}

type GetTradeConfigReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 原: ConfigService::get('trade','switch')
	Switch *structpb.Value `protobuf:"bytes,1,opt,name=switch,proto3" json:"switch,omitempty"`
	// 原: ConfigService::get('trade','limitTime')
	LimitTime     *structpb.Value `protobuf:"bytes,2,opt,name=limit_time,json=limitTime,proto3" json:"limit_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTradeConfigReply) Reset() {
	*x = GetTradeConfigReply{}
	mi := &file_api_xtravel_v1_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTradeConfigReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTradeConfigReply) ProtoMessage() {}

func (x *GetTradeConfigReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_xtravel_v1_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTradeConfigReply.ProtoReflect.Descriptor instead.
func (*GetTradeConfigReply) Descriptor() ([]byte, []int) {
	return file_api_xtravel_v1_common_proto_rawDescGZIP(), []int{5}
}

func (x *GetTradeConfigReply) GetSwitch() *structpb.Value {
	if x != nil {
		return x.Switch
	}
	return nil
}

func (x *GetTradeConfigReply) GetLimitTime() *structpb.Value {
	if x != nil {
		return x.LimitTime
	}
	return nil
}

var File_api_xtravel_v1_common_proto protoreflect.FileDescriptor

const file_api_xtravel_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/xtravel/v1/common.proto\x12\n" +
	"xtravel.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x12\n" +
	"\x10GetConfigRequest\"\xc6\x01\n" +
	"\x0eGetConfigReply\x12/\n" +
	"\aout_fee\x18\x01 \x01(\v2\x16.google.protobuf.ValueR\x06outFee\x12>\n" +
	"\ftrade_switch\x18\x02 \x01(\v2\x1b.xtravel.v1.TradeTimeStatusR\vtradeSwitch\x12C\n" +
	"\x12buy_or_sale_config\x18\x03 \x01(\v2\x16.google.protobuf.ValueR\x0fbuyOrSaleConfig\"\xf1\x01\n" +
	"\x0fTradeTimeStatus\x129\n" +
	"\ftrade_switch\x18\x01 \x01(\v2\x16.google.protobuf.ValueR\vtradeSwitch\x12\x17\n" +
	"\ais_open\x18\x02 \x01(\x05R\x06isOpen\x12\x1d\n" +
	"\n" +
	"today_type\x18\x03 \x01(\tR\ttodayType\x12$\n" +
	"\x0etoday_type_str\x18\x04 \x01(\tR\ftodayTypeStr\x121\n" +
	"\aperiods\x18\x05 \x03(\v2\x17.xtravel.v1.TradePeriodR\aperiods\x12\x12\n" +
	"\x04tips\x18\x06 \x01(\tR\x04tips\"5\n" +
	"\vTradePeriod\x12\x14\n" +
	"\x05start\x18\x01 \x01(\tR\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\tR\x03end\"\x17\n" +
	"\x15GetTradeConfigRequest\"|\n" +
	"\x13GetTradeConfigReply\x12.\n" +
	"\x06switch\x18\x01 \x01(\v2\x16.google.protobuf.ValueR\x06switch\x125\n" +
	"\n" +
	"limit_time\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\tlimitTime2\xe8\x01\n" +
	"\rCommonService\x12`\n" +
	"\tGetConfig\x12\x1c.xtravel.v1.GetConfigRequest\x1a\x1a.xtravel.v1.GetConfigReply\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/common/config\x12u\n" +
	"\x0eGetTradeConfig\x12!.xtravel.v1.GetTradeConfigRequest\x1a\x1f.xtravel.v1.GetTradeConfigReply\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/common/trade/configB2Z0github.com/lixiaoping4258/ymkj/api/xtravel/v1;v1b\x06proto3"

var (
	file_api_xtravel_v1_common_proto_rawDescOnce sync.Once
	file_api_xtravel_v1_common_proto_rawDescData []byte
)

func file_api_xtravel_v1_common_proto_rawDescGZIP() []byte {
	file_api_xtravel_v1_common_proto_rawDescOnce.Do(func() {
		file_api_xtravel_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_xtravel_v1_common_proto_rawDesc), len(file_api_xtravel_v1_common_proto_rawDesc)))
	})
	return file_api_xtravel_v1_common_proto_rawDescData
}

var file_api_xtravel_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_xtravel_v1_common_proto_goTypes = []any{
	(*GetConfigRequest)(nil),      // 0: xtravel.v1.GetConfigRequest
	(*GetConfigReply)(nil),        // 1: xtravel.v1.GetConfigReply
	(*TradeTimeStatus)(nil),       // 2: xtravel.v1.TradeTimeStatus
	(*TradePeriod)(nil),           // 3: xtravel.v1.TradePeriod
	(*GetTradeConfigRequest)(nil), // 4: xtravel.v1.GetTradeConfigRequest
	(*GetTradeConfigReply)(nil),   // 5: xtravel.v1.GetTradeConfigReply
	(*structpb.Value)(nil),        // 6: google.protobuf.Value
}
var file_api_xtravel_v1_common_proto_depIdxs = []int32{
	6, // 0: xtravel.v1.GetConfigReply.out_fee:type_name -> google.protobuf.Value
	2, // 1: xtravel.v1.GetConfigReply.trade_switch:type_name -> xtravel.v1.TradeTimeStatus
	6, // 2: xtravel.v1.GetConfigReply.buy_or_sale_config:type_name -> google.protobuf.Value
	6, // 3: xtravel.v1.TradeTimeStatus.trade_switch:type_name -> google.protobuf.Value
	3, // 4: xtravel.v1.TradeTimeStatus.periods:type_name -> xtravel.v1.TradePeriod
	6, // 5: xtravel.v1.GetTradeConfigReply.switch:type_name -> google.protobuf.Value
	6, // 6: xtravel.v1.GetTradeConfigReply.limit_time:type_name -> google.protobuf.Value
	0, // 7: xtravel.v1.CommonService.GetConfig:input_type -> xtravel.v1.GetConfigRequest
	4, // 8: xtravel.v1.CommonService.GetTradeConfig:input_type -> xtravel.v1.GetTradeConfigRequest
	1, // 9: xtravel.v1.CommonService.GetConfig:output_type -> xtravel.v1.GetConfigReply
	5, // 10: xtravel.v1.CommonService.GetTradeConfig:output_type -> xtravel.v1.GetTradeConfigReply
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_api_xtravel_v1_common_proto_init() }
func file_api_xtravel_v1_common_proto_init() {
	if File_api_xtravel_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_xtravel_v1_common_proto_rawDesc), len(file_api_xtravel_v1_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_xtravel_v1_common_proto_goTypes,
		DependencyIndexes: file_api_xtravel_v1_common_proto_depIdxs,
		MessageInfos:      file_api_xtravel_v1_common_proto_msgTypes,
	}.Build()
	File_api_xtravel_v1_common_proto = out.File
	file_api_xtravel_v1_common_proto_goTypes = nil
	file_api_xtravel_v1_common_proto_depIdxs = nil
}
