// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/xtravel/v1/index.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetIndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIndexRequest) Reset() {
	*x = GetIndexRequest{}
	mi := &file_api_xtravel_v1_index_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIndexRequest) ProtoMessage() {}

func (x *GetIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_xtravel_v1_index_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIndexRequest.ProtoReflect.Descriptor instead.
func (*GetIndexRequest) Descriptor() ([]byte, []int) {
	return file_api_xtravel_v1_index_proto_rawDescGZIP(), []int{0}
}

// GetIndexReply 对应 ['page'=>..., 'article'=>[...]]。
type GetIndexReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *DecoratePage          `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	Article       []*HomeArticle         `protobuf:"bytes,2,rep,name=article,proto3" json:"article,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIndexReply) Reset() {
	*x = GetIndexReply{}
	mi := &file_api_xtravel_v1_index_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIndexReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIndexReply) ProtoMessage() {}

func (x *GetIndexReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_xtravel_v1_index_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIndexReply.ProtoReflect.Descriptor instead.
func (*GetIndexReply) Descriptor() ([]byte, []int) {
	return file_api_xtravel_v1_index_proto_rawDescGZIP(), []int{1}
}

func (x *GetIndexReply) GetPage() *DecoratePage {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *GetIndexReply) GetArticle() []*HomeArticle {
	if x != nil {
		return x.Article
	}
	return nil
}

// DecoratePage 对应 DecoratePage::field(['type','name','data','meta'])->toArray()。
//
// ⚠️ data / meta 是 text 列且模型**没有 json 转换**，所以 PHP 输出的是
//
//	**原始 JSON 字符串**，不是数组。这里也用 string。
//
// ⚠️ 主键 id **不在** field 列表里，所以响应里没有 id。
type DecoratePage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          int32                  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Meta          string                 `protobuf:"bytes,4,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecoratePage) Reset() {
	*x = DecoratePage{}
	mi := &file_api_xtravel_v1_index_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecoratePage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecoratePage) ProtoMessage() {}

func (x *DecoratePage) ProtoReflect() protoreflect.Message {
	mi := &file_api_xtravel_v1_index_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecoratePage.ProtoReflect.Descriptor instead.
func (*DecoratePage) Descriptor() ([]byte, []int) {
	return file_api_xtravel_v1_index_proto_rawDescGZIP(), []int{2}
}

func (x *DecoratePage) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *DecoratePage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DecoratePage) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *DecoratePage) GetMeta() string {
	if x != nil {
		return x.Meta
	}
	return ""
}

// HomeArticle 对应 getIndexData 里文章的对外形态（8 个键）。
//
// ⚠️ click_actual / click_virtual 被 `->hidden([...])` 藏掉了，
//
//	对外只有计算列 **click**（= click_actual + click_virtual）。
type HomeArticle struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// ⚠️ 列名就叫 desc（SQL 保留字），PHP 的 toArray() 键名也是 "desc"
	Desc     string `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	Abstract string `protobuf:"bytes,4,opt,name=abstract,proto3" json:"abstract,omitempty"`
	Image    string `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	Author   string `protobuf:"bytes,6,opt,name=author,proto3" json:"author,omitempty"`
	// x_article.create_time 是 int(11) -> PHP 输出数字
	CreateTime    int64 `protobuf:"varint,7,opt,name=create_time,proto3" json:"create_time,omitempty"`
	Click         int64 `protobuf:"varint,8,opt,name=click,proto3" json:"click,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HomeArticle) Reset() {
	*x = HomeArticle{}
	mi := &file_api_xtravel_v1_index_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HomeArticle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomeArticle) ProtoMessage() {}

func (x *HomeArticle) ProtoReflect() protoreflect.Message {
	mi := &file_api_xtravel_v1_index_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomeArticle.ProtoReflect.Descriptor instead.
func (*HomeArticle) Descriptor() ([]byte, []int) {
	return file_api_xtravel_v1_index_proto_rawDescGZIP(), []int{3}
}

func (x *HomeArticle) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HomeArticle) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *HomeArticle) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *HomeArticle) GetAbstract() string {
	if x != nil {
		return x.Abstract
	}
	return ""
}

func (x *HomeArticle) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *HomeArticle) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *HomeArticle) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *HomeArticle) GetClick() int64 {
	if x != nil {
		return x.Click
	}
	return 0
}

type GetDecorateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 对应 `$this->request->get('id/d')` —— 强制整数
	Id            int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDecorateRequest) Reset() {
	*x = GetDecorateRequest{}
	mi := &file_api_xtravel_v1_index_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDecorateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDecorateRequest) ProtoMessage() {}

func (x *GetDecorateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_xtravel_v1_index_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDecorateRequest.ProtoReflect.Descriptor instead.
func (*GetDecorateRequest) Descriptor() ([]byte, []int) {
	return file_api_xtravel_v1_index_proto_rawDescGZIP(), []int{4}
}

func (x *GetDecorateRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetDecorateReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *DecoratePage          `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDecorateReply) Reset() {
	*x = GetDecorateReply{}
	mi := &file_api_xtravel_v1_index_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDecorateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDecorateReply) ProtoMessage() {}

func (x *GetDecorateReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_xtravel_v1_index_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDecorateReply.ProtoReflect.Descriptor instead.
func (*GetDecorateReply) Descriptor() ([]byte, []int) {
	return file_api_xtravel_v1_index_proto_rawDescGZIP(), []int{5}
}

func (x *GetDecorateReply) GetPage() *DecoratePage {
	if x != nil {
		return x.Page
	}
	return nil
}

type GetBannerListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBannerListRequest) Reset() {
	*x = GetBannerListRequest{}
	mi := &file_api_xtravel_v1_index_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBannerListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBannerListRequest) ProtoMessage() {}

func (x *GetBannerListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_xtravel_v1_index_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBannerListRequest.ProtoReflect.Descriptor instead.
func (*GetBannerListRequest) Descriptor() ([]byte, []int) {
	return file_api_xtravel_v1_index_proto_rawDescGZIP(), []int{6}
}

// GetBannerListReply 顶层数组（原实现直接 return $lists）。
type GetBannerListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*BannerItem          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBannerListReply) Reset() {
	*x = GetBannerListReply{}
	mi := &file_api_xtravel_v1_index_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBannerListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBannerListReply) ProtoMessage() {}

func (x *GetBannerListReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_xtravel_v1_index_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBannerListReply.ProtoReflect.Descriptor instead.
func (*GetBannerListReply) Descriptor() ([]byte, []int) {
	return file_api_xtravel_v1_index_proto_rawDescGZIP(), []int{7}
}

func (x *GetBannerListReply) GetItems() []*BannerItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// BannerItem 对应 field(['id','title','image','jump_url','sort','create_time'])。
type BannerItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// 已经过 get_image_url 处理（完整 URL 原样返回）
	Image   string `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	JumpUrl string `protobuf:"bytes,4,opt,name=jump_url,proto3" json:"jump_url,omitempty"`
	Sort    int32  `protobuf:"varint,5,opt,name=sort,proto3" json:"sort,omitempty"`
	// datetime -> PHP 的 'Y-m-d H:i:s' 字符串
	CreateTime    string `protobuf:"bytes,6,opt,name=create_time,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BannerItem) Reset() {
	*x = BannerItem{}
	mi := &file_api_xtravel_v1_index_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BannerItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BannerItem) ProtoMessage() {}

func (x *BannerItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_xtravel_v1_index_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BannerItem.ProtoReflect.Descriptor instead.
func (*BannerItem) Descriptor() ([]byte, []int) {
	return file_api_xtravel_v1_index_proto_rawDescGZIP(), []int{8}
}

func (x *BannerItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BannerItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BannerItem) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *BannerItem) GetJumpUrl() string {
	if x != nil {
		return x.JumpUrl
	}
	return ""
}

func (x *BannerItem) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *BannerItem) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

var File_api_xtravel_v1_index_proto protoreflect.FileDescriptor

const file_api_xtravel_v1_index_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/xtravel/v1/index.proto\x12\n" +
	"xtravel.v1\x1a\x1cgoogle/api/annotations.proto\"\x11\n" +
	"\x0fGetIndexRequest\"p\n" +
	"\rGetIndexReply\x12,\n" +
	"\x04page\x18\x01 \x01(\v2\x18.xtravel.v1.DecoratePageR\x04page\x121\n" +
	"\aarticle\x18\x02 \x03(\v2\x17.xtravel.v1.HomeArticleR\aarticle\"^\n" +
	"\fDecoratePage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x05R\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\x12\x12\n" +
	"\x04meta\x18\x04 \x01(\tR\x04meta\"\xc9\x01\n" +
	"\vHomeArticle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04desc\x18\x03 \x01(\tR\x04desc\x12\x1a\n" +
	"\babstract\x18\x04 \x01(\tR\babstract\x12\x14\n" +
	"\x05image\x18\x05 \x01(\tR\x05image\x12\x16\n" +
	"\x06author\x18\x06 \x01(\tR\x06author\x12 \n" +
	"\vcreate_time\x18\a \x01(\x03R\vcreate_time\x12\x14\n" +
	"\x05click\x18\b \x01(\x03R\x05click\"$\n" +
	"\x12GetDecorateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"@\n" +
	"\x10GetDecorateReply\x12,\n" +
	"\x04page\x18\x01 \x01(\v2\x18.xtravel.v1.DecoratePageR\x04page\"\x16\n" +
	"\x14GetBannerListRequest\"B\n" +
	"\x12GetBannerListReply\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.xtravel.v1.BannerItemR\x05items\"\x9a\x01\n" +
	"\n" +
	"BannerItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x1a\n" +
	"\bjump_url\x18\x04 \x01(\tR\bjump_url\x12\x12\n" +
	"\x04sort\x18\x05 \x01(\x05R\x04sort\x12 \n" +
	"\vcreate_time\x18\x06 \x01(\tR\vcreate_time2\xc5\x02\n" +
	"\fIndexService\x12[\n" +
	"\bGetIndex\x12\x1b.xtravel.v1.GetIndexRequest\x1a\x19.xtravel.v1.GetIndexReply\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/index/index\x12g\n" +
	"\vGetDecorate\x12\x1e.xtravel.v1.GetDecorateRequest\x1a\x1c.xtravel.v1.GetDecorateReply\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/index/decorate\x12o\n" +
	"\rGetBannerList\x12 .xtravel.v1.GetBannerListRequest\x1a\x1e.xtravel.v1.GetBannerListReply\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/index/bannerListB2Z0github.com/lixiaoping4258/ymkj/api/xtravel/v1;v1b\x06proto3"

var (
	file_api_xtravel_v1_index_proto_rawDescOnce sync.Once
	file_api_xtravel_v1_index_proto_rawDescData []byte
)

func file_api_xtravel_v1_index_proto_rawDescGZIP() []byte {
	file_api_xtravel_v1_index_proto_rawDescOnce.Do(func() {
		file_api_xtravel_v1_index_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_xtravel_v1_index_proto_rawDesc), len(file_api_xtravel_v1_index_proto_rawDesc)))
	})
	return file_api_xtravel_v1_index_proto_rawDescData
}

var file_api_xtravel_v1_index_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_xtravel_v1_index_proto_goTypes = []any{
	(*GetIndexRequest)(nil),      // 0: xtravel.v1.GetIndexRequest
	(*GetIndexReply)(nil),        // 1: xtravel.v1.GetIndexReply
	(*DecoratePage)(nil),         // 2: xtravel.v1.DecoratePage
	(*HomeArticle)(nil),          // 3: xtravel.v1.HomeArticle
	(*GetDecorateRequest)(nil),   // 4: xtravel.v1.GetDecorateRequest
	(*GetDecorateReply)(nil),     // 5: xtravel.v1.GetDecorateReply
	(*GetBannerListRequest)(nil), // 6: xtravel.v1.GetBannerListRequest
	(*GetBannerListReply)(nil),   // 7: xtravel.v1.GetBannerListReply
	(*BannerItem)(nil),           // 8: xtravel.v1.BannerItem
}
var file_api_xtravel_v1_index_proto_depIdxs = []int32{
	2, // 0: xtravel.v1.GetIndexReply.page:type_name -> xtravel.v1.DecoratePage
	3, // 1: xtravel.v1.GetIndexReply.article:type_name -> xtravel.v1.HomeArticle
	2, // 2: xtravel.v1.GetDecorateReply.page:type_name -> xtravel.v1.DecoratePage
	8, // 3: xtravel.v1.GetBannerListReply.items:type_name -> xtravel.v1.BannerItem
	0, // 4: xtravel.v1.IndexService.GetIndex:input_type -> xtravel.v1.GetIndexRequest
	4, // 5: xtravel.v1.IndexService.GetDecorate:input_type -> xtravel.v1.GetDecorateRequest
	6, // 6: xtravel.v1.IndexService.GetBannerList:input_type -> xtravel.v1.GetBannerListRequest
	1, // 7: xtravel.v1.IndexService.GetIndex:output_type -> xtravel.v1.GetIndexReply
	5, // 8: xtravel.v1.IndexService.GetDecorate:output_type -> xtravel.v1.GetDecorateReply
	7, // 9: xtravel.v1.IndexService.GetBannerList:output_type -> xtravel.v1.GetBannerListReply
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_xtravel_v1_index_proto_init() }
func file_api_xtravel_v1_index_proto_init() {
	if File_api_xtravel_v1_index_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_xtravel_v1_index_proto_rawDesc), len(file_api_xtravel_v1_index_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_xtravel_v1_index_proto_goTypes,
		DependencyIndexes: file_api_xtravel_v1_index_proto_depIdxs,
		MessageInfos:      file_api_xtravel_v1_index_proto_msgTypes,
	}.Build()
	File_api_xtravel_v1_index_proto = out.File
	file_api_xtravel_v1_index_proto_goTypes = nil
	file_api_xtravel_v1_index_proto_depIdxs = nil
}
