// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: api/xtravel/v1/index.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IndexService_GetIndex_FullMethodName      = "/xtravel.v1.IndexService/GetIndex"
	IndexService_GetDecorate_FullMethodName   = "/xtravel.v1.IndexService/GetDecorate"
	IndexService_GetBannerList_FullMethodName = "/xtravel.v1.IndexService/GetBannerList"
)

// IndexServiceClient is the client API for IndexService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// IndexService 首页相关。
// 对应原项目 app/api/route/index.php（Route::group('/v1/index', ...)）
//
//	Route::get('index',      [IndexController::class,  'index']);
//	Route::get('decorate',   [IndexController::class,  'decorate']);
//	Route::get('config',     [IndexController::class,  'config']);     <- 未实现
//	Route::get('bannerList', [BannerController::class, 'getList']);
//	Route::get('test',       [IndexController::class,  'test']);       <- 未实现，见下
//
// ⚠️ IndexController::$notNeedLogin = ['test','index','config','policy','decorate']
//
//	BannerController::$notNeedLogin = ['getList']
//	-> 本文件的 4 条**全部免登录**。
type IndexServiceClient interface {
	// 首页聚合数据（装修页 + 最新 20 篇文章）
	// 原: IndexLogic::getIndexData()
	//
	//	return ['page' => $decoratePage, 'article' => $article];
	GetIndex(ctx context.Context, in *GetIndexRequest, opts ...grpc.CallOption) (*GetIndexReply, error)
	// 装修页详情
	// 原: IndexLogic::getDecorate($id)
	//
	//	DecoratePage::field(['type','name','data','meta'])->findOrEmpty($id)->toArray()
	GetDecorate(ctx context.Context, in *GetDecorateRequest, opts ...grpc.CallOption) (*GetDecorateReply, error)
	// 轮播图列表
	// 原: GetListLogic::getList()（有 10 秒缓存，键 'banner:list'，与 PHP 共用）
	GetBannerList(ctx context.Context, in *GetBannerListRequest, opts ...grpc.CallOption) (*GetBannerListReply, error)
}

type indexServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIndexServiceClient(cc grpc.ClientConnInterface) IndexServiceClient {
	return &indexServiceClient{cc}
}

func (c *indexServiceClient) GetIndex(ctx context.Context, in *GetIndexRequest, opts ...grpc.CallOption) (*GetIndexReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIndexReply)
	err := c.cc.Invoke(ctx, IndexService_GetIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexServiceClient) GetDecorate(ctx context.Context, in *GetDecorateRequest, opts ...grpc.CallOption) (*GetDecorateReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDecorateReply)
	err := c.cc.Invoke(ctx, IndexService_GetDecorate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexServiceClient) GetBannerList(ctx context.Context, in *GetBannerListRequest, opts ...grpc.CallOption) (*GetBannerListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBannerListReply)
	err := c.cc.Invoke(ctx, IndexService_GetBannerList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IndexServiceServer is the server API for IndexService service.
// All implementations must embed UnimplementedIndexServiceServer
// for forward compatibility.
//
// IndexService 首页相关。
// 对应原项目 app/api/route/index.php（Route::group('/v1/index', ...)）
//
//	Route::get('index',      [IndexController::class,  'index']);
//	Route::get('decorate',   [IndexController::class,  'decorate']);
//	Route::get('config',     [IndexController::class,  'config']);     <- 未实现
//	Route::get('bannerList', [BannerController::class, 'getList']);
//	Route::get('test',       [IndexController::class,  'test']);       <- 未实现，见下
//
// ⚠️ IndexController::$notNeedLogin = ['test','index','config','policy','decorate']
//
//	BannerController::$notNeedLogin = ['getList']
//	-> 本文件的 4 条**全部免登录**。
type IndexServiceServer interface {
	// 首页聚合数据（装修页 + 最新 20 篇文章）
	// 原: IndexLogic::getIndexData()
	//
	//	return ['page' => $decoratePage, 'article' => $article];
	GetIndex(context.Context, *GetIndexRequest) (*GetIndexReply, error)
	// 装修页详情
	// 原: IndexLogic::getDecorate($id)
	//
	//	DecoratePage::field(['type','name','data','meta'])->findOrEmpty($id)->toArray()
	GetDecorate(context.Context, *GetDecorateRequest) (*GetDecorateReply, error)
	// 轮播图列表
	// 原: GetListLogic::getList()（有 10 秒缓存，键 'banner:list'，与 PHP 共用）
	GetBannerList(context.Context, *GetBannerListRequest) (*GetBannerListReply, error)
	mustEmbedUnimplementedIndexServiceServer()
}

// UnimplementedIndexServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIndexServiceServer struct{}

func (UnimplementedIndexServiceServer) GetIndex(context.Context, *GetIndexRequest) (*GetIndexReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIndex not implemented")
}
func (UnimplementedIndexServiceServer) GetDecorate(context.Context, *GetDecorateRequest) (*GetDecorateReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDecorate not implemented")
}
func (UnimplementedIndexServiceServer) GetBannerList(context.Context, *GetBannerListRequest) (*GetBannerListReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBannerList not implemented")
}
func (UnimplementedIndexServiceServer) mustEmbedUnimplementedIndexServiceServer() {}
func (UnimplementedIndexServiceServer) testEmbeddedByValue()                      {}

// UnsafeIndexServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IndexServiceServer will
// result in compilation errors.
type UnsafeIndexServiceServer interface {
	mustEmbedUnimplementedIndexServiceServer()
}

func RegisterIndexServiceServer(s grpc.ServiceRegistrar, srv IndexServiceServer) {
	// If the following call panics, it indicates UnimplementedIndexServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IndexService_ServiceDesc, srv)
}

func _IndexService_GetIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServiceServer).GetIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IndexService_GetIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServiceServer).GetIndex(ctx, req.(*GetIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IndexService_GetDecorate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDecorateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServiceServer).GetDecorate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IndexService_GetDecorate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServiceServer).GetDecorate(ctx, req.(*GetDecorateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IndexService_GetBannerList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBannerListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServiceServer).GetBannerList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IndexService_GetBannerList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServiceServer).GetBannerList(ctx, req.(*GetBannerListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IndexService_ServiceDesc is the grpc.ServiceDesc for IndexService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IndexService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xtravel.v1.IndexService",
	HandlerType: (*IndexServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetIndex",
			Handler:    _IndexService_GetIndex_Handler,
		},
		{
			MethodName: "GetDecorate",
			Handler:    _IndexService_GetDecorate_Handler,
		},
		{
			MethodName: "GetBannerList",
			Handler:    _IndexService_GetBannerList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/xtravel/v1/index.proto",
}
