// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.35.1
// source: api/xtravel/v1/index.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationIndexServiceGetBannerList = "/xtravel.v1.IndexService/GetBannerList"
const OperationIndexServiceGetDecorate = "/xtravel.v1.IndexService/GetDecorate"
const OperationIndexServiceGetIndex = "/xtravel.v1.IndexService/GetIndex"

type IndexServiceHTTPServer interface {
	// GetBannerList 轮播图列表
	// 原: GetListLogic::getList()（有 10 秒缓存，键 'banner:list'，与 PHP 共用）
	GetBannerList(context.Context, *GetBannerListRequest) (*GetBannerListReply, error)
	// GetDecorate 装修页详情
	// 原: IndexLogic::getDecorate($id)
	//   DecoratePage::field(['type','name','data','meta'])->findOrEmpty($id)->toArray()
	GetDecorate(context.Context, *GetDecorateRequest) (*GetDecorateReply, error)
	// GetIndex 首页聚合数据（装修页 + 最新 20 篇文章）
	// 原: IndexLogic::getIndexData()
	//
	//	return ['page' => $decoratePage, 'article' => $article];
	GetIndex(context.Context, *GetIndexRequest) (*GetIndexReply, error)
}

func RegisterIndexServiceHTTPServer(s *http.Server, srv IndexServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/index/index", _IndexService_GetIndex0_HTTP_Handler(srv))
	r.GET("/v1/index/decorate", _IndexService_GetDecorate0_HTTP_Handler(srv))
	r.GET("/v1/index/bannerList", _IndexService_GetBannerList0_HTTP_Handler(srv))
}

func _IndexService_GetIndex0_HTTP_Handler(srv IndexServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetIndexRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIndexServiceGetIndex)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetIndex(ctx, req.(*GetIndexRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetIndexReply)
		return ctx.Result(200, reply)
	}
}

func _IndexService_GetDecorate0_HTTP_Handler(srv IndexServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetDecorateRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIndexServiceGetDecorate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetDecorate(ctx, req.(*GetDecorateRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetDecorateReply)
		return ctx.Result(200, reply)
	}
}

func _IndexService_GetBannerList0_HTTP_Handler(srv IndexServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetBannerListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIndexServiceGetBannerList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetBannerList(ctx, req.(*GetBannerListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetBannerListReply)
		return ctx.Result(200, reply)
	}
}

type IndexServiceHTTPClient interface {
	// GetBannerList 轮播图列表
	// 原: GetListLogic::getList()（有 10 秒缓存，键 'banner:list'，与 PHP 共用）
	GetBannerList(ctx context.Context, req *GetBannerListRequest, opts ...http.CallOption) (rsp *GetBannerListReply, err error)
	// GetDecorate 装修页详情
	// 原: IndexLogic::getDecorate($id)
	//   DecoratePage::field(['type','name','data','meta'])->findOrEmpty($id)->toArray()
	GetDecorate(ctx context.Context, req *GetDecorateRequest, opts ...http.CallOption) (rsp *GetDecorateReply, err error)
	// GetIndex 首页聚合数据（装修页 + 最新 20 篇文章）
	// 原: IndexLogic::getIndexData()
	//
	//	return ['page' => $decoratePage, 'article' => $article];
	GetIndex(ctx context.Context, req *GetIndexRequest, opts ...http.CallOption) (rsp *GetIndexReply, err error)
}

type IndexServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewIndexServiceHTTPClient(client *http.Client) IndexServiceHTTPClient {
	return &IndexServiceHTTPClientImpl{client}
}

// GetBannerList 轮播图列表
// 原: GetListLogic::getList()（有 10 秒缓存，键 'banner:list'，与 PHP 共用）
func (c *IndexServiceHTTPClientImpl) GetBannerList(ctx context.Context, in *GetBannerListRequest, opts ...http.CallOption) (*GetBannerListReply, error) {
	var out GetBannerListReply
	pattern := "/v1/index/bannerList"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationIndexServiceGetBannerList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetDecorate 装修页详情
// 原: IndexLogic::getDecorate($id)
//
//	DecoratePage::field(['type','name','data','meta'])->findOrEmpty($id)->toArray()
func (c *IndexServiceHTTPClientImpl) GetDecorate(ctx context.Context, in *GetDecorateRequest, opts ...http.CallOption) (*GetDecorateReply, error) {
	var out GetDecorateReply
	pattern := "/v1/index/decorate"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationIndexServiceGetDecorate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetIndex 首页聚合数据（装修页 + 最新 20 篇文章）
// 原: IndexLogic::getIndexData()
//
//	return ['page' => $decoratePage, 'article' => $article];
func (c *IndexServiceHTTPClientImpl) GetIndex(ctx context.Context, in *GetIndexRequest, opts ...http.CallOption) (*GetIndexReply, error) {
	var out GetIndexReply
	pattern := "/v1/index/index"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationIndexServiceGetIndex))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
