// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.35.1
// source: api/xtravel/v1/market.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationMarketServiceCheckExchange = "/xtravel.v1.MarketService/CheckExchange"
const OperationMarketServiceGetPayWay = "/xtravel.v1.MarketService/GetPayWay"
const OperationMarketServiceGetSaleCategories = "/xtravel.v1.MarketService/GetSaleCategories"
const OperationMarketServicePurchaseIndex = "/xtravel.v1.MarketService/PurchaseIndex"
const OperationMarketServicePurchaseInfo = "/xtravel.v1.MarketService/PurchaseInfo"
const OperationMarketServicePurchaseOn = "/xtravel.v1.MarketService/PurchaseOn"
const OperationMarketServicePurchaseOut = "/xtravel.v1.MarketService/PurchaseOut"
const OperationMarketServiceSaleIndex = "/xtravel.v1.MarketService/SaleIndex"
const OperationMarketServiceSaleInfo = "/xtravel.v1.MarketService/SaleInfo"
const OperationMarketServiceShowTotalAmount = "/xtravel.v1.MarketService/ShowTotalAmount"
const OperationMarketServiceStockLookAll = "/xtravel.v1.MarketService/StockLookAll"

type MarketServiceHTTPServer interface {
	// CheckExchange 兑换前置校验
	// 原: PurchaseController::checkExchange -> GoodsLogic::checkExchange
	//     （需要登录；会加 2 秒防重复点击锁并查一次兑换单数量）
	CheckExchange(context.Context, *CheckExchangeRequest) (*CheckExchangeReply, error)
	// GetPayWay 支付方式列表
	// 原: PurchaseController::payWay（硬编码，不查库；需要登录）
	GetPayWay(context.Context, *GetPayWayRequest) (*GetPayWayReply, error)
	// GetSaleCategories 秒转专区分类列表
	// 原: SaleController::categories —— **硬编码**，不查库；是 SaleController 里
	//     唯一免登录的方法（$notNeedLogin = ['categories']）
	GetSaleCategories(context.Context, *GetSaleCategoriesRequest) (*GetSaleCategoriesReply, error)
	// PurchaseIndex 兑换专区首页列表
	// 原: PurchaseController::index -> PurchaseFaceLists
	//     **免登录**（控制器 $notNeedLogin 放行了 index）
	//     挂白名单 no_collection_trade
	//     走交易时段判断；带 20 秒整包缓存
	//
	// 返回 RawData：列表行结构任意（bigint 主键 / decimal 字符串 / json 数组 /
	// "0 转 --" 后处理），用 proto 建模会丢精度又拧巴，见 common.proto 的说明。
	PurchaseIndex(context.Context, *PurchaseIndexRequest) (*RawData, error)
	// PurchaseInfo 藏品封面（档案基础信息）
	// 原: PurchaseController::purchaseInfo -> MarketListPurchaseLogic::getArchive
	//     **需要登录**；结果按 archive id 缓存 600 秒
	PurchaseInfo(context.Context, *PurchaseInfoRequest) (*PurchaseInfoReply, error)
	// PurchaseOn 兑换中列表（state=WANTED）
	// 原: PurchaseController::salesOn -> PurchaseStateLists(['state'=>'WANTED'])
	//     需要登录
	//
	// ⚠️ 与 purchase/out 的两处差异：
	//   1. 排序不同：unit_price DESC, grab_time ASC, create_time ASC, id DESC
	//   2. **分页之后**会过滤掉 available_amount <= 0 的行 ——
	//      所以返回行数可能少于 page_size，而 count() 不做这个过滤，
	//      **count 与 lists 天然对不上**（原实现行为，刻意保持）
	//
	// 原实现还挂了 stale-while-revalidate 缓存（逻辑过期 5s / 物理 15s / 重建锁 5s），
	// 本批**未接**，每次直查。功能正确，少了缓存。
	PurchaseOn(context.Context, *PurchaseOnRequest) (*RawData, error)
	// PurchaseOut 兑换售出列表（state=COMPLETE）
	// 原: PurchaseController::salesOut -> PurchaseStateLists(['state'=>'COMPLETE'])
	//     需要登录；结果按参数 md5 缓存 10 秒（简单 TTL，无锁）
	//
	// ⚠️ count 与 lists 可能对不上：lists 在 SQL 层过滤，但原实现对 WANTED 状态
	//    还有一次**分页之后**的过滤；COMPLETE 分支没有那次过滤。
	PurchaseOut(context.Context, *PurchaseOutRequest) (*RawData, error)
	// SaleIndex 秒转专区首页列表
	// 原: SaleController::index -> SaleFaceLists
	//     **需要登录**（不在 $notNeedLogin 里）
	//
	// ⚠️ 与 purchase 列表的两个差异（都是实测出来的）：
	//   1. 该接口没有默认排序 —— PurchaseFaceLists 的 switch 有 default 分支，
	//      SaleFaceLists 没有，所以**不带 sort 参数时 SQL 里根本没有 ORDER BY**
	//   2. 行后处理只做 images 的 json 解码，没有 "0 转 --" 那套
	SaleIndex(context.Context, *SaleIndexRequest) (*RawData, error)
	// SaleInfo 秒转藏品封面
	// 原: SaleController::saleInfo -> MarketListSalesLogic::findSales + SaleLogic::getArchive
	//     **需要登录**
	//
	// ⚠️ 与 PurchaseInfo 不是同一个函数，尽管缓存键看起来一样：
	//    本例走 SaleLogic::getArchive，用 TP 的 cache()（物理键 la:archive:{id}），
	//    **只有 5 个字段**（没有 collection_id / platform_id），TTL 3600s；
	//    PurchaseInfo 走 MarketListPurchaseLogic::getArchive，用 RedisLockService
	//    （物理键 archive:{id}），有 7 个字段，TTL 600s。
	//    两者物理键不同所以不会互相覆盖，但字段集不同 —— 不要"顺手统一"。
	SaleInfo(context.Context, *SaleInfoRequest) (*SaleInfoReply, error)
	// ShowTotalAmount 计算总额（含服务手续费）
	// 原: PurchaseOrdersController::showTotalAmount -> FeeAmountLogic::showTotalAmount
	//
	// ⚠️ totalAmount 是**字符串**，不是数字：原实现返回的是 bcsub 的结果，
	//    且参数不合法时是 '0'（没有小数位），合法时是 2 位小数。
	ShowTotalAmount(context.Context, *ShowTotalAmountRequest) (*ShowTotalAmountReply, error)
	// StockLookAll 库存汇总（可释放数量 + 是否有释放任务在处理中）
	// 原: PurchaseController::lookAll -> GoodsLogic::lookAll
	//     **需要登录**；结果缓存 10 秒
	//
	// ⚠️ state 字段迁移期恒为 1：它依赖的"释放任务进行中"标记由 PHP 用
	//    ThinkPHP 的 cache() 写入，键空间与 Go 侧隔离。详见 biz/stock.go。
	StockLookAll(context.Context, *StockLookAllRequest) (*StockLookAllReply, error)
}

func RegisterMarketServiceHTTPServer(s *http.Server, srv MarketServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/market/pay_way", _MarketService_GetPayWay0_HTTP_Handler(srv))
	r.GET("/v1/market/check/exchange", _MarketService_CheckExchange0_HTTP_Handler(srv))
	r.GET("/v1/market/purchase", _MarketService_PurchaseIndex0_HTTP_Handler(srv))
	r.GET("/v1/market/sales/categories", _MarketService_GetSaleCategories0_HTTP_Handler(srv))
	r.GET("/v1/market/sales", _MarketService_SaleIndex0_HTTP_Handler(srv))
	r.GET("/v1/market/stock/lookall", _MarketService_StockLookAll0_HTTP_Handler(srv))
	r.GET("/v1/market/purchase/info", _MarketService_PurchaseInfo0_HTTP_Handler(srv))
	r.GET("/v1/market/sales/info", _MarketService_SaleInfo0_HTTP_Handler(srv))
	r.GET("/v1/market/purchase/showTotalAmount", _MarketService_ShowTotalAmount0_HTTP_Handler(srv))
	r.GET("/v1/market/purchase/out", _MarketService_PurchaseOut0_HTTP_Handler(srv))
	r.GET("/v1/market/purchase/on", _MarketService_PurchaseOn0_HTTP_Handler(srv))
}

func _MarketService_GetPayWay0_HTTP_Handler(srv MarketServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetPayWayRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketServiceGetPayWay)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetPayWay(ctx, req.(*GetPayWayRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetPayWayReply)
		return ctx.Result(200, reply)
	}
}

func _MarketService_CheckExchange0_HTTP_Handler(srv MarketServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CheckExchangeRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketServiceCheckExchange)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CheckExchange(ctx, req.(*CheckExchangeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CheckExchangeReply)
		return ctx.Result(200, reply)
	}
}

func _MarketService_PurchaseIndex0_HTTP_Handler(srv MarketServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PurchaseIndexRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketServicePurchaseIndex)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PurchaseIndex(ctx, req.(*PurchaseIndexRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RawData)
		return ctx.Result(200, reply)
	}
}

func _MarketService_GetSaleCategories0_HTTP_Handler(srv MarketServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetSaleCategoriesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketServiceGetSaleCategories)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetSaleCategories(ctx, req.(*GetSaleCategoriesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetSaleCategoriesReply)
		return ctx.Result(200, reply)
	}
}

func _MarketService_SaleIndex0_HTTP_Handler(srv MarketServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SaleIndexRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketServiceSaleIndex)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SaleIndex(ctx, req.(*SaleIndexRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RawData)
		return ctx.Result(200, reply)
	}
}

func _MarketService_StockLookAll0_HTTP_Handler(srv MarketServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in StockLookAllRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketServiceStockLookAll)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.StockLookAll(ctx, req.(*StockLookAllRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*StockLookAllReply)
		return ctx.Result(200, reply)
	}
}

func _MarketService_PurchaseInfo0_HTTP_Handler(srv MarketServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PurchaseInfoRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketServicePurchaseInfo)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PurchaseInfo(ctx, req.(*PurchaseInfoRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PurchaseInfoReply)
		return ctx.Result(200, reply)
	}
}

func _MarketService_SaleInfo0_HTTP_Handler(srv MarketServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SaleInfoRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketServiceSaleInfo)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SaleInfo(ctx, req.(*SaleInfoRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SaleInfoReply)
		return ctx.Result(200, reply)
	}
}

func _MarketService_ShowTotalAmount0_HTTP_Handler(srv MarketServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ShowTotalAmountRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketServiceShowTotalAmount)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ShowTotalAmount(ctx, req.(*ShowTotalAmountRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ShowTotalAmountReply)
		return ctx.Result(200, reply)
	}
}

func _MarketService_PurchaseOut0_HTTP_Handler(srv MarketServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PurchaseOutRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketServicePurchaseOut)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PurchaseOut(ctx, req.(*PurchaseOutRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RawData)
		return ctx.Result(200, reply)
	}
}

func _MarketService_PurchaseOn0_HTTP_Handler(srv MarketServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PurchaseOnRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketServicePurchaseOn)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PurchaseOn(ctx, req.(*PurchaseOnRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RawData)
		return ctx.Result(200, reply)
	}
}

type MarketServiceHTTPClient interface {
	// CheckExchange 兑换前置校验
	// 原: PurchaseController::checkExchange -> GoodsLogic::checkExchange
	//     （需要登录；会加 2 秒防重复点击锁并查一次兑换单数量）
	CheckExchange(ctx context.Context, req *CheckExchangeRequest, opts ...http.CallOption) (rsp *CheckExchangeReply, err error)
	// GetPayWay 支付方式列表
	// 原: PurchaseController::payWay（硬编码，不查库；需要登录）
	GetPayWay(ctx context.Context, req *GetPayWayRequest, opts ...http.CallOption) (rsp *GetPayWayReply, err error)
	// GetSaleCategories 秒转专区分类列表
	// 原: SaleController::categories —— **硬编码**，不查库；是 SaleController 里
	//     唯一免登录的方法（$notNeedLogin = ['categories']）
	GetSaleCategories(ctx context.Context, req *GetSaleCategoriesRequest, opts ...http.CallOption) (rsp *GetSaleCategoriesReply, err error)
	// PurchaseIndex 兑换专区首页列表
	// 原: PurchaseController::index -> PurchaseFaceLists
	//     **免登录**（控制器 $notNeedLogin 放行了 index）
	//     挂白名单 no_collection_trade
	//     走交易时段判断；带 20 秒整包缓存
	//
	// 返回 RawData：列表行结构任意（bigint 主键 / decimal 字符串 / json 数组 /
	// "0 转 --" 后处理），用 proto 建模会丢精度又拧巴，见 common.proto 的说明。
	PurchaseIndex(ctx context.Context, req *PurchaseIndexRequest, opts ...http.CallOption) (rsp *RawData, err error)
	// PurchaseInfo 藏品封面（档案基础信息）
	// 原: PurchaseController::purchaseInfo -> MarketListPurchaseLogic::getArchive
	//     **需要登录**；结果按 archive id 缓存 600 秒
	PurchaseInfo(ctx context.Context, req *PurchaseInfoRequest, opts ...http.CallOption) (rsp *PurchaseInfoReply, err error)
	// PurchaseOn 兑换中列表（state=WANTED）
	// 原: PurchaseController::salesOn -> PurchaseStateLists(['state'=>'WANTED'])
	//     需要登录
	//
	// ⚠️ 与 purchase/out 的两处差异：
	//   1. 排序不同：unit_price DESC, grab_time ASC, create_time ASC, id DESC
	//   2. **分页之后**会过滤掉 available_amount <= 0 的行 ——
	//      所以返回行数可能少于 page_size，而 count() 不做这个过滤，
	//      **count 与 lists 天然对不上**（原实现行为，刻意保持）
	//
	// 原实现还挂了 stale-while-revalidate 缓存（逻辑过期 5s / 物理 15s / 重建锁 5s），
	// 本批**未接**，每次直查。功能正确，少了缓存。
	PurchaseOn(ctx context.Context, req *PurchaseOnRequest, opts ...http.CallOption) (rsp *RawData, err error)
	// PurchaseOut 兑换售出列表（state=COMPLETE）
	// 原: PurchaseController::salesOut -> PurchaseStateLists(['state'=>'COMPLETE'])
	//     需要登录；结果按参数 md5 缓存 10 秒（简单 TTL，无锁）
	//
	// ⚠️ count 与 lists 可能对不上：lists 在 SQL 层过滤，但原实现对 WANTED 状态
	//    还有一次**分页之后**的过滤；COMPLETE 分支没有那次过滤。
	PurchaseOut(ctx context.Context, req *PurchaseOutRequest, opts ...http.CallOption) (rsp *RawData, err error)
	// SaleIndex 秒转专区首页列表
	// 原: SaleController::index -> SaleFaceLists
	//     **需要登录**（不在 $notNeedLogin 里）
	//
	// ⚠️ 与 purchase 列表的两个差异（都是实测出来的）：
	//   1. 该接口没有默认排序 —— PurchaseFaceLists 的 switch 有 default 分支，
	//      SaleFaceLists 没有，所以**不带 sort 参数时 SQL 里根本没有 ORDER BY**
	//   2. 行后处理只做 images 的 json 解码，没有 "0 转 --" 那套
	SaleIndex(ctx context.Context, req *SaleIndexRequest, opts ...http.CallOption) (rsp *RawData, err error)
	// SaleInfo 秒转藏品封面
	// 原: SaleController::saleInfo -> MarketListSalesLogic::findSales + SaleLogic::getArchive
	//     **需要登录**
	//
	// ⚠️ 与 PurchaseInfo 不是同一个函数，尽管缓存键看起来一样：
	//    本例走 SaleLogic::getArchive，用 TP 的 cache()（物理键 la:archive:{id}），
	//    **只有 5 个字段**（没有 collection_id / platform_id），TTL 3600s；
	//    PurchaseInfo 走 MarketListPurchaseLogic::getArchive，用 RedisLockService
	//    （物理键 archive:{id}），有 7 个字段，TTL 600s。
	//    两者物理键不同所以不会互相覆盖，但字段集不同 —— 不要"顺手统一"。
	SaleInfo(ctx context.Context, req *SaleInfoRequest, opts ...http.CallOption) (rsp *SaleInfoReply, err error)
	// ShowTotalAmount 计算总额（含服务手续费）
	// 原: PurchaseOrdersController::showTotalAmount -> FeeAmountLogic::showTotalAmount
	//
	// ⚠️ totalAmount 是**字符串**，不是数字：原实现返回的是 bcsub 的结果，
	//    且参数不合法时是 '0'（没有小数位），合法时是 2 位小数。
	ShowTotalAmount(ctx context.Context, req *ShowTotalAmountRequest, opts ...http.CallOption) (rsp *ShowTotalAmountReply, err error)
	// StockLookAll 库存汇总（可释放数量 + 是否有释放任务在处理中）
	// 原: PurchaseController::lookAll -> GoodsLogic::lookAll
	//     **需要登录**；结果缓存 10 秒
	//
	// ⚠️ state 字段迁移期恒为 1：它依赖的"释放任务进行中"标记由 PHP 用
	//    ThinkPHP 的 cache() 写入，键空间与 Go 侧隔离。详见 biz/stock.go。
	StockLookAll(ctx context.Context, req *StockLookAllRequest, opts ...http.CallOption) (rsp *StockLookAllReply, err error)
}

type MarketServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewMarketServiceHTTPClient(client *http.Client) MarketServiceHTTPClient {
	return &MarketServiceHTTPClientImpl{client}
}

// CheckExchange 兑换前置校验
// 原: PurchaseController::checkExchange -> GoodsLogic::checkExchange
//
//	（需要登录；会加 2 秒防重复点击锁并查一次兑换单数量）
func (c *MarketServiceHTTPClientImpl) CheckExchange(ctx context.Context, in *CheckExchangeRequest, opts ...http.CallOption) (*CheckExchangeReply, error) {
	var out CheckExchangeReply
	pattern := "/v1/market/check/exchange"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMarketServiceCheckExchange))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetPayWay 支付方式列表
// 原: PurchaseController::payWay（硬编码，不查库；需要登录）
func (c *MarketServiceHTTPClientImpl) GetPayWay(ctx context.Context, in *GetPayWayRequest, opts ...http.CallOption) (*GetPayWayReply, error) {
	var out GetPayWayReply
	pattern := "/v1/market/pay_way"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMarketServiceGetPayWay))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetSaleCategories 秒转专区分类列表
// 原: SaleController::categories —— **硬编码**，不查库；是 SaleController 里
//
//	唯一免登录的方法（$notNeedLogin = ['categories']）
func (c *MarketServiceHTTPClientImpl) GetSaleCategories(ctx context.Context, in *GetSaleCategoriesRequest, opts ...http.CallOption) (*GetSaleCategoriesReply, error) {
	var out GetSaleCategoriesReply
	pattern := "/v1/market/sales/categories"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMarketServiceGetSaleCategories))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// PurchaseIndex 兑换专区首页列表
// 原: PurchaseController::index -> PurchaseFaceLists
//
//	**免登录**（控制器 $notNeedLogin 放行了 index）
//	挂白名单 no_collection_trade
//	走交易时段判断；带 20 秒整包缓存
//
// 返回 RawData：列表行结构任意（bigint 主键 / decimal 字符串 / json 数组 /
// "0 转 --" 后处理），用 proto 建模会丢精度又拧巴，见 common.proto 的说明。
func (c *MarketServiceHTTPClientImpl) PurchaseIndex(ctx context.Context, in *PurchaseIndexRequest, opts ...http.CallOption) (*RawData, error) {
	var out RawData
	pattern := "/v1/market/purchase"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMarketServicePurchaseIndex))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// PurchaseInfo 藏品封面（档案基础信息）
// 原: PurchaseController::purchaseInfo -> MarketListPurchaseLogic::getArchive
//
//	**需要登录**；结果按 archive id 缓存 600 秒
func (c *MarketServiceHTTPClientImpl) PurchaseInfo(ctx context.Context, in *PurchaseInfoRequest, opts ...http.CallOption) (*PurchaseInfoReply, error) {
	var out PurchaseInfoReply
	pattern := "/v1/market/purchase/info"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMarketServicePurchaseInfo))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// PurchaseOn 兑换中列表（state=WANTED）
// 原: PurchaseController::salesOn -> PurchaseStateLists(['state'=>'WANTED'])
//
//	需要登录
//
// ⚠️ 与 purchase/out 的两处差异：
//  1. 排序不同：unit_price DESC, grab_time ASC, create_time ASC, id DESC
//  2. **分页之后**会过滤掉 available_amount <= 0 的行 ——
//     所以返回行数可能少于 page_size，而 count() 不做这个过滤，
//     **count 与 lists 天然对不上**（原实现行为，刻意保持）
//
// 原实现还挂了 stale-while-revalidate 缓存（逻辑过期 5s / 物理 15s / 重建锁 5s），
// 本批**未接**，每次直查。功能正确，少了缓存。
func (c *MarketServiceHTTPClientImpl) PurchaseOn(ctx context.Context, in *PurchaseOnRequest, opts ...http.CallOption) (*RawData, error) {
	var out RawData
	pattern := "/v1/market/purchase/on"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMarketServicePurchaseOn))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// PurchaseOut 兑换售出列表（state=COMPLETE）
// 原: PurchaseController::salesOut -> PurchaseStateLists(['state'=>'COMPLETE'])
//
//	需要登录；结果按参数 md5 缓存 10 秒（简单 TTL，无锁）
//
// ⚠️ count 与 lists 可能对不上：lists 在 SQL 层过滤，但原实现对 WANTED 状态
//
//	还有一次**分页之后**的过滤；COMPLETE 分支没有那次过滤。
func (c *MarketServiceHTTPClientImpl) PurchaseOut(ctx context.Context, in *PurchaseOutRequest, opts ...http.CallOption) (*RawData, error) {
	var out RawData
	pattern := "/v1/market/purchase/out"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMarketServicePurchaseOut))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SaleIndex 秒转专区首页列表
// 原: SaleController::index -> SaleFaceLists
//
//	**需要登录**（不在 $notNeedLogin 里）
//
// ⚠️ 与 purchase 列表的两个差异（都是实测出来的）：
//  1. 该接口没有默认排序 —— PurchaseFaceLists 的 switch 有 default 分支，
//     SaleFaceLists 没有，所以**不带 sort 参数时 SQL 里根本没有 ORDER BY**
//  2. 行后处理只做 images 的 json 解码，没有 "0 转 --" 那套
func (c *MarketServiceHTTPClientImpl) SaleIndex(ctx context.Context, in *SaleIndexRequest, opts ...http.CallOption) (*RawData, error) {
	var out RawData
	pattern := "/v1/market/sales"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMarketServiceSaleIndex))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SaleInfo 秒转藏品封面
// 原: SaleController::saleInfo -> MarketListSalesLogic::findSales + SaleLogic::getArchive
//
//	**需要登录**
//
// ⚠️ 与 PurchaseInfo 不是同一个函数，尽管缓存键看起来一样：
//
//	本例走 SaleLogic::getArchive，用 TP 的 cache()（物理键 la:archive:{id}），
//	**只有 5 个字段**（没有 collection_id / platform_id），TTL 3600s；
//	PurchaseInfo 走 MarketListPurchaseLogic::getArchive，用 RedisLockService
//	（物理键 archive:{id}），有 7 个字段，TTL 600s。
//	两者物理键不同所以不会互相覆盖，但字段集不同 —— 不要"顺手统一"。
func (c *MarketServiceHTTPClientImpl) SaleInfo(ctx context.Context, in *SaleInfoRequest, opts ...http.CallOption) (*SaleInfoReply, error) {
	var out SaleInfoReply
	pattern := "/v1/market/sales/info"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMarketServiceSaleInfo))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ShowTotalAmount 计算总额（含服务手续费）
// 原: PurchaseOrdersController::showTotalAmount -> FeeAmountLogic::showTotalAmount
//
// ⚠️ totalAmount 是**字符串**，不是数字：原实现返回的是 bcsub 的结果，
//
//	且参数不合法时是 '0'（没有小数位），合法时是 2 位小数。
func (c *MarketServiceHTTPClientImpl) ShowTotalAmount(ctx context.Context, in *ShowTotalAmountRequest, opts ...http.CallOption) (*ShowTotalAmountReply, error) {
	var out ShowTotalAmountReply
	pattern := "/v1/market/purchase/showTotalAmount"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMarketServiceShowTotalAmount))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// StockLookAll 库存汇总（可释放数量 + 是否有释放任务在处理中）
// 原: PurchaseController::lookAll -> GoodsLogic::lookAll
//
//	**需要登录**；结果缓存 10 秒
//
// ⚠️ state 字段迁移期恒为 1：它依赖的"释放任务进行中"标记由 PHP 用
//
//	ThinkPHP 的 cache() 写入，键空间与 Go 侧隔离。详见 biz/stock.go。
func (c *MarketServiceHTTPClientImpl) StockLookAll(ctx context.Context, in *StockLookAllRequest, opts ...http.CallOption) (*StockLookAllReply, error) {
	var out StockLookAllReply
	pattern := "/v1/market/stock/lookall"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMarketServiceStockLookAll))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
