// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.35.1
// source: api/xtravel/v1/market.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationMarketServiceCheckExchange = "/xtravel.v1.MarketService/CheckExchange"
const OperationMarketServiceGetPayWay = "/xtravel.v1.MarketService/GetPayWay"

type MarketServiceHTTPServer interface {
	// CheckExchange 兑换前置校验
	// 原: PurchaseController::checkExchange -> GoodsLogic::checkExchange
	//     （需要登录；会加 2 秒防重复点击锁并查一次兑换单数量）
	CheckExchange(context.Context, *CheckExchangeRequest) (*CheckExchangeReply, error)
	// GetPayWay 支付方式列表
	// 原: PurchaseController::payWay（硬编码，不查库；需要登录）
	GetPayWay(context.Context, *GetPayWayRequest) (*GetPayWayReply, error)
}

func RegisterMarketServiceHTTPServer(s *http.Server, srv MarketServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/market/pay_way", _MarketService_GetPayWay0_HTTP_Handler(srv))
	r.GET("/v1/market/check/exchange", _MarketService_CheckExchange0_HTTP_Handler(srv))
}

func _MarketService_GetPayWay0_HTTP_Handler(srv MarketServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetPayWayRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketServiceGetPayWay)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetPayWay(ctx, req.(*GetPayWayRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetPayWayReply)
		return ctx.Result(200, reply)
	}
}

func _MarketService_CheckExchange0_HTTP_Handler(srv MarketServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CheckExchangeRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketServiceCheckExchange)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CheckExchange(ctx, req.(*CheckExchangeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CheckExchangeReply)
		return ctx.Result(200, reply)
	}
}

type MarketServiceHTTPClient interface {
	// CheckExchange 兑换前置校验
	// 原: PurchaseController::checkExchange -> GoodsLogic::checkExchange
	//     （需要登录；会加 2 秒防重复点击锁并查一次兑换单数量）
	CheckExchange(ctx context.Context, req *CheckExchangeRequest, opts ...http.CallOption) (rsp *CheckExchangeReply, err error)
	// GetPayWay 支付方式列表
	// 原: PurchaseController::payWay（硬编码，不查库；需要登录）
	GetPayWay(ctx context.Context, req *GetPayWayRequest, opts ...http.CallOption) (rsp *GetPayWayReply, err error)
}

type MarketServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewMarketServiceHTTPClient(client *http.Client) MarketServiceHTTPClient {
	return &MarketServiceHTTPClientImpl{client}
}

// CheckExchange 兑换前置校验
// 原: PurchaseController::checkExchange -> GoodsLogic::checkExchange
//
//	（需要登录；会加 2 秒防重复点击锁并查一次兑换单数量）
func (c *MarketServiceHTTPClientImpl) CheckExchange(ctx context.Context, in *CheckExchangeRequest, opts ...http.CallOption) (*CheckExchangeReply, error) {
	var out CheckExchangeReply
	pattern := "/v1/market/check/exchange"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMarketServiceCheckExchange))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetPayWay 支付方式列表
// 原: PurchaseController::payWay（硬编码，不查库；需要登录）
func (c *MarketServiceHTTPClientImpl) GetPayWay(ctx context.Context, in *GetPayWayRequest, opts ...http.CallOption) (*GetPayWayReply, error) {
	var out GetPayWayReply
	pattern := "/v1/market/pay_way"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMarketServiceGetPayWay))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
