// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: api/xtravel/v1/market.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MarketService_GetPayWay_FullMethodName     = "/xtravel.v1.MarketService/GetPayWay"
	MarketService_CheckExchange_FullMethodName = "/xtravel.v1.MarketService/CheckExchange"
)

// MarketServiceClient is the client API for MarketService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MarketService 市场交易域。
// 对应原项目 app/api/route/market.php（44 条路由）与 app/api/controller/v1/market/*。
//
// ⚠️ 这是项目核心业务域，Stage 3 分批迁。本文件当前只包含第一批：
// 两个不涉及资金、不改数据的只读接口。写入类接口（下单/支付/兑换）
// 必须单独评估，不能顺手一起做。
type MarketServiceClient interface {
	// 支付方式列表
	// 原: PurchaseController::payWay（硬编码，不查库；需要登录）
	GetPayWay(ctx context.Context, in *GetPayWayRequest, opts ...grpc.CallOption) (*GetPayWayReply, error)
	// 兑换前置校验
	// 原: PurchaseController::checkExchange -> GoodsLogic::checkExchange
	//
	//	（需要登录；会加 2 秒防重复点击锁并查一次兑换单数量）
	CheckExchange(ctx context.Context, in *CheckExchangeRequest, opts ...grpc.CallOption) (*CheckExchangeReply, error)
}

type marketServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMarketServiceClient(cc grpc.ClientConnInterface) MarketServiceClient {
	return &marketServiceClient{cc}
}

func (c *marketServiceClient) GetPayWay(ctx context.Context, in *GetPayWayRequest, opts ...grpc.CallOption) (*GetPayWayReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPayWayReply)
	err := c.cc.Invoke(ctx, MarketService_GetPayWay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketServiceClient) CheckExchange(ctx context.Context, in *CheckExchangeRequest, opts ...grpc.CallOption) (*CheckExchangeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckExchangeReply)
	err := c.cc.Invoke(ctx, MarketService_CheckExchange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarketServiceServer is the server API for MarketService service.
// All implementations must embed UnimplementedMarketServiceServer
// for forward compatibility.
//
// MarketService 市场交易域。
// 对应原项目 app/api/route/market.php（44 条路由）与 app/api/controller/v1/market/*。
//
// ⚠️ 这是项目核心业务域，Stage 3 分批迁。本文件当前只包含第一批：
// 两个不涉及资金、不改数据的只读接口。写入类接口（下单/支付/兑换）
// 必须单独评估，不能顺手一起做。
type MarketServiceServer interface {
	// 支付方式列表
	// 原: PurchaseController::payWay（硬编码，不查库；需要登录）
	GetPayWay(context.Context, *GetPayWayRequest) (*GetPayWayReply, error)
	// 兑换前置校验
	// 原: PurchaseController::checkExchange -> GoodsLogic::checkExchange
	//
	//	（需要登录；会加 2 秒防重复点击锁并查一次兑换单数量）
	CheckExchange(context.Context, *CheckExchangeRequest) (*CheckExchangeReply, error)
	mustEmbedUnimplementedMarketServiceServer()
}

// UnimplementedMarketServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMarketServiceServer struct{}

func (UnimplementedMarketServiceServer) GetPayWay(context.Context, *GetPayWayRequest) (*GetPayWayReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPayWay not implemented")
}
func (UnimplementedMarketServiceServer) CheckExchange(context.Context, *CheckExchangeRequest) (*CheckExchangeReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckExchange not implemented")
}
func (UnimplementedMarketServiceServer) mustEmbedUnimplementedMarketServiceServer() {}
func (UnimplementedMarketServiceServer) testEmbeddedByValue()                       {}

// UnsafeMarketServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarketServiceServer will
// result in compilation errors.
type UnsafeMarketServiceServer interface {
	mustEmbedUnimplementedMarketServiceServer()
}

func RegisterMarketServiceServer(s grpc.ServiceRegistrar, srv MarketServiceServer) {
	// If the following call panics, it indicates UnimplementedMarketServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MarketService_ServiceDesc, srv)
}

func _MarketService_GetPayWay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPayWayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).GetPayWay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketService_GetPayWay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).GetPayWay(ctx, req.(*GetPayWayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_CheckExchange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckExchangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).CheckExchange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketService_CheckExchange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).CheckExchange(ctx, req.(*CheckExchangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MarketService_ServiceDesc is the grpc.ServiceDesc for MarketService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MarketService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xtravel.v1.MarketService",
	HandlerType: (*MarketServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPayWay",
			Handler:    _MarketService_GetPayWay_Handler,
		},
		{
			MethodName: "CheckExchange",
			Handler:    _MarketService_CheckExchange_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/xtravel/v1/market.proto",
}
