// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/xtravel/v1/market.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShowTotalAmountRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 原实现用 $this->request->param()（GET/POST 都收），路由是 GET
	AppId         string `protobuf:"bytes,1,opt,name=app_id,proto3" json:"app_id,omitempty"`
	Amount        string `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	UnitPrice     string `protobuf:"bytes,3,opt,name=unit_price,proto3" json:"unit_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowTotalAmountRequest) Reset() {
	*x = ShowTotalAmountRequest{}
	mi := &file_api_xtravel_v1_market_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowTotalAmountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowTotalAmountRequest) ProtoMessage() {}

func (x *ShowTotalAmountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_xtravel_v1_market_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowTotalAmountRequest.ProtoReflect.Descriptor instead.
func (*ShowTotalAmountRequest) Descriptor() ([]byte, []int) {
	return file_api_xtravel_v1_market_proto_rawDescGZIP(), []int{0}
}

func (x *ShowTotalAmountRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *ShowTotalAmountRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *ShowTotalAmountRequest) GetUnitPrice() string {
	if x != nil {
		return x.UnitPrice
	}
	return ""
}

type ShowTotalAmountReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 原实现是 $this->data(['totalAmount' => $totalAmount]) —— key 是 camelCase
	TotalAmount   string `protobuf:"bytes,1,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowTotalAmountReply) Reset() {
	*x = ShowTotalAmountReply{}
	mi := &file_api_xtravel_v1_market_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowTotalAmountReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowTotalAmountReply) ProtoMessage() {}

func (x *ShowTotalAmountReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_xtravel_v1_market_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowTotalAmountReply.ProtoReflect.Descriptor instead.
func (*ShowTotalAmountReply) Descriptor() ([]byte, []int) {
	return file_api_xtravel_v1_market_proto_rawDescGZIP(), []int{1}
}

func (x *ShowTotalAmountReply) GetTotalAmount() string {
	if x != nil {
		return x.TotalAmount
	}
	return ""
}

type SaleInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaleInfoRequest) Reset() {
	*x = SaleInfoRequest{}
	mi := &file_api_xtravel_v1_market_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaleInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaleInfoRequest) ProtoMessage() {}

func (x *SaleInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_xtravel_v1_market_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaleInfoRequest.ProtoReflect.Descriptor instead.
func (*SaleInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_xtravel_v1_market_proto_rawDescGZIP(), []int{2}
}

func (x *SaleInfoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SaleInfoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Images        *structpb.Value        `protobuf:"bytes,3,opt,name=images,proto3" json:"images,omitempty"`
	Issuer        string                 `protobuf:"bytes,4,opt,name=issuer,proto3" json:"issuer,omitempty"`
	PlatformName  string                 `protobuf:"bytes,5,opt,name=platform_name,proto3" json:"platform_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaleInfoReply) Reset() {
	*x = SaleInfoReply{}
	mi := &file_api_xtravel_v1_market_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaleInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaleInfoReply) ProtoMessage() {}

func (x *SaleInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_xtravel_v1_market_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaleInfoReply.ProtoReflect.Descriptor instead.
func (*SaleInfoReply) Descriptor() ([]byte, []int) {
	return file_api_xtravel_v1_market_proto_rawDescGZIP(), []int{3}
}

func (x *SaleInfoReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SaleInfoReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SaleInfoReply) GetImages() *structpb.Value {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *SaleInfoReply) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *SaleInfoReply) GetPlatformName() string {
	if x != nil {
		return x.PlatformName
	}
	return ""
}

type PurchaseInfoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 查询参数 id（原 validate 规则是 require，缺失会返回"档案ID不能为空"）
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchaseInfoRequest) Reset() {
	*x = PurchaseInfoRequest{}
	mi := &file_api_xtravel_v1_market_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseInfoRequest) ProtoMessage() {}

func (x *PurchaseInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_xtravel_v1_market_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseInfoRequest.ProtoReflect.Descriptor instead.
func (*PurchaseInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_xtravel_v1_market_proto_rawDescGZIP(), []int{4}
}

func (x *PurchaseInfoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PurchaseInfoReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// ⚠️ 这一列是 varchar，PHP 输出的是**字符串** "116" 而不是数字
	CollectionId string `protobuf:"bytes,2,opt,name=collection_id,proto3" json:"collection_id,omitempty"`
	Name         string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// images 在 DB 里是 json 字符串，PHP 会解码；解码失败时是 null，
	// 所以用 Value 承载（普通 repeated string 在未设置时会输出 []，与 null 不同）
	Images        *structpb.Value `protobuf:"bytes,4,opt,name=images,proto3" json:"images,omitempty"`
	Issuer        string          `protobuf:"bytes,5,opt,name=issuer,proto3" json:"issuer,omitempty"`
	PlatformName  string          `protobuf:"bytes,6,opt,name=platform_name,proto3" json:"platform_name,omitempty"`
	PlatformId    int64           `protobuf:"varint,7,opt,name=platform_id,proto3" json:"platform_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchaseInfoReply) Reset() {
	*x = PurchaseInfoReply{}
	mi := &file_api_xtravel_v1_market_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseInfoReply) ProtoMessage() {}

func (x *PurchaseInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_xtravel_v1_market_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseInfoReply.ProtoReflect.Descriptor instead.
func (*PurchaseInfoReply) Descriptor() ([]byte, []int) {
	return file_api_xtravel_v1_market_proto_rawDescGZIP(), []int{5}
}

func (x *PurchaseInfoReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PurchaseInfoReply) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

func (x *PurchaseInfoReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PurchaseInfoReply) GetImages() *structpb.Value {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *PurchaseInfoReply) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *PurchaseInfoReply) GetPlatformName() string {
	if x != nil {
		return x.PlatformName
	}
	return ""
}

func (x *PurchaseInfoReply) GetPlatformId() int64 {
	if x != nil {
		return x.PlatformId
	}
	return 0
}

type StockLookAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockLookAllRequest) Reset() {
	*x = StockLookAllRequest{}
	mi := &file_api_xtravel_v1_market_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockLookAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockLookAllRequest) ProtoMessage() {}

func (x *StockLookAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_xtravel_v1_market_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockLookAllRequest.ProtoReflect.Descriptor instead.
func (*StockLookAllRequest) Descriptor() ([]byte, []int) {
	return file_api_xtravel_v1_market_proto_rawDescGZIP(), []int{6}
}

type StockLookAllReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 1 正常；0 表示有释放任务正在处理中（迁移期恒为 1，见上面的说明）
	State         int32 `protobuf:"varint,1,opt,name=state,proto3" json:"state,omitempty"`
	Num           int64 `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockLookAllReply) Reset() {
	*x = StockLookAllReply{}
	mi := &file_api_xtravel_v1_market_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockLookAllReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockLookAllReply) ProtoMessage() {}

func (x *StockLookAllReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_xtravel_v1_market_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockLookAllReply.ProtoReflect.Descriptor instead.
func (*StockLookAllReply) Descriptor() ([]byte, []int) {
	return file_api_xtravel_v1_market_proto_rawDescGZIP(), []int{7}
}

func (x *StockLookAllReply) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *StockLookAllReply) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

type PurchaseIndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchaseIndexRequest) Reset() {
	*x = PurchaseIndexRequest{}
	mi := &file_api_xtravel_v1_market_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseIndexRequest) ProtoMessage() {}

func (x *PurchaseIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_xtravel_v1_market_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseIndexRequest.ProtoReflect.Descriptor instead.
func (*PurchaseIndexRequest) Descriptor() ([]byte, []int) {
	return file_api_xtravel_v1_market_proto_rawDescGZIP(), []int{8}
}

type GetSaleCategoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSaleCategoriesRequest) Reset() {
	*x = GetSaleCategoriesRequest{}
	mi := &file_api_xtravel_v1_market_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSaleCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSaleCategoriesRequest) ProtoMessage() {}

func (x *GetSaleCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_xtravel_v1_market_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSaleCategoriesRequest.ProtoReflect.Descriptor instead.
func (*GetSaleCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_api_xtravel_v1_market_proto_rawDescGZIP(), []int{9}
}

type GetSaleCategoriesReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 原接口 data 是顶层数组：[{"title":"全部","key":"all"}]
	Items         []*SaleCategory `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSaleCategoriesReply) Reset() {
	*x = GetSaleCategoriesReply{}
	mi := &file_api_xtravel_v1_market_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSaleCategoriesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSaleCategoriesReply) ProtoMessage() {}

func (x *GetSaleCategoriesReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_xtravel_v1_market_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSaleCategoriesReply.ProtoReflect.Descriptor instead.
func (*GetSaleCategoriesReply) Descriptor() ([]byte, []int) {
	return file_api_xtravel_v1_market_proto_rawDescGZIP(), []int{10}
}

func (x *GetSaleCategoriesReply) GetItems() []*SaleCategory {
	if x != nil {
		return x.Items
	}
	return nil
}

type SaleCategory struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Title string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	// key 是 PHP 数组里的字面键名，输出就是 "key"
	Key           string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaleCategory) Reset() {
	*x = SaleCategory{}
	mi := &file_api_xtravel_v1_market_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaleCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaleCategory) ProtoMessage() {}

func (x *SaleCategory) ProtoReflect() protoreflect.Message {
	mi := &file_api_xtravel_v1_market_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaleCategory.ProtoReflect.Descriptor instead.
func (*SaleCategory) Descriptor() ([]byte, []int) {
	return file_api_xtravel_v1_market_proto_rawDescGZIP(), []int{11}
}

func (x *SaleCategory) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SaleCategory) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type SaleIndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaleIndexRequest) Reset() {
	*x = SaleIndexRequest{}
	mi := &file_api_xtravel_v1_market_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaleIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaleIndexRequest) ProtoMessage() {}

func (x *SaleIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_xtravel_v1_market_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaleIndexRequest.ProtoReflect.Descriptor instead.
func (*SaleIndexRequest) Descriptor() ([]byte, []int) {
	return file_api_xtravel_v1_market_proto_rawDescGZIP(), []int{12}
}

type GetPayWayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPayWayRequest) Reset() {
	*x = GetPayWayRequest{}
	mi := &file_api_xtravel_v1_market_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPayWayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPayWayRequest) ProtoMessage() {}

func (x *GetPayWayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_xtravel_v1_market_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPayWayRequest.ProtoReflect.Descriptor instead.
func (*GetPayWayRequest) Descriptor() ([]byte, []int) {
	return file_api_xtravel_v1_market_proto_rawDescGZIP(), []int{13}
}

type GetPayWayReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ⚠️ 原接口的 data 是**顶层数组**而不是对象：
	//
	//	{"code":1,"show":0,"msg":"","data":[{"pay_way":1,...}]}
	//	Kratos 的 reply 是 message，默认会被包成 {"data":{"items":[...]}}。
	//	所以这里靠 api/xtravel/v1/envelope.go 里的 Envelope() 把 items 摊出去。
	Items         []*PayWay `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPayWayReply) Reset() {
	*x = GetPayWayReply{}
	mi := &file_api_xtravel_v1_market_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPayWayReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPayWayReply) ProtoMessage() {}

func (x *GetPayWayReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_xtravel_v1_market_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPayWayReply.ProtoReflect.Descriptor instead.
func (*GetPayWayReply) Descriptor() ([]byte, []int) {
	return file_api_xtravel_v1_market_proto_rawDescGZIP(), []int{14}
}

func (x *GetPayWayReply) GetItems() []*PayWay {
	if x != nil {
		return x.Items
	}
	return nil
}

type PayWay struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 原 PHP 是硬编码数组 ['pay_way' => 1, 'pay_name' => '茶交所']，
	// json_encode 出来就是下划线键名。必须显式指定 json_name，
	// 否则 protojson 会输出 payWay / payName，前端取不到字段。
	PayWay        int32  `protobuf:"varint,1,opt,name=pay_way,proto3" json:"pay_way,omitempty"`
	PayName       string `protobuf:"bytes,2,opt,name=pay_name,proto3" json:"pay_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayWay) Reset() {
	*x = PayWay{}
	mi := &file_api_xtravel_v1_market_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayWay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayWay) ProtoMessage() {}

func (x *PayWay) ProtoReflect() protoreflect.Message {
	mi := &file_api_xtravel_v1_market_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayWay.ProtoReflect.Descriptor instead.
func (*PayWay) Descriptor() ([]byte, []int) {
	return file_api_xtravel_v1_market_proto_rawDescGZIP(), []int{15}
}

func (x *PayWay) GetPayWay() int32 {
	if x != nil {
		return x.PayWay
	}
	return 0
}

func (x *PayWay) GetPayName() string {
	if x != nil {
		return x.PayName
	}
	return ""
}

type CheckExchangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckExchangeRequest) Reset() {
	*x = CheckExchangeRequest{}
	mi := &file_api_xtravel_v1_market_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckExchangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckExchangeRequest) ProtoMessage() {}

func (x *CheckExchangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_xtravel_v1_market_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckExchangeRequest.ProtoReflect.Descriptor instead.
func (*CheckExchangeRequest) Descriptor() ([]byte, []int) {
	return file_api_xtravel_v1_market_proto_rawDescGZIP(), []int{16}
}

// 成功时原接口返回的是**空数组** []（`return $this->data([])`），
// 不是空对象 {}。同样由 Envelope() 处理。
type CheckExchangeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckExchangeReply) Reset() {
	*x = CheckExchangeReply{}
	mi := &file_api_xtravel_v1_market_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckExchangeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckExchangeReply) ProtoMessage() {}

func (x *CheckExchangeReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_xtravel_v1_market_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckExchangeReply.ProtoReflect.Descriptor instead.
func (*CheckExchangeReply) Descriptor() ([]byte, []int) {
	return file_api_xtravel_v1_market_proto_rawDescGZIP(), []int{17}
}

var File_api_xtravel_v1_market_proto protoreflect.FileDescriptor

const file_api_xtravel_v1_market_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/xtravel/v1/market.proto\x12\n" +
	"xtravel.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1bapi/xtravel/v1/common.proto\"h\n" +
	"\x16ShowTotalAmountRequest\x12\x16\n" +
	"\x06app_id\x18\x01 \x01(\tR\x06app_id\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\x12\x1e\n" +
	"\n" +
	"unit_price\x18\x03 \x01(\tR\n" +
	"unit_price\"9\n" +
	"\x14ShowTotalAmountReply\x12!\n" +
	"\ftotal_amount\x18\x01 \x01(\tR\vtotalAmount\"!\n" +
	"\x0fSaleInfoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xa1\x01\n" +
	"\rSaleInfoReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12.\n" +
	"\x06images\x18\x03 \x01(\v2\x16.google.protobuf.ValueR\x06images\x12\x16\n" +
	"\x06issuer\x18\x04 \x01(\tR\x06issuer\x12$\n" +
	"\rplatform_name\x18\x05 \x01(\tR\rplatform_name\"%\n" +
	"\x13PurchaseInfoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xed\x01\n" +
	"\x11PurchaseInfoReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12$\n" +
	"\rcollection_id\x18\x02 \x01(\tR\rcollection_id\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12.\n" +
	"\x06images\x18\x04 \x01(\v2\x16.google.protobuf.ValueR\x06images\x12\x16\n" +
	"\x06issuer\x18\x05 \x01(\tR\x06issuer\x12$\n" +
	"\rplatform_name\x18\x06 \x01(\tR\rplatform_name\x12 \n" +
	"\vplatform_id\x18\a \x01(\x03R\vplatform_id\"\x15\n" +
	"\x13StockLookAllRequest\";\n" +
	"\x11StockLookAllReply\x12\x14\n" +
	"\x05state\x18\x01 \x01(\x05R\x05state\x12\x10\n" +
	"\x03num\x18\x02 \x01(\x03R\x03num\"\x16\n" +
	"\x14PurchaseIndexRequest\"\x1a\n" +
	"\x18GetSaleCategoriesRequest\"H\n" +
	"\x16GetSaleCategoriesReply\x12.\n" +
	"\x05items\x18\x01 \x03(\v2\x18.xtravel.v1.SaleCategoryR\x05items\"6\n" +
	"\fSaleCategory\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"\x12\n" +
	"\x10SaleIndexRequest\"\x12\n" +
	"\x10GetPayWayRequest\":\n" +
	"\x0eGetPayWayReply\x12(\n" +
	"\x05items\x18\x01 \x03(\v2\x12.xtravel.v1.PayWayR\x05items\">\n" +
	"\x06PayWay\x12\x18\n" +
	"\apay_way\x18\x01 \x01(\x05R\apay_way\x12\x1a\n" +
	"\bpay_name\x18\x02 \x01(\tR\bpay_name\"\x16\n" +
	"\x14CheckExchangeRequest\"\x14\n" +
	"\x12CheckExchangeReply2\xfa\a\n" +
	"\rMarketService\x12a\n" +
	"\tGetPayWay\x12\x1c.xtravel.v1.GetPayWayRequest\x1a\x1a.xtravel.v1.GetPayWayReply\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/market/pay_way\x12t\n" +
	"\rCheckExchange\x12 .xtravel.v1.CheckExchangeRequest\x1a\x1e.xtravel.v1.CheckExchangeReply\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/market/check/exchange\x12c\n" +
	"\rPurchaseIndex\x12 .xtravel.v1.PurchaseIndexRequest\x1a\x13.xtravel.v1.RawData\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/market/purchase\x12\x82\x01\n" +
	"\x11GetSaleCategories\x12$.xtravel.v1.GetSaleCategoriesRequest\x1a\".xtravel.v1.GetSaleCategoriesReply\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v1/market/sales/categories\x12X\n" +
	"\tSaleIndex\x12\x1c.xtravel.v1.SaleIndexRequest\x1a\x13.xtravel.v1.RawData\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/market/sales\x12p\n" +
	"\fStockLookAll\x12\x1f.xtravel.v1.StockLookAllRequest\x1a\x1d.xtravel.v1.StockLookAllReply\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/market/stock/lookall\x12p\n" +
	"\fPurchaseInfo\x12\x1f.xtravel.v1.PurchaseInfoRequest\x1a\x1d.xtravel.v1.PurchaseInfoReply\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/market/purchase/info\x12a\n" +
	"\bSaleInfo\x12\x1b.xtravel.v1.SaleInfoRequest\x1a\x19.xtravel.v1.SaleInfoReply\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/market/sales/info\x12\x84\x01\n" +
	"\x0fShowTotalAmount\x12\".xtravel.v1.ShowTotalAmountRequest\x1a .xtravel.v1.ShowTotalAmountReply\"+\x82\xd3\xe4\x93\x02%\x12#/v1/market/purchase/showTotalAmountB2Z0github.com/lixiaoping4258/ymkj/api/xtravel/v1;v1b\x06proto3"

var (
	file_api_xtravel_v1_market_proto_rawDescOnce sync.Once
	file_api_xtravel_v1_market_proto_rawDescData []byte
)

func file_api_xtravel_v1_market_proto_rawDescGZIP() []byte {
	file_api_xtravel_v1_market_proto_rawDescOnce.Do(func() {
		file_api_xtravel_v1_market_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_xtravel_v1_market_proto_rawDesc), len(file_api_xtravel_v1_market_proto_rawDesc)))
	})
	return file_api_xtravel_v1_market_proto_rawDescData
}

var file_api_xtravel_v1_market_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_api_xtravel_v1_market_proto_goTypes = []any{
	(*ShowTotalAmountRequest)(nil),   // 0: xtravel.v1.ShowTotalAmountRequest
	(*ShowTotalAmountReply)(nil),     // 1: xtravel.v1.ShowTotalAmountReply
	(*SaleInfoRequest)(nil),          // 2: xtravel.v1.SaleInfoRequest
	(*SaleInfoReply)(nil),            // 3: xtravel.v1.SaleInfoReply
	(*PurchaseInfoRequest)(nil),      // 4: xtravel.v1.PurchaseInfoRequest
	(*PurchaseInfoReply)(nil),        // 5: xtravel.v1.PurchaseInfoReply
	(*StockLookAllRequest)(nil),      // 6: xtravel.v1.StockLookAllRequest
	(*StockLookAllReply)(nil),        // 7: xtravel.v1.StockLookAllReply
	(*PurchaseIndexRequest)(nil),     // 8: xtravel.v1.PurchaseIndexRequest
	(*GetSaleCategoriesRequest)(nil), // 9: xtravel.v1.GetSaleCategoriesRequest
	(*GetSaleCategoriesReply)(nil),   // 10: xtravel.v1.GetSaleCategoriesReply
	(*SaleCategory)(nil),             // 11: xtravel.v1.SaleCategory
	(*SaleIndexRequest)(nil),         // 12: xtravel.v1.SaleIndexRequest
	(*GetPayWayRequest)(nil),         // 13: xtravel.v1.GetPayWayRequest
	(*GetPayWayReply)(nil),           // 14: xtravel.v1.GetPayWayReply
	(*PayWay)(nil),                   // 15: xtravel.v1.PayWay
	(*CheckExchangeRequest)(nil),     // 16: xtravel.v1.CheckExchangeRequest
	(*CheckExchangeReply)(nil),       // 17: xtravel.v1.CheckExchangeReply
	(*structpb.Value)(nil),           // 18: google.protobuf.Value
	(*RawData)(nil),                  // 19: xtravel.v1.RawData
}
var file_api_xtravel_v1_market_proto_depIdxs = []int32{
	18, // 0: xtravel.v1.SaleInfoReply.images:type_name -> google.protobuf.Value
	18, // 1: xtravel.v1.PurchaseInfoReply.images:type_name -> google.protobuf.Value
	11, // 2: xtravel.v1.GetSaleCategoriesReply.items:type_name -> xtravel.v1.SaleCategory
	15, // 3: xtravel.v1.GetPayWayReply.items:type_name -> xtravel.v1.PayWay
	13, // 4: xtravel.v1.MarketService.GetPayWay:input_type -> xtravel.v1.GetPayWayRequest
	16, // 5: xtravel.v1.MarketService.CheckExchange:input_type -> xtravel.v1.CheckExchangeRequest
	8,  // 6: xtravel.v1.MarketService.PurchaseIndex:input_type -> xtravel.v1.PurchaseIndexRequest
	9,  // 7: xtravel.v1.MarketService.GetSaleCategories:input_type -> xtravel.v1.GetSaleCategoriesRequest
	12, // 8: xtravel.v1.MarketService.SaleIndex:input_type -> xtravel.v1.SaleIndexRequest
	6,  // 9: xtravel.v1.MarketService.StockLookAll:input_type -> xtravel.v1.StockLookAllRequest
	4,  // 10: xtravel.v1.MarketService.PurchaseInfo:input_type -> xtravel.v1.PurchaseInfoRequest
	2,  // 11: xtravel.v1.MarketService.SaleInfo:input_type -> xtravel.v1.SaleInfoRequest
	0,  // 12: xtravel.v1.MarketService.ShowTotalAmount:input_type -> xtravel.v1.ShowTotalAmountRequest
	14, // 13: xtravel.v1.MarketService.GetPayWay:output_type -> xtravel.v1.GetPayWayReply
	17, // 14: xtravel.v1.MarketService.CheckExchange:output_type -> xtravel.v1.CheckExchangeReply
	19, // 15: xtravel.v1.MarketService.PurchaseIndex:output_type -> xtravel.v1.RawData
	10, // 16: xtravel.v1.MarketService.GetSaleCategories:output_type -> xtravel.v1.GetSaleCategoriesReply
	19, // 17: xtravel.v1.MarketService.SaleIndex:output_type -> xtravel.v1.RawData
	7,  // 18: xtravel.v1.MarketService.StockLookAll:output_type -> xtravel.v1.StockLookAllReply
	5,  // 19: xtravel.v1.MarketService.PurchaseInfo:output_type -> xtravel.v1.PurchaseInfoReply
	3,  // 20: xtravel.v1.MarketService.SaleInfo:output_type -> xtravel.v1.SaleInfoReply
	1,  // 21: xtravel.v1.MarketService.ShowTotalAmount:output_type -> xtravel.v1.ShowTotalAmountReply
	13, // [13:22] is the sub-list for method output_type
	4,  // [4:13] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_xtravel_v1_market_proto_init() }
func file_api_xtravel_v1_market_proto_init() {
	if File_api_xtravel_v1_market_proto != nil {
		return
	}
	file_api_xtravel_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_xtravel_v1_market_proto_rawDesc), len(file_api_xtravel_v1_market_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_xtravel_v1_market_proto_goTypes,
		DependencyIndexes: file_api_xtravel_v1_market_proto_depIdxs,
		MessageInfos:      file_api_xtravel_v1_market_proto_msgTypes,
	}.Build()
	File_api_xtravel_v1_market_proto = out.File
	file_api_xtravel_v1_market_proto_goTypes = nil
	file_api_xtravel_v1_market_proto_depIdxs = nil
}
