// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/xtravel/v1/market.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PurchaseIndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchaseIndexRequest) Reset() {
	*x = PurchaseIndexRequest{}
	mi := &file_api_xtravel_v1_market_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseIndexRequest) ProtoMessage() {}

func (x *PurchaseIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_xtravel_v1_market_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseIndexRequest.ProtoReflect.Descriptor instead.
func (*PurchaseIndexRequest) Descriptor() ([]byte, []int) {
	return file_api_xtravel_v1_market_proto_rawDescGZIP(), []int{0}
}

type GetPayWayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPayWayRequest) Reset() {
	*x = GetPayWayRequest{}
	mi := &file_api_xtravel_v1_market_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPayWayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPayWayRequest) ProtoMessage() {}

func (x *GetPayWayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_xtravel_v1_market_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPayWayRequest.ProtoReflect.Descriptor instead.
func (*GetPayWayRequest) Descriptor() ([]byte, []int) {
	return file_api_xtravel_v1_market_proto_rawDescGZIP(), []int{1}
}

type GetPayWayReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ⚠️ 原接口的 data 是**顶层数组**而不是对象：
	//
	//	{"code":1,"show":0,"msg":"","data":[{"pay_way":1,...}]}
	//	Kratos 的 reply 是 message，默认会被包成 {"data":{"items":[...]}}。
	//	所以这里靠 api/xtravel/v1/envelope.go 里的 Envelope() 把 items 摊出去。
	Items         []*PayWay `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPayWayReply) Reset() {
	*x = GetPayWayReply{}
	mi := &file_api_xtravel_v1_market_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPayWayReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPayWayReply) ProtoMessage() {}

func (x *GetPayWayReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_xtravel_v1_market_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPayWayReply.ProtoReflect.Descriptor instead.
func (*GetPayWayReply) Descriptor() ([]byte, []int) {
	return file_api_xtravel_v1_market_proto_rawDescGZIP(), []int{2}
}

func (x *GetPayWayReply) GetItems() []*PayWay {
	if x != nil {
		return x.Items
	}
	return nil
}

type PayWay struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 原 PHP 是硬编码数组 ['pay_way' => 1, 'pay_name' => '茶交所']，
	// json_encode 出来就是下划线键名。必须显式指定 json_name，
	// 否则 protojson 会输出 payWay / payName，前端取不到字段。
	PayWay        int32  `protobuf:"varint,1,opt,name=pay_way,proto3" json:"pay_way,omitempty"`
	PayName       string `protobuf:"bytes,2,opt,name=pay_name,proto3" json:"pay_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayWay) Reset() {
	*x = PayWay{}
	mi := &file_api_xtravel_v1_market_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayWay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayWay) ProtoMessage() {}

func (x *PayWay) ProtoReflect() protoreflect.Message {
	mi := &file_api_xtravel_v1_market_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayWay.ProtoReflect.Descriptor instead.
func (*PayWay) Descriptor() ([]byte, []int) {
	return file_api_xtravel_v1_market_proto_rawDescGZIP(), []int{3}
}

func (x *PayWay) GetPayWay() int32 {
	if x != nil {
		return x.PayWay
	}
	return 0
}

func (x *PayWay) GetPayName() string {
	if x != nil {
		return x.PayName
	}
	return ""
}

type CheckExchangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckExchangeRequest) Reset() {
	*x = CheckExchangeRequest{}
	mi := &file_api_xtravel_v1_market_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckExchangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckExchangeRequest) ProtoMessage() {}

func (x *CheckExchangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_xtravel_v1_market_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckExchangeRequest.ProtoReflect.Descriptor instead.
func (*CheckExchangeRequest) Descriptor() ([]byte, []int) {
	return file_api_xtravel_v1_market_proto_rawDescGZIP(), []int{4}
}

// 成功时原接口返回的是**空数组** []（`return $this->data([])`），
// 不是空对象 {}。同样由 Envelope() 处理。
type CheckExchangeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckExchangeReply) Reset() {
	*x = CheckExchangeReply{}
	mi := &file_api_xtravel_v1_market_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckExchangeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckExchangeReply) ProtoMessage() {}

func (x *CheckExchangeReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_xtravel_v1_market_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckExchangeReply.ProtoReflect.Descriptor instead.
func (*CheckExchangeReply) Descriptor() ([]byte, []int) {
	return file_api_xtravel_v1_market_proto_rawDescGZIP(), []int{5}
}

var File_api_xtravel_v1_market_proto protoreflect.FileDescriptor

const file_api_xtravel_v1_market_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/xtravel/v1/market.proto\x12\n" +
	"xtravel.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bapi/xtravel/v1/common.proto\"\x16\n" +
	"\x14PurchaseIndexRequest\"\x12\n" +
	"\x10GetPayWayRequest\":\n" +
	"\x0eGetPayWayReply\x12(\n" +
	"\x05items\x18\x01 \x03(\v2\x12.xtravel.v1.PayWayR\x05items\">\n" +
	"\x06PayWay\x12\x18\n" +
	"\apay_way\x18\x01 \x01(\x05R\apay_way\x12\x1a\n" +
	"\bpay_name\x18\x02 \x01(\tR\bpay_name\"\x16\n" +
	"\x14CheckExchangeRequest\"\x14\n" +
	"\x12CheckExchangeReply2\xcd\x02\n" +
	"\rMarketService\x12a\n" +
	"\tGetPayWay\x12\x1c.xtravel.v1.GetPayWayRequest\x1a\x1a.xtravel.v1.GetPayWayReply\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/market/pay_way\x12t\n" +
	"\rCheckExchange\x12 .xtravel.v1.CheckExchangeRequest\x1a\x1e.xtravel.v1.CheckExchangeReply\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/market/check/exchange\x12c\n" +
	"\rPurchaseIndex\x12 .xtravel.v1.PurchaseIndexRequest\x1a\x13.xtravel.v1.RawData\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/market/purchaseB2Z0github.com/lixiaoping4258/ymkj/api/xtravel/v1;v1b\x06proto3"

var (
	file_api_xtravel_v1_market_proto_rawDescOnce sync.Once
	file_api_xtravel_v1_market_proto_rawDescData []byte
)

func file_api_xtravel_v1_market_proto_rawDescGZIP() []byte {
	file_api_xtravel_v1_market_proto_rawDescOnce.Do(func() {
		file_api_xtravel_v1_market_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_xtravel_v1_market_proto_rawDesc), len(file_api_xtravel_v1_market_proto_rawDesc)))
	})
	return file_api_xtravel_v1_market_proto_rawDescData
}

var file_api_xtravel_v1_market_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_xtravel_v1_market_proto_goTypes = []any{
	(*PurchaseIndexRequest)(nil), // 0: xtravel.v1.PurchaseIndexRequest
	(*GetPayWayRequest)(nil),     // 1: xtravel.v1.GetPayWayRequest
	(*GetPayWayReply)(nil),       // 2: xtravel.v1.GetPayWayReply
	(*PayWay)(nil),               // 3: xtravel.v1.PayWay
	(*CheckExchangeRequest)(nil), // 4: xtravel.v1.CheckExchangeRequest
	(*CheckExchangeReply)(nil),   // 5: xtravel.v1.CheckExchangeReply
	(*RawData)(nil),              // 6: xtravel.v1.RawData
}
var file_api_xtravel_v1_market_proto_depIdxs = []int32{
	3, // 0: xtravel.v1.GetPayWayReply.items:type_name -> xtravel.v1.PayWay
	1, // 1: xtravel.v1.MarketService.GetPayWay:input_type -> xtravel.v1.GetPayWayRequest
	4, // 2: xtravel.v1.MarketService.CheckExchange:input_type -> xtravel.v1.CheckExchangeRequest
	0, // 3: xtravel.v1.MarketService.PurchaseIndex:input_type -> xtravel.v1.PurchaseIndexRequest
	2, // 4: xtravel.v1.MarketService.GetPayWay:output_type -> xtravel.v1.GetPayWayReply
	5, // 5: xtravel.v1.MarketService.CheckExchange:output_type -> xtravel.v1.CheckExchangeReply
	6, // 6: xtravel.v1.MarketService.PurchaseIndex:output_type -> xtravel.v1.RawData
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_xtravel_v1_market_proto_init() }
func file_api_xtravel_v1_market_proto_init() {
	if File_api_xtravel_v1_market_proto != nil {
		return
	}
	file_api_xtravel_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_xtravel_v1_market_proto_rawDesc), len(file_api_xtravel_v1_market_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_xtravel_v1_market_proto_goTypes,
		DependencyIndexes: file_api_xtravel_v1_market_proto_depIdxs,
		MessageInfos:      file_api_xtravel_v1_market_proto_msgTypes,
	}.Build()
	File_api_xtravel_v1_market_proto = out.File
	file_api_xtravel_v1_market_proto_goTypes = nil
	file_api_xtravel_v1_market_proto_depIdxs = nil
}
