// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: api/xtravel/v1/market.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MarketService_GetPayWay_FullMethodName         = "/xtravel.v1.MarketService/GetPayWay"
	MarketService_CheckExchange_FullMethodName     = "/xtravel.v1.MarketService/CheckExchange"
	MarketService_PurchaseIndex_FullMethodName     = "/xtravel.v1.MarketService/PurchaseIndex"
	MarketService_GetSaleCategories_FullMethodName = "/xtravel.v1.MarketService/GetSaleCategories"
	MarketService_SaleIndex_FullMethodName         = "/xtravel.v1.MarketService/SaleIndex"
	MarketService_StockLookAll_FullMethodName      = "/xtravel.v1.MarketService/StockLookAll"
	MarketService_PurchaseInfo_FullMethodName      = "/xtravel.v1.MarketService/PurchaseInfo"
)

// MarketServiceClient is the client API for MarketService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MarketService 市场交易域。
// 对应原项目 app/api/route/market.php（44 条路由）与 app/api/controller/v1/market/*。
//
// ⚠️ 这是项目核心业务域，Stage 3 分批迁。本文件当前只包含第一批：
// 两个不涉及资金、不改数据的只读接口。写入类接口（下单/支付/兑换）
// 必须单独评估，不能顺手一起做。
type MarketServiceClient interface {
	// 支付方式列表
	// 原: PurchaseController::payWay（硬编码，不查库；需要登录）
	GetPayWay(ctx context.Context, in *GetPayWayRequest, opts ...grpc.CallOption) (*GetPayWayReply, error)
	// 兑换前置校验
	// 原: PurchaseController::checkExchange -> GoodsLogic::checkExchange
	//
	//	（需要登录；会加 2 秒防重复点击锁并查一次兑换单数量）
	CheckExchange(ctx context.Context, in *CheckExchangeRequest, opts ...grpc.CallOption) (*CheckExchangeReply, error)
	// 兑换专区首页列表
	// 原: PurchaseController::index -> PurchaseFaceLists
	//
	//	**免登录**（控制器 $notNeedLogin 放行了 index）
	//	挂白名单 no_collection_trade
	//	走交易时段判断；带 20 秒整包缓存
	//
	// 返回 RawData：列表行结构任意（bigint 主键 / decimal 字符串 / json 数组 /
	// "0 转 --" 后处理），用 proto 建模会丢精度又拧巴，见 common.proto 的说明。
	PurchaseIndex(ctx context.Context, in *PurchaseIndexRequest, opts ...grpc.CallOption) (*RawData, error)
	// 秒转专区分类列表
	// 原: SaleController::categories —— **硬编码**，不查库；是 SaleController 里
	//
	//	唯一免登录的方法（$notNeedLogin = ['categories']）
	GetSaleCategories(ctx context.Context, in *GetSaleCategoriesRequest, opts ...grpc.CallOption) (*GetSaleCategoriesReply, error)
	// 秒转专区首页列表
	// 原: SaleController::index -> SaleFaceLists
	//
	//	**需要登录**（不在 $notNeedLogin 里）
	//
	// ⚠️ 与 purchase 列表的两个差异（都是实测出来的）：
	//  1. 该接口没有默认排序 —— PurchaseFaceLists 的 switch 有 default 分支，
	//     SaleFaceLists 没有，所以**不带 sort 参数时 SQL 里根本没有 ORDER BY**
	//  2. 行后处理只做 images 的 json 解码，没有 "0 转 --" 那套
	SaleIndex(ctx context.Context, in *SaleIndexRequest, opts ...grpc.CallOption) (*RawData, error)
	// 库存汇总（可释放数量 + 是否有释放任务在处理中）
	// 原: PurchaseController::lookAll -> GoodsLogic::lookAll
	//
	//	**需要登录**；结果缓存 10 秒
	//
	// ⚠️ state 字段迁移期恒为 1：它依赖的"释放任务进行中"标记由 PHP 用
	//
	//	ThinkPHP 的 cache() 写入，键空间与 Go 侧隔离。详见 biz/stock.go。
	StockLookAll(ctx context.Context, in *StockLookAllRequest, opts ...grpc.CallOption) (*StockLookAllReply, error)
	// 藏品封面（档案基础信息）
	// 原: PurchaseController::purchaseInfo -> MarketListPurchaseLogic::getArchive
	//
	//	**需要登录**；结果按 archive id 缓存 600 秒
	PurchaseInfo(ctx context.Context, in *PurchaseInfoRequest, opts ...grpc.CallOption) (*PurchaseInfoReply, error)
}

type marketServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMarketServiceClient(cc grpc.ClientConnInterface) MarketServiceClient {
	return &marketServiceClient{cc}
}

func (c *marketServiceClient) GetPayWay(ctx context.Context, in *GetPayWayRequest, opts ...grpc.CallOption) (*GetPayWayReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPayWayReply)
	err := c.cc.Invoke(ctx, MarketService_GetPayWay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketServiceClient) CheckExchange(ctx context.Context, in *CheckExchangeRequest, opts ...grpc.CallOption) (*CheckExchangeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckExchangeReply)
	err := c.cc.Invoke(ctx, MarketService_CheckExchange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketServiceClient) PurchaseIndex(ctx context.Context, in *PurchaseIndexRequest, opts ...grpc.CallOption) (*RawData, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RawData)
	err := c.cc.Invoke(ctx, MarketService_PurchaseIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketServiceClient) GetSaleCategories(ctx context.Context, in *GetSaleCategoriesRequest, opts ...grpc.CallOption) (*GetSaleCategoriesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSaleCategoriesReply)
	err := c.cc.Invoke(ctx, MarketService_GetSaleCategories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketServiceClient) SaleIndex(ctx context.Context, in *SaleIndexRequest, opts ...grpc.CallOption) (*RawData, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RawData)
	err := c.cc.Invoke(ctx, MarketService_SaleIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketServiceClient) StockLookAll(ctx context.Context, in *StockLookAllRequest, opts ...grpc.CallOption) (*StockLookAllReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StockLookAllReply)
	err := c.cc.Invoke(ctx, MarketService_StockLookAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketServiceClient) PurchaseInfo(ctx context.Context, in *PurchaseInfoRequest, opts ...grpc.CallOption) (*PurchaseInfoReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PurchaseInfoReply)
	err := c.cc.Invoke(ctx, MarketService_PurchaseInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarketServiceServer is the server API for MarketService service.
// All implementations must embed UnimplementedMarketServiceServer
// for forward compatibility.
//
// MarketService 市场交易域。
// 对应原项目 app/api/route/market.php（44 条路由）与 app/api/controller/v1/market/*。
//
// ⚠️ 这是项目核心业务域，Stage 3 分批迁。本文件当前只包含第一批：
// 两个不涉及资金、不改数据的只读接口。写入类接口（下单/支付/兑换）
// 必须单独评估，不能顺手一起做。
type MarketServiceServer interface {
	// 支付方式列表
	// 原: PurchaseController::payWay（硬编码，不查库；需要登录）
	GetPayWay(context.Context, *GetPayWayRequest) (*GetPayWayReply, error)
	// 兑换前置校验
	// 原: PurchaseController::checkExchange -> GoodsLogic::checkExchange
	//
	//	（需要登录；会加 2 秒防重复点击锁并查一次兑换单数量）
	CheckExchange(context.Context, *CheckExchangeRequest) (*CheckExchangeReply, error)
	// 兑换专区首页列表
	// 原: PurchaseController::index -> PurchaseFaceLists
	//
	//	**免登录**（控制器 $notNeedLogin 放行了 index）
	//	挂白名单 no_collection_trade
	//	走交易时段判断；带 20 秒整包缓存
	//
	// 返回 RawData：列表行结构任意（bigint 主键 / decimal 字符串 / json 数组 /
	// "0 转 --" 后处理），用 proto 建模会丢精度又拧巴，见 common.proto 的说明。
	PurchaseIndex(context.Context, *PurchaseIndexRequest) (*RawData, error)
	// 秒转专区分类列表
	// 原: SaleController::categories —— **硬编码**，不查库；是 SaleController 里
	//
	//	唯一免登录的方法（$notNeedLogin = ['categories']）
	GetSaleCategories(context.Context, *GetSaleCategoriesRequest) (*GetSaleCategoriesReply, error)
	// 秒转专区首页列表
	// 原: SaleController::index -> SaleFaceLists
	//
	//	**需要登录**（不在 $notNeedLogin 里）
	//
	// ⚠️ 与 purchase 列表的两个差异（都是实测出来的）：
	//  1. 该接口没有默认排序 —— PurchaseFaceLists 的 switch 有 default 分支，
	//     SaleFaceLists 没有，所以**不带 sort 参数时 SQL 里根本没有 ORDER BY**
	//  2. 行后处理只做 images 的 json 解码，没有 "0 转 --" 那套
	SaleIndex(context.Context, *SaleIndexRequest) (*RawData, error)
	// 库存汇总（可释放数量 + 是否有释放任务在处理中）
	// 原: PurchaseController::lookAll -> GoodsLogic::lookAll
	//
	//	**需要登录**；结果缓存 10 秒
	//
	// ⚠️ state 字段迁移期恒为 1：它依赖的"释放任务进行中"标记由 PHP 用
	//
	//	ThinkPHP 的 cache() 写入，键空间与 Go 侧隔离。详见 biz/stock.go。
	StockLookAll(context.Context, *StockLookAllRequest) (*StockLookAllReply, error)
	// 藏品封面（档案基础信息）
	// 原: PurchaseController::purchaseInfo -> MarketListPurchaseLogic::getArchive
	//
	//	**需要登录**；结果按 archive id 缓存 600 秒
	PurchaseInfo(context.Context, *PurchaseInfoRequest) (*PurchaseInfoReply, error)
	mustEmbedUnimplementedMarketServiceServer()
}

// UnimplementedMarketServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMarketServiceServer struct{}

func (UnimplementedMarketServiceServer) GetPayWay(context.Context, *GetPayWayRequest) (*GetPayWayReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPayWay not implemented")
}
func (UnimplementedMarketServiceServer) CheckExchange(context.Context, *CheckExchangeRequest) (*CheckExchangeReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckExchange not implemented")
}
func (UnimplementedMarketServiceServer) PurchaseIndex(context.Context, *PurchaseIndexRequest) (*RawData, error) {
	return nil, status.Error(codes.Unimplemented, "method PurchaseIndex not implemented")
}
func (UnimplementedMarketServiceServer) GetSaleCategories(context.Context, *GetSaleCategoriesRequest) (*GetSaleCategoriesReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSaleCategories not implemented")
}
func (UnimplementedMarketServiceServer) SaleIndex(context.Context, *SaleIndexRequest) (*RawData, error) {
	return nil, status.Error(codes.Unimplemented, "method SaleIndex not implemented")
}
func (UnimplementedMarketServiceServer) StockLookAll(context.Context, *StockLookAllRequest) (*StockLookAllReply, error) {
	return nil, status.Error(codes.Unimplemented, "method StockLookAll not implemented")
}
func (UnimplementedMarketServiceServer) PurchaseInfo(context.Context, *PurchaseInfoRequest) (*PurchaseInfoReply, error) {
	return nil, status.Error(codes.Unimplemented, "method PurchaseInfo not implemented")
}
func (UnimplementedMarketServiceServer) mustEmbedUnimplementedMarketServiceServer() {}
func (UnimplementedMarketServiceServer) testEmbeddedByValue()                       {}

// UnsafeMarketServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarketServiceServer will
// result in compilation errors.
type UnsafeMarketServiceServer interface {
	mustEmbedUnimplementedMarketServiceServer()
}

func RegisterMarketServiceServer(s grpc.ServiceRegistrar, srv MarketServiceServer) {
	// If the following call panics, it indicates UnimplementedMarketServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MarketService_ServiceDesc, srv)
}

func _MarketService_GetPayWay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPayWayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).GetPayWay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketService_GetPayWay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).GetPayWay(ctx, req.(*GetPayWayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_CheckExchange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckExchangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).CheckExchange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketService_CheckExchange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).CheckExchange(ctx, req.(*CheckExchangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_PurchaseIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurchaseIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).PurchaseIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketService_PurchaseIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).PurchaseIndex(ctx, req.(*PurchaseIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_GetSaleCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSaleCategoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).GetSaleCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketService_GetSaleCategories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).GetSaleCategories(ctx, req.(*GetSaleCategoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_SaleIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaleIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).SaleIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketService_SaleIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).SaleIndex(ctx, req.(*SaleIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_StockLookAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StockLookAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).StockLookAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketService_StockLookAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).StockLookAll(ctx, req.(*StockLookAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_PurchaseInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurchaseInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).PurchaseInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketService_PurchaseInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).PurchaseInfo(ctx, req.(*PurchaseInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MarketService_ServiceDesc is the grpc.ServiceDesc for MarketService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MarketService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xtravel.v1.MarketService",
	HandlerType: (*MarketServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPayWay",
			Handler:    _MarketService_GetPayWay_Handler,
		},
		{
			MethodName: "CheckExchange",
			Handler:    _MarketService_CheckExchange_Handler,
		},
		{
			MethodName: "PurchaseIndex",
			Handler:    _MarketService_PurchaseIndex_Handler,
		},
		{
			MethodName: "GetSaleCategories",
			Handler:    _MarketService_GetSaleCategories_Handler,
		},
		{
			MethodName: "SaleIndex",
			Handler:    _MarketService_SaleIndex_Handler,
		},
		{
			MethodName: "StockLookAll",
			Handler:    _MarketService_StockLookAll_Handler,
		},
		{
			MethodName: "PurchaseInfo",
			Handler:    _MarketService_PurchaseInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/xtravel/v1/market.proto",
}
