// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: api/xtravel/v1/market.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MarketService_GetPayWay_FullMethodName         = "/xtravel.v1.MarketService/GetPayWay"
	MarketService_CheckExchange_FullMethodName     = "/xtravel.v1.MarketService/CheckExchange"
	MarketService_PurchaseIndex_FullMethodName     = "/xtravel.v1.MarketService/PurchaseIndex"
	MarketService_GetSaleCategories_FullMethodName = "/xtravel.v1.MarketService/GetSaleCategories"
	MarketService_SaleIndex_FullMethodName         = "/xtravel.v1.MarketService/SaleIndex"
	MarketService_StockLookAll_FullMethodName      = "/xtravel.v1.MarketService/StockLookAll"
	MarketService_PurchaseInfo_FullMethodName      = "/xtravel.v1.MarketService/PurchaseInfo"
	MarketService_SaleInfo_FullMethodName          = "/xtravel.v1.MarketService/SaleInfo"
	MarketService_ShowTotalAmount_FullMethodName   = "/xtravel.v1.MarketService/ShowTotalAmount"
	MarketService_PurchaseOut_FullMethodName       = "/xtravel.v1.MarketService/PurchaseOut"
	MarketService_PurchaseOn_FullMethodName        = "/xtravel.v1.MarketService/PurchaseOn"
)

// MarketServiceClient is the client API for MarketService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MarketService 市场交易域。
// 对应原项目 app/api/route/market.php（44 条路由）与 app/api/controller/v1/market/*。
//
// ⚠️ 这是项目核心业务域，Stage 3 分批迁。本文件当前只包含第一批：
// 两个不涉及资金、不改数据的只读接口。写入类接口（下单/支付/兑换）
// 必须单独评估，不能顺手一起做。
type MarketServiceClient interface {
	// 支付方式列表
	// 原: PurchaseController::payWay（硬编码，不查库；需要登录）
	GetPayWay(ctx context.Context, in *GetPayWayRequest, opts ...grpc.CallOption) (*GetPayWayReply, error)
	// 兑换前置校验
	// 原: PurchaseController::checkExchange -> GoodsLogic::checkExchange
	//
	//	（需要登录；会加 2 秒防重复点击锁并查一次兑换单数量）
	CheckExchange(ctx context.Context, in *CheckExchangeRequest, opts ...grpc.CallOption) (*CheckExchangeReply, error)
	// 兑换专区首页列表
	// 原: PurchaseController::index -> PurchaseFaceLists
	//
	//	**免登录**（控制器 $notNeedLogin 放行了 index）
	//	挂白名单 no_collection_trade
	//	走交易时段判断；带 20 秒整包缓存
	//
	// 返回 RawData：列表行结构任意（bigint 主键 / decimal 字符串 / json 数组 /
	// "0 转 --" 后处理），用 proto 建模会丢精度又拧巴，见 common.proto 的说明。
	PurchaseIndex(ctx context.Context, in *PurchaseIndexRequest, opts ...grpc.CallOption) (*RawData, error)
	// 秒转专区分类列表
	// 原: SaleController::categories —— **硬编码**，不查库；是 SaleController 里
	//
	//	唯一免登录的方法（$notNeedLogin = ['categories']）
	GetSaleCategories(ctx context.Context, in *GetSaleCategoriesRequest, opts ...grpc.CallOption) (*GetSaleCategoriesReply, error)
	// 秒转专区首页列表
	// 原: SaleController::index -> SaleFaceLists
	//
	//	**需要登录**（不在 $notNeedLogin 里）
	//
	// ⚠️ 与 purchase 列表的两个差异（都是实测出来的）：
	//  1. 该接口没有默认排序 —— PurchaseFaceLists 的 switch 有 default 分支，
	//     SaleFaceLists 没有，所以**不带 sort 参数时 SQL 里根本没有 ORDER BY**
	//  2. 行后处理只做 images 的 json 解码，没有 "0 转 --" 那套
	SaleIndex(ctx context.Context, in *SaleIndexRequest, opts ...grpc.CallOption) (*RawData, error)
	// 库存汇总（可释放数量 + 是否有释放任务在处理中）
	// 原: PurchaseController::lookAll -> GoodsLogic::lookAll
	//
	//	**需要登录**；结果缓存 10 秒
	//
	// ⚠️ state 字段迁移期恒为 1：它依赖的"释放任务进行中"标记由 PHP 用
	//
	//	ThinkPHP 的 cache() 写入，键空间与 Go 侧隔离。详见 biz/stock.go。
	StockLookAll(ctx context.Context, in *StockLookAllRequest, opts ...grpc.CallOption) (*StockLookAllReply, error)
	// 藏品封面（档案基础信息）
	// 原: PurchaseController::purchaseInfo -> MarketListPurchaseLogic::getArchive
	//
	//	**需要登录**；结果按 archive id 缓存 600 秒
	PurchaseInfo(ctx context.Context, in *PurchaseInfoRequest, opts ...grpc.CallOption) (*PurchaseInfoReply, error)
	// 秒转藏品封面
	// 原: SaleController::saleInfo -> MarketListSalesLogic::findSales + SaleLogic::getArchive
	//
	//	**需要登录**
	//
	// ⚠️ 与 PurchaseInfo 不是同一个函数，尽管缓存键看起来一样：
	//
	//	本例走 SaleLogic::getArchive，用 TP 的 cache()（物理键 la:archive:{id}），
	//	**只有 5 个字段**（没有 collection_id / platform_id），TTL 3600s；
	//	PurchaseInfo 走 MarketListPurchaseLogic::getArchive，用 RedisLockService
	//	（物理键 archive:{id}），有 7 个字段，TTL 600s。
	//	两者物理键不同所以不会互相覆盖，但字段集不同 —— 不要"顺手统一"。
	SaleInfo(ctx context.Context, in *SaleInfoRequest, opts ...grpc.CallOption) (*SaleInfoReply, error)
	// 计算总额（含服务手续费）
	// 原: PurchaseOrdersController::showTotalAmount -> FeeAmountLogic::showTotalAmount
	//
	// ⚠️ totalAmount 是**字符串**，不是数字：原实现返回的是 bcsub 的结果，
	//
	//	且参数不合法时是 '0'（没有小数位），合法时是 2 位小数。
	ShowTotalAmount(ctx context.Context, in *ShowTotalAmountRequest, opts ...grpc.CallOption) (*ShowTotalAmountReply, error)
	// 兑换售出列表（state=COMPLETE）
	// 原: PurchaseController::salesOut -> PurchaseStateLists(['state'=>'COMPLETE'])
	//
	//	需要登录；结果按参数 md5 缓存 10 秒（简单 TTL，无锁）
	//
	// ⚠️ count 与 lists 可能对不上：lists 在 SQL 层过滤，但原实现对 WANTED 状态
	//
	//	还有一次**分页之后**的过滤；COMPLETE 分支没有那次过滤。
	PurchaseOut(ctx context.Context, in *PurchaseOutRequest, opts ...grpc.CallOption) (*RawData, error)
	// 兑换中列表（state=WANTED）
	// 原: PurchaseController::salesOn -> PurchaseStateLists(['state'=>'WANTED'])
	//
	//	需要登录
	//
	// ⚠️ 与 purchase/out 的两处差异：
	//  1. 排序不同：unit_price DESC, grab_time ASC, create_time ASC, id DESC
	//  2. **分页之后**会过滤掉 available_amount <= 0 的行 ——
	//     所以返回行数可能少于 page_size，而 count() 不做这个过滤，
	//     **count 与 lists 天然对不上**（原实现行为，刻意保持）
	//
	// 原实现还挂了 stale-while-revalidate 缓存（逻辑过期 5s / 物理 15s / 重建锁 5s），
	// 本批**未接**，每次直查。功能正确，少了缓存。
	PurchaseOn(ctx context.Context, in *PurchaseOnRequest, opts ...grpc.CallOption) (*RawData, error)
}

type marketServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMarketServiceClient(cc grpc.ClientConnInterface) MarketServiceClient {
	return &marketServiceClient{cc}
}

func (c *marketServiceClient) GetPayWay(ctx context.Context, in *GetPayWayRequest, opts ...grpc.CallOption) (*GetPayWayReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPayWayReply)
	err := c.cc.Invoke(ctx, MarketService_GetPayWay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketServiceClient) CheckExchange(ctx context.Context, in *CheckExchangeRequest, opts ...grpc.CallOption) (*CheckExchangeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckExchangeReply)
	err := c.cc.Invoke(ctx, MarketService_CheckExchange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketServiceClient) PurchaseIndex(ctx context.Context, in *PurchaseIndexRequest, opts ...grpc.CallOption) (*RawData, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RawData)
	err := c.cc.Invoke(ctx, MarketService_PurchaseIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketServiceClient) GetSaleCategories(ctx context.Context, in *GetSaleCategoriesRequest, opts ...grpc.CallOption) (*GetSaleCategoriesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSaleCategoriesReply)
	err := c.cc.Invoke(ctx, MarketService_GetSaleCategories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketServiceClient) SaleIndex(ctx context.Context, in *SaleIndexRequest, opts ...grpc.CallOption) (*RawData, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RawData)
	err := c.cc.Invoke(ctx, MarketService_SaleIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketServiceClient) StockLookAll(ctx context.Context, in *StockLookAllRequest, opts ...grpc.CallOption) (*StockLookAllReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StockLookAllReply)
	err := c.cc.Invoke(ctx, MarketService_StockLookAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketServiceClient) PurchaseInfo(ctx context.Context, in *PurchaseInfoRequest, opts ...grpc.CallOption) (*PurchaseInfoReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PurchaseInfoReply)
	err := c.cc.Invoke(ctx, MarketService_PurchaseInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketServiceClient) SaleInfo(ctx context.Context, in *SaleInfoRequest, opts ...grpc.CallOption) (*SaleInfoReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaleInfoReply)
	err := c.cc.Invoke(ctx, MarketService_SaleInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketServiceClient) ShowTotalAmount(ctx context.Context, in *ShowTotalAmountRequest, opts ...grpc.CallOption) (*ShowTotalAmountReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShowTotalAmountReply)
	err := c.cc.Invoke(ctx, MarketService_ShowTotalAmount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketServiceClient) PurchaseOut(ctx context.Context, in *PurchaseOutRequest, opts ...grpc.CallOption) (*RawData, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RawData)
	err := c.cc.Invoke(ctx, MarketService_PurchaseOut_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketServiceClient) PurchaseOn(ctx context.Context, in *PurchaseOnRequest, opts ...grpc.CallOption) (*RawData, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RawData)
	err := c.cc.Invoke(ctx, MarketService_PurchaseOn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarketServiceServer is the server API for MarketService service.
// All implementations must embed UnimplementedMarketServiceServer
// for forward compatibility.
//
// MarketService 市场交易域。
// 对应原项目 app/api/route/market.php（44 条路由）与 app/api/controller/v1/market/*。
//
// ⚠️ 这是项目核心业务域，Stage 3 分批迁。本文件当前只包含第一批：
// 两个不涉及资金、不改数据的只读接口。写入类接口（下单/支付/兑换）
// 必须单独评估，不能顺手一起做。
type MarketServiceServer interface {
	// 支付方式列表
	// 原: PurchaseController::payWay（硬编码，不查库；需要登录）
	GetPayWay(context.Context, *GetPayWayRequest) (*GetPayWayReply, error)
	// 兑换前置校验
	// 原: PurchaseController::checkExchange -> GoodsLogic::checkExchange
	//
	//	（需要登录；会加 2 秒防重复点击锁并查一次兑换单数量）
	CheckExchange(context.Context, *CheckExchangeRequest) (*CheckExchangeReply, error)
	// 兑换专区首页列表
	// 原: PurchaseController::index -> PurchaseFaceLists
	//
	//	**免登录**（控制器 $notNeedLogin 放行了 index）
	//	挂白名单 no_collection_trade
	//	走交易时段判断；带 20 秒整包缓存
	//
	// 返回 RawData：列表行结构任意（bigint 主键 / decimal 字符串 / json 数组 /
	// "0 转 --" 后处理），用 proto 建模会丢精度又拧巴，见 common.proto 的说明。
	PurchaseIndex(context.Context, *PurchaseIndexRequest) (*RawData, error)
	// 秒转专区分类列表
	// 原: SaleController::categories —— **硬编码**，不查库；是 SaleController 里
	//
	//	唯一免登录的方法（$notNeedLogin = ['categories']）
	GetSaleCategories(context.Context, *GetSaleCategoriesRequest) (*GetSaleCategoriesReply, error)
	// 秒转专区首页列表
	// 原: SaleController::index -> SaleFaceLists
	//
	//	**需要登录**（不在 $notNeedLogin 里）
	//
	// ⚠️ 与 purchase 列表的两个差异（都是实测出来的）：
	//  1. 该接口没有默认排序 —— PurchaseFaceLists 的 switch 有 default 分支，
	//     SaleFaceLists 没有，所以**不带 sort 参数时 SQL 里根本没有 ORDER BY**
	//  2. 行后处理只做 images 的 json 解码，没有 "0 转 --" 那套
	SaleIndex(context.Context, *SaleIndexRequest) (*RawData, error)
	// 库存汇总（可释放数量 + 是否有释放任务在处理中）
	// 原: PurchaseController::lookAll -> GoodsLogic::lookAll
	//
	//	**需要登录**；结果缓存 10 秒
	//
	// ⚠️ state 字段迁移期恒为 1：它依赖的"释放任务进行中"标记由 PHP 用
	//
	//	ThinkPHP 的 cache() 写入，键空间与 Go 侧隔离。详见 biz/stock.go。
	StockLookAll(context.Context, *StockLookAllRequest) (*StockLookAllReply, error)
	// 藏品封面（档案基础信息）
	// 原: PurchaseController::purchaseInfo -> MarketListPurchaseLogic::getArchive
	//
	//	**需要登录**；结果按 archive id 缓存 600 秒
	PurchaseInfo(context.Context, *PurchaseInfoRequest) (*PurchaseInfoReply, error)
	// 秒转藏品封面
	// 原: SaleController::saleInfo -> MarketListSalesLogic::findSales + SaleLogic::getArchive
	//
	//	**需要登录**
	//
	// ⚠️ 与 PurchaseInfo 不是同一个函数，尽管缓存键看起来一样：
	//
	//	本例走 SaleLogic::getArchive，用 TP 的 cache()（物理键 la:archive:{id}），
	//	**只有 5 个字段**（没有 collection_id / platform_id），TTL 3600s；
	//	PurchaseInfo 走 MarketListPurchaseLogic::getArchive，用 RedisLockService
	//	（物理键 archive:{id}），有 7 个字段，TTL 600s。
	//	两者物理键不同所以不会互相覆盖，但字段集不同 —— 不要"顺手统一"。
	SaleInfo(context.Context, *SaleInfoRequest) (*SaleInfoReply, error)
	// 计算总额（含服务手续费）
	// 原: PurchaseOrdersController::showTotalAmount -> FeeAmountLogic::showTotalAmount
	//
	// ⚠️ totalAmount 是**字符串**，不是数字：原实现返回的是 bcsub 的结果，
	//
	//	且参数不合法时是 '0'（没有小数位），合法时是 2 位小数。
	ShowTotalAmount(context.Context, *ShowTotalAmountRequest) (*ShowTotalAmountReply, error)
	// 兑换售出列表（state=COMPLETE）
	// 原: PurchaseController::salesOut -> PurchaseStateLists(['state'=>'COMPLETE'])
	//
	//	需要登录；结果按参数 md5 缓存 10 秒（简单 TTL，无锁）
	//
	// ⚠️ count 与 lists 可能对不上：lists 在 SQL 层过滤，但原实现对 WANTED 状态
	//
	//	还有一次**分页之后**的过滤；COMPLETE 分支没有那次过滤。
	PurchaseOut(context.Context, *PurchaseOutRequest) (*RawData, error)
	// 兑换中列表（state=WANTED）
	// 原: PurchaseController::salesOn -> PurchaseStateLists(['state'=>'WANTED'])
	//
	//	需要登录
	//
	// ⚠️ 与 purchase/out 的两处差异：
	//  1. 排序不同：unit_price DESC, grab_time ASC, create_time ASC, id DESC
	//  2. **分页之后**会过滤掉 available_amount <= 0 的行 ——
	//     所以返回行数可能少于 page_size，而 count() 不做这个过滤，
	//     **count 与 lists 天然对不上**（原实现行为，刻意保持）
	//
	// 原实现还挂了 stale-while-revalidate 缓存（逻辑过期 5s / 物理 15s / 重建锁 5s），
	// 本批**未接**，每次直查。功能正确，少了缓存。
	PurchaseOn(context.Context, *PurchaseOnRequest) (*RawData, error)
	mustEmbedUnimplementedMarketServiceServer()
}

// UnimplementedMarketServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMarketServiceServer struct{}

func (UnimplementedMarketServiceServer) GetPayWay(context.Context, *GetPayWayRequest) (*GetPayWayReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPayWay not implemented")
}
func (UnimplementedMarketServiceServer) CheckExchange(context.Context, *CheckExchangeRequest) (*CheckExchangeReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckExchange not implemented")
}
func (UnimplementedMarketServiceServer) PurchaseIndex(context.Context, *PurchaseIndexRequest) (*RawData, error) {
	return nil, status.Error(codes.Unimplemented, "method PurchaseIndex not implemented")
}
func (UnimplementedMarketServiceServer) GetSaleCategories(context.Context, *GetSaleCategoriesRequest) (*GetSaleCategoriesReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSaleCategories not implemented")
}
func (UnimplementedMarketServiceServer) SaleIndex(context.Context, *SaleIndexRequest) (*RawData, error) {
	return nil, status.Error(codes.Unimplemented, "method SaleIndex not implemented")
}
func (UnimplementedMarketServiceServer) StockLookAll(context.Context, *StockLookAllRequest) (*StockLookAllReply, error) {
	return nil, status.Error(codes.Unimplemented, "method StockLookAll not implemented")
}
func (UnimplementedMarketServiceServer) PurchaseInfo(context.Context, *PurchaseInfoRequest) (*PurchaseInfoReply, error) {
	return nil, status.Error(codes.Unimplemented, "method PurchaseInfo not implemented")
}
func (UnimplementedMarketServiceServer) SaleInfo(context.Context, *SaleInfoRequest) (*SaleInfoReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SaleInfo not implemented")
}
func (UnimplementedMarketServiceServer) ShowTotalAmount(context.Context, *ShowTotalAmountRequest) (*ShowTotalAmountReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ShowTotalAmount not implemented")
}
func (UnimplementedMarketServiceServer) PurchaseOut(context.Context, *PurchaseOutRequest) (*RawData, error) {
	return nil, status.Error(codes.Unimplemented, "method PurchaseOut not implemented")
}
func (UnimplementedMarketServiceServer) PurchaseOn(context.Context, *PurchaseOnRequest) (*RawData, error) {
	return nil, status.Error(codes.Unimplemented, "method PurchaseOn not implemented")
}
func (UnimplementedMarketServiceServer) mustEmbedUnimplementedMarketServiceServer() {}
func (UnimplementedMarketServiceServer) testEmbeddedByValue()                       {}

// UnsafeMarketServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarketServiceServer will
// result in compilation errors.
type UnsafeMarketServiceServer interface {
	mustEmbedUnimplementedMarketServiceServer()
}

func RegisterMarketServiceServer(s grpc.ServiceRegistrar, srv MarketServiceServer) {
	// If the following call panics, it indicates UnimplementedMarketServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MarketService_ServiceDesc, srv)
}

func _MarketService_GetPayWay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPayWayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).GetPayWay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketService_GetPayWay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).GetPayWay(ctx, req.(*GetPayWayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_CheckExchange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckExchangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).CheckExchange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketService_CheckExchange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).CheckExchange(ctx, req.(*CheckExchangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_PurchaseIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurchaseIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).PurchaseIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketService_PurchaseIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).PurchaseIndex(ctx, req.(*PurchaseIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_GetSaleCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSaleCategoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).GetSaleCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketService_GetSaleCategories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).GetSaleCategories(ctx, req.(*GetSaleCategoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_SaleIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaleIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).SaleIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketService_SaleIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).SaleIndex(ctx, req.(*SaleIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_StockLookAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StockLookAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).StockLookAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketService_StockLookAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).StockLookAll(ctx, req.(*StockLookAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_PurchaseInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurchaseInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).PurchaseInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketService_PurchaseInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).PurchaseInfo(ctx, req.(*PurchaseInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_SaleInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaleInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).SaleInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketService_SaleInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).SaleInfo(ctx, req.(*SaleInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_ShowTotalAmount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShowTotalAmountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).ShowTotalAmount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketService_ShowTotalAmount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).ShowTotalAmount(ctx, req.(*ShowTotalAmountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_PurchaseOut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurchaseOutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).PurchaseOut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketService_PurchaseOut_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).PurchaseOut(ctx, req.(*PurchaseOutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_PurchaseOn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurchaseOnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).PurchaseOn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketService_PurchaseOn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).PurchaseOn(ctx, req.(*PurchaseOnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MarketService_ServiceDesc is the grpc.ServiceDesc for MarketService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MarketService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xtravel.v1.MarketService",
	HandlerType: (*MarketServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPayWay",
			Handler:    _MarketService_GetPayWay_Handler,
		},
		{
			MethodName: "CheckExchange",
			Handler:    _MarketService_CheckExchange_Handler,
		},
		{
			MethodName: "PurchaseIndex",
			Handler:    _MarketService_PurchaseIndex_Handler,
		},
		{
			MethodName: "GetSaleCategories",
			Handler:    _MarketService_GetSaleCategories_Handler,
		},
		{
			MethodName: "SaleIndex",
			Handler:    _MarketService_SaleIndex_Handler,
		},
		{
			MethodName: "StockLookAll",
			Handler:    _MarketService_StockLookAll_Handler,
		},
		{
			MethodName: "PurchaseInfo",
			Handler:    _MarketService_PurchaseInfo_Handler,
		},
		{
			MethodName: "SaleInfo",
			Handler:    _MarketService_SaleInfo_Handler,
		},
		{
			MethodName: "ShowTotalAmount",
			Handler:    _MarketService_ShowTotalAmount_Handler,
		},
		{
			MethodName: "PurchaseOut",
			Handler:    _MarketService_PurchaseOut_Handler,
		},
		{
			MethodName: "PurchaseOn",
			Handler:    _MarketService_PurchaseOn_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/xtravel/v1/market.proto",
}
