// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.35.1
// source: api/xtravel/v1/market.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationMarketServiceCheckExchange = "/xtravel.v1.MarketService/CheckExchange"
const OperationMarketServiceGetPayWay = "/xtravel.v1.MarketService/GetPayWay"
const OperationMarketServiceGetSaleCategories = "/xtravel.v1.MarketService/GetSaleCategories"
const OperationMarketServicePurchaseIndex = "/xtravel.v1.MarketService/PurchaseIndex"
const OperationMarketServiceSaleIndex = "/xtravel.v1.MarketService/SaleIndex"

type MarketServiceHTTPServer interface {
	// CheckExchange 兑换前置校验
	// 原: PurchaseController::checkExchange -> GoodsLogic::checkExchange
	//     （需要登录；会加 2 秒防重复点击锁并查一次兑换单数量）
	CheckExchange(context.Context, *CheckExchangeRequest) (*CheckExchangeReply, error)
	// GetPayWay 支付方式列表
	// 原: PurchaseController::payWay（硬编码，不查库；需要登录）
	GetPayWay(context.Context, *GetPayWayRequest) (*GetPayWayReply, error)
	// GetSaleCategories 秒转专区分类列表
	// 原: SaleController::categories —— **硬编码**，不查库；是 SaleController 里
	//     唯一免登录的方法（$notNeedLogin = ['categories']）
	GetSaleCategories(context.Context, *GetSaleCategoriesRequest) (*GetSaleCategoriesReply, error)
	// PurchaseIndex 兑换专区首页列表
	// 原: PurchaseController::index -> PurchaseFaceLists
	//     **免登录**（控制器 $notNeedLogin 放行了 index）
	//     挂白名单 no_collection_trade
	//     走交易时段判断；带 20 秒整包缓存
	//
	// 返回 RawData：列表行结构任意（bigint 主键 / decimal 字符串 / json 数组 /
	// "0 转 --" 后处理），用 proto 建模会丢精度又拧巴，见 common.proto 的说明。
	PurchaseIndex(context.Context, *PurchaseIndexRequest) (*RawData, error)
	// SaleIndex 秒转专区首页列表
	// 原: SaleController::index -> SaleFaceLists
	//     **需要登录**（不在 $notNeedLogin 里）
	//
	// ⚠️ 与 purchase 列表的两个差异（都是实测出来的）：
	//   1. 该接口没有默认排序 —— PurchaseFaceLists 的 switch 有 default 分支，
	//      SaleFaceLists 没有，所以**不带 sort 参数时 SQL 里根本没有 ORDER BY**
	//   2. 行后处理只做 images 的 json 解码，没有 "0 转 --" 那套
	SaleIndex(context.Context, *SaleIndexRequest) (*RawData, error)
}

func RegisterMarketServiceHTTPServer(s *http.Server, srv MarketServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/market/pay_way", _MarketService_GetPayWay0_HTTP_Handler(srv))
	r.GET("/v1/market/check/exchange", _MarketService_CheckExchange0_HTTP_Handler(srv))
	r.GET("/v1/market/purchase", _MarketService_PurchaseIndex0_HTTP_Handler(srv))
	r.GET("/v1/market/sales/categories", _MarketService_GetSaleCategories0_HTTP_Handler(srv))
	r.GET("/v1/market/sales", _MarketService_SaleIndex0_HTTP_Handler(srv))
}

func _MarketService_GetPayWay0_HTTP_Handler(srv MarketServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetPayWayRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketServiceGetPayWay)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetPayWay(ctx, req.(*GetPayWayRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetPayWayReply)
		return ctx.Result(200, reply)
	}
}

func _MarketService_CheckExchange0_HTTP_Handler(srv MarketServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CheckExchangeRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketServiceCheckExchange)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CheckExchange(ctx, req.(*CheckExchangeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CheckExchangeReply)
		return ctx.Result(200, reply)
	}
}

func _MarketService_PurchaseIndex0_HTTP_Handler(srv MarketServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PurchaseIndexRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketServicePurchaseIndex)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PurchaseIndex(ctx, req.(*PurchaseIndexRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RawData)
		return ctx.Result(200, reply)
	}
}

func _MarketService_GetSaleCategories0_HTTP_Handler(srv MarketServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetSaleCategoriesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketServiceGetSaleCategories)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetSaleCategories(ctx, req.(*GetSaleCategoriesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetSaleCategoriesReply)
		return ctx.Result(200, reply)
	}
}

func _MarketService_SaleIndex0_HTTP_Handler(srv MarketServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SaleIndexRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketServiceSaleIndex)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SaleIndex(ctx, req.(*SaleIndexRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RawData)
		return ctx.Result(200, reply)
	}
}

type MarketServiceHTTPClient interface {
	// CheckExchange 兑换前置校验
	// 原: PurchaseController::checkExchange -> GoodsLogic::checkExchange
	//     （需要登录；会加 2 秒防重复点击锁并查一次兑换单数量）
	CheckExchange(ctx context.Context, req *CheckExchangeRequest, opts ...http.CallOption) (rsp *CheckExchangeReply, err error)
	// GetPayWay 支付方式列表
	// 原: PurchaseController::payWay（硬编码，不查库；需要登录）
	GetPayWay(ctx context.Context, req *GetPayWayRequest, opts ...http.CallOption) (rsp *GetPayWayReply, err error)
	// GetSaleCategories 秒转专区分类列表
	// 原: SaleController::categories —— **硬编码**，不查库；是 SaleController 里
	//     唯一免登录的方法（$notNeedLogin = ['categories']）
	GetSaleCategories(ctx context.Context, req *GetSaleCategoriesRequest, opts ...http.CallOption) (rsp *GetSaleCategoriesReply, err error)
	// PurchaseIndex 兑换专区首页列表
	// 原: PurchaseController::index -> PurchaseFaceLists
	//     **免登录**（控制器 $notNeedLogin 放行了 index）
	//     挂白名单 no_collection_trade
	//     走交易时段判断；带 20 秒整包缓存
	//
	// 返回 RawData：列表行结构任意（bigint 主键 / decimal 字符串 / json 数组 /
	// "0 转 --" 后处理），用 proto 建模会丢精度又拧巴，见 common.proto 的说明。
	PurchaseIndex(ctx context.Context, req *PurchaseIndexRequest, opts ...http.CallOption) (rsp *RawData, err error)
	// SaleIndex 秒转专区首页列表
	// 原: SaleController::index -> SaleFaceLists
	//     **需要登录**（不在 $notNeedLogin 里）
	//
	// ⚠️ 与 purchase 列表的两个差异（都是实测出来的）：
	//   1. 该接口没有默认排序 —— PurchaseFaceLists 的 switch 有 default 分支，
	//      SaleFaceLists 没有，所以**不带 sort 参数时 SQL 里根本没有 ORDER BY**
	//   2. 行后处理只做 images 的 json 解码，没有 "0 转 --" 那套
	SaleIndex(ctx context.Context, req *SaleIndexRequest, opts ...http.CallOption) (rsp *RawData, err error)
}

type MarketServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewMarketServiceHTTPClient(client *http.Client) MarketServiceHTTPClient {
	return &MarketServiceHTTPClientImpl{client}
}

// CheckExchange 兑换前置校验
// 原: PurchaseController::checkExchange -> GoodsLogic::checkExchange
//
//	（需要登录；会加 2 秒防重复点击锁并查一次兑换单数量）
func (c *MarketServiceHTTPClientImpl) CheckExchange(ctx context.Context, in *CheckExchangeRequest, opts ...http.CallOption) (*CheckExchangeReply, error) {
	var out CheckExchangeReply
	pattern := "/v1/market/check/exchange"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMarketServiceCheckExchange))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetPayWay 支付方式列表
// 原: PurchaseController::payWay（硬编码，不查库；需要登录）
func (c *MarketServiceHTTPClientImpl) GetPayWay(ctx context.Context, in *GetPayWayRequest, opts ...http.CallOption) (*GetPayWayReply, error) {
	var out GetPayWayReply
	pattern := "/v1/market/pay_way"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMarketServiceGetPayWay))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetSaleCategories 秒转专区分类列表
// 原: SaleController::categories —— **硬编码**，不查库；是 SaleController 里
//
//	唯一免登录的方法（$notNeedLogin = ['categories']）
func (c *MarketServiceHTTPClientImpl) GetSaleCategories(ctx context.Context, in *GetSaleCategoriesRequest, opts ...http.CallOption) (*GetSaleCategoriesReply, error) {
	var out GetSaleCategoriesReply
	pattern := "/v1/market/sales/categories"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMarketServiceGetSaleCategories))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// PurchaseIndex 兑换专区首页列表
// 原: PurchaseController::index -> PurchaseFaceLists
//
//	**免登录**（控制器 $notNeedLogin 放行了 index）
//	挂白名单 no_collection_trade
//	走交易时段判断；带 20 秒整包缓存
//
// 返回 RawData：列表行结构任意（bigint 主键 / decimal 字符串 / json 数组 /
// "0 转 --" 后处理），用 proto 建模会丢精度又拧巴，见 common.proto 的说明。
func (c *MarketServiceHTTPClientImpl) PurchaseIndex(ctx context.Context, in *PurchaseIndexRequest, opts ...http.CallOption) (*RawData, error) {
	var out RawData
	pattern := "/v1/market/purchase"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMarketServicePurchaseIndex))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SaleIndex 秒转专区首页列表
// 原: SaleController::index -> SaleFaceLists
//
//	**需要登录**（不在 $notNeedLogin 里）
//
// ⚠️ 与 purchase 列表的两个差异（都是实测出来的）：
//  1. 该接口没有默认排序 —— PurchaseFaceLists 的 switch 有 default 分支，
//     SaleFaceLists 没有，所以**不带 sort 参数时 SQL 里根本没有 ORDER BY**
//  2. 行后处理只做 images 的 json 解码，没有 "0 转 --" 那套
func (c *MarketServiceHTTPClientImpl) SaleIndex(ctx context.Context, in *SaleIndexRequest, opts ...http.CallOption) (*RawData, error) {
	var out RawData
	pattern := "/v1/market/sales"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMarketServiceSaleIndex))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
