// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/xtravel/v1/market.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StockLookAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockLookAllRequest) Reset() {
	*x = StockLookAllRequest{}
	mi := &file_api_xtravel_v1_market_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockLookAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockLookAllRequest) ProtoMessage() {}

func (x *StockLookAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_xtravel_v1_market_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockLookAllRequest.ProtoReflect.Descriptor instead.
func (*StockLookAllRequest) Descriptor() ([]byte, []int) {
	return file_api_xtravel_v1_market_proto_rawDescGZIP(), []int{0}
}

type StockLookAllReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 1 正常；0 表示有释放任务正在处理中（迁移期恒为 1，见上面的说明）
	State         int32 `protobuf:"varint,1,opt,name=state,proto3" json:"state,omitempty"`
	Num           int64 `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockLookAllReply) Reset() {
	*x = StockLookAllReply{}
	mi := &file_api_xtravel_v1_market_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockLookAllReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockLookAllReply) ProtoMessage() {}

func (x *StockLookAllReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_xtravel_v1_market_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockLookAllReply.ProtoReflect.Descriptor instead.
func (*StockLookAllReply) Descriptor() ([]byte, []int) {
	return file_api_xtravel_v1_market_proto_rawDescGZIP(), []int{1}
}

func (x *StockLookAllReply) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *StockLookAllReply) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

type PurchaseIndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchaseIndexRequest) Reset() {
	*x = PurchaseIndexRequest{}
	mi := &file_api_xtravel_v1_market_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseIndexRequest) ProtoMessage() {}

func (x *PurchaseIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_xtravel_v1_market_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseIndexRequest.ProtoReflect.Descriptor instead.
func (*PurchaseIndexRequest) Descriptor() ([]byte, []int) {
	return file_api_xtravel_v1_market_proto_rawDescGZIP(), []int{2}
}

type GetSaleCategoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSaleCategoriesRequest) Reset() {
	*x = GetSaleCategoriesRequest{}
	mi := &file_api_xtravel_v1_market_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSaleCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSaleCategoriesRequest) ProtoMessage() {}

func (x *GetSaleCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_xtravel_v1_market_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSaleCategoriesRequest.ProtoReflect.Descriptor instead.
func (*GetSaleCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_api_xtravel_v1_market_proto_rawDescGZIP(), []int{3}
}

type GetSaleCategoriesReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 原接口 data 是顶层数组：[{"title":"全部","key":"all"}]
	Items         []*SaleCategory `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSaleCategoriesReply) Reset() {
	*x = GetSaleCategoriesReply{}
	mi := &file_api_xtravel_v1_market_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSaleCategoriesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSaleCategoriesReply) ProtoMessage() {}

func (x *GetSaleCategoriesReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_xtravel_v1_market_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSaleCategoriesReply.ProtoReflect.Descriptor instead.
func (*GetSaleCategoriesReply) Descriptor() ([]byte, []int) {
	return file_api_xtravel_v1_market_proto_rawDescGZIP(), []int{4}
}

func (x *GetSaleCategoriesReply) GetItems() []*SaleCategory {
	if x != nil {
		return x.Items
	}
	return nil
}

type SaleCategory struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Title string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	// key 是 PHP 数组里的字面键名，输出就是 "key"
	Key           string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaleCategory) Reset() {
	*x = SaleCategory{}
	mi := &file_api_xtravel_v1_market_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaleCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaleCategory) ProtoMessage() {}

func (x *SaleCategory) ProtoReflect() protoreflect.Message {
	mi := &file_api_xtravel_v1_market_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaleCategory.ProtoReflect.Descriptor instead.
func (*SaleCategory) Descriptor() ([]byte, []int) {
	return file_api_xtravel_v1_market_proto_rawDescGZIP(), []int{5}
}

func (x *SaleCategory) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SaleCategory) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type SaleIndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaleIndexRequest) Reset() {
	*x = SaleIndexRequest{}
	mi := &file_api_xtravel_v1_market_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaleIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaleIndexRequest) ProtoMessage() {}

func (x *SaleIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_xtravel_v1_market_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaleIndexRequest.ProtoReflect.Descriptor instead.
func (*SaleIndexRequest) Descriptor() ([]byte, []int) {
	return file_api_xtravel_v1_market_proto_rawDescGZIP(), []int{6}
}

type GetPayWayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPayWayRequest) Reset() {
	*x = GetPayWayRequest{}
	mi := &file_api_xtravel_v1_market_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPayWayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPayWayRequest) ProtoMessage() {}

func (x *GetPayWayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_xtravel_v1_market_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPayWayRequest.ProtoReflect.Descriptor instead.
func (*GetPayWayRequest) Descriptor() ([]byte, []int) {
	return file_api_xtravel_v1_market_proto_rawDescGZIP(), []int{7}
}

type GetPayWayReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ⚠️ 原接口的 data 是**顶层数组**而不是对象：
	//
	//	{"code":1,"show":0,"msg":"","data":[{"pay_way":1,...}]}
	//	Kratos 的 reply 是 message，默认会被包成 {"data":{"items":[...]}}。
	//	所以这里靠 api/xtravel/v1/envelope.go 里的 Envelope() 把 items 摊出去。
	Items         []*PayWay `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPayWayReply) Reset() {
	*x = GetPayWayReply{}
	mi := &file_api_xtravel_v1_market_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPayWayReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPayWayReply) ProtoMessage() {}

func (x *GetPayWayReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_xtravel_v1_market_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPayWayReply.ProtoReflect.Descriptor instead.
func (*GetPayWayReply) Descriptor() ([]byte, []int) {
	return file_api_xtravel_v1_market_proto_rawDescGZIP(), []int{8}
}

func (x *GetPayWayReply) GetItems() []*PayWay {
	if x != nil {
		return x.Items
	}
	return nil
}

type PayWay struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 原 PHP 是硬编码数组 ['pay_way' => 1, 'pay_name' => '茶交所']，
	// json_encode 出来就是下划线键名。必须显式指定 json_name，
	// 否则 protojson 会输出 payWay / payName，前端取不到字段。
	PayWay        int32  `protobuf:"varint,1,opt,name=pay_way,proto3" json:"pay_way,omitempty"`
	PayName       string `protobuf:"bytes,2,opt,name=pay_name,proto3" json:"pay_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayWay) Reset() {
	*x = PayWay{}
	mi := &file_api_xtravel_v1_market_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayWay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayWay) ProtoMessage() {}

func (x *PayWay) ProtoReflect() protoreflect.Message {
	mi := &file_api_xtravel_v1_market_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayWay.ProtoReflect.Descriptor instead.
func (*PayWay) Descriptor() ([]byte, []int) {
	return file_api_xtravel_v1_market_proto_rawDescGZIP(), []int{9}
}

func (x *PayWay) GetPayWay() int32 {
	if x != nil {
		return x.PayWay
	}
	return 0
}

func (x *PayWay) GetPayName() string {
	if x != nil {
		return x.PayName
	}
	return ""
}

type CheckExchangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckExchangeRequest) Reset() {
	*x = CheckExchangeRequest{}
	mi := &file_api_xtravel_v1_market_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckExchangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckExchangeRequest) ProtoMessage() {}

func (x *CheckExchangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_xtravel_v1_market_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckExchangeRequest.ProtoReflect.Descriptor instead.
func (*CheckExchangeRequest) Descriptor() ([]byte, []int) {
	return file_api_xtravel_v1_market_proto_rawDescGZIP(), []int{10}
}

// 成功时原接口返回的是**空数组** []（`return $this->data([])`），
// 不是空对象 {}。同样由 Envelope() 处理。
type CheckExchangeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckExchangeReply) Reset() {
	*x = CheckExchangeReply{}
	mi := &file_api_xtravel_v1_market_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckExchangeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckExchangeReply) ProtoMessage() {}

func (x *CheckExchangeReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_xtravel_v1_market_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckExchangeReply.ProtoReflect.Descriptor instead.
func (*CheckExchangeReply) Descriptor() ([]byte, []int) {
	return file_api_xtravel_v1_market_proto_rawDescGZIP(), []int{11}
}

var File_api_xtravel_v1_market_proto protoreflect.FileDescriptor

const file_api_xtravel_v1_market_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/xtravel/v1/market.proto\x12\n" +
	"xtravel.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bapi/xtravel/v1/common.proto\"\x15\n" +
	"\x13StockLookAllRequest\";\n" +
	"\x11StockLookAllReply\x12\x14\n" +
	"\x05state\x18\x01 \x01(\x05R\x05state\x12\x10\n" +
	"\x03num\x18\x02 \x01(\x03R\x03num\"\x16\n" +
	"\x14PurchaseIndexRequest\"\x1a\n" +
	"\x18GetSaleCategoriesRequest\"H\n" +
	"\x16GetSaleCategoriesReply\x12.\n" +
	"\x05items\x18\x01 \x03(\v2\x18.xtravel.v1.SaleCategoryR\x05items\"6\n" +
	"\fSaleCategory\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"\x12\n" +
	"\x10SaleIndexRequest\"\x12\n" +
	"\x10GetPayWayRequest\":\n" +
	"\x0eGetPayWayReply\x12(\n" +
	"\x05items\x18\x01 \x03(\v2\x12.xtravel.v1.PayWayR\x05items\">\n" +
	"\x06PayWay\x12\x18\n" +
	"\apay_way\x18\x01 \x01(\x05R\apay_way\x12\x1a\n" +
	"\bpay_name\x18\x02 \x01(\tR\bpay_name\"\x16\n" +
	"\x14CheckExchangeRequest\"\x14\n" +
	"\x12CheckExchangeReply2\x9e\x05\n" +
	"\rMarketService\x12a\n" +
	"\tGetPayWay\x12\x1c.xtravel.v1.GetPayWayRequest\x1a\x1a.xtravel.v1.GetPayWayReply\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/market/pay_way\x12t\n" +
	"\rCheckExchange\x12 .xtravel.v1.CheckExchangeRequest\x1a\x1e.xtravel.v1.CheckExchangeReply\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/market/check/exchange\x12c\n" +
	"\rPurchaseIndex\x12 .xtravel.v1.PurchaseIndexRequest\x1a\x13.xtravel.v1.RawData\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/market/purchase\x12\x82\x01\n" +
	"\x11GetSaleCategories\x12$.xtravel.v1.GetSaleCategoriesRequest\x1a\".xtravel.v1.GetSaleCategoriesReply\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v1/market/sales/categories\x12X\n" +
	"\tSaleIndex\x12\x1c.xtravel.v1.SaleIndexRequest\x1a\x13.xtravel.v1.RawData\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/market/sales\x12p\n" +
	"\fStockLookAll\x12\x1f.xtravel.v1.StockLookAllRequest\x1a\x1d.xtravel.v1.StockLookAllReply\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/market/stock/lookallB2Z0github.com/lixiaoping4258/ymkj/api/xtravel/v1;v1b\x06proto3"

var (
	file_api_xtravel_v1_market_proto_rawDescOnce sync.Once
	file_api_xtravel_v1_market_proto_rawDescData []byte
)

func file_api_xtravel_v1_market_proto_rawDescGZIP() []byte {
	file_api_xtravel_v1_market_proto_rawDescOnce.Do(func() {
		file_api_xtravel_v1_market_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_xtravel_v1_market_proto_rawDesc), len(file_api_xtravel_v1_market_proto_rawDesc)))
	})
	return file_api_xtravel_v1_market_proto_rawDescData
}

var file_api_xtravel_v1_market_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_xtravel_v1_market_proto_goTypes = []any{
	(*StockLookAllRequest)(nil),      // 0: xtravel.v1.StockLookAllRequest
	(*StockLookAllReply)(nil),        // 1: xtravel.v1.StockLookAllReply
	(*PurchaseIndexRequest)(nil),     // 2: xtravel.v1.PurchaseIndexRequest
	(*GetSaleCategoriesRequest)(nil), // 3: xtravel.v1.GetSaleCategoriesRequest
	(*GetSaleCategoriesReply)(nil),   // 4: xtravel.v1.GetSaleCategoriesReply
	(*SaleCategory)(nil),             // 5: xtravel.v1.SaleCategory
	(*SaleIndexRequest)(nil),         // 6: xtravel.v1.SaleIndexRequest
	(*GetPayWayRequest)(nil),         // 7: xtravel.v1.GetPayWayRequest
	(*GetPayWayReply)(nil),           // 8: xtravel.v1.GetPayWayReply
	(*PayWay)(nil),                   // 9: xtravel.v1.PayWay
	(*CheckExchangeRequest)(nil),     // 10: xtravel.v1.CheckExchangeRequest
	(*CheckExchangeReply)(nil),       // 11: xtravel.v1.CheckExchangeReply
	(*RawData)(nil),                  // 12: xtravel.v1.RawData
}
var file_api_xtravel_v1_market_proto_depIdxs = []int32{
	5,  // 0: xtravel.v1.GetSaleCategoriesReply.items:type_name -> xtravel.v1.SaleCategory
	9,  // 1: xtravel.v1.GetPayWayReply.items:type_name -> xtravel.v1.PayWay
	7,  // 2: xtravel.v1.MarketService.GetPayWay:input_type -> xtravel.v1.GetPayWayRequest
	10, // 3: xtravel.v1.MarketService.CheckExchange:input_type -> xtravel.v1.CheckExchangeRequest
	2,  // 4: xtravel.v1.MarketService.PurchaseIndex:input_type -> xtravel.v1.PurchaseIndexRequest
	3,  // 5: xtravel.v1.MarketService.GetSaleCategories:input_type -> xtravel.v1.GetSaleCategoriesRequest
	6,  // 6: xtravel.v1.MarketService.SaleIndex:input_type -> xtravel.v1.SaleIndexRequest
	0,  // 7: xtravel.v1.MarketService.StockLookAll:input_type -> xtravel.v1.StockLookAllRequest
	8,  // 8: xtravel.v1.MarketService.GetPayWay:output_type -> xtravel.v1.GetPayWayReply
	11, // 9: xtravel.v1.MarketService.CheckExchange:output_type -> xtravel.v1.CheckExchangeReply
	12, // 10: xtravel.v1.MarketService.PurchaseIndex:output_type -> xtravel.v1.RawData
	4,  // 11: xtravel.v1.MarketService.GetSaleCategories:output_type -> xtravel.v1.GetSaleCategoriesReply
	12, // 12: xtravel.v1.MarketService.SaleIndex:output_type -> xtravel.v1.RawData
	1,  // 13: xtravel.v1.MarketService.StockLookAll:output_type -> xtravel.v1.StockLookAllReply
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_api_xtravel_v1_market_proto_init() }
func file_api_xtravel_v1_market_proto_init() {
	if File_api_xtravel_v1_market_proto != nil {
		return
	}
	file_api_xtravel_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_xtravel_v1_market_proto_rawDesc), len(file_api_xtravel_v1_market_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_xtravel_v1_market_proto_goTypes,
		DependencyIndexes: file_api_xtravel_v1_market_proto_depIdxs,
		MessageInfos:      file_api_xtravel_v1_market_proto_msgTypes,
	}.Build()
	File_api_xtravel_v1_market_proto = out.File
	file_api_xtravel_v1_market_proto_goTypes = nil
	file_api_xtravel_v1_market_proto_depIdxs = nil
}
