// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/lixiaoping4258/ymkj/internal/biz"
	"github.com/lixiaoping4258/ymkj/internal/conf"
	"github.com/lixiaoping4258/ymkj/internal/data"
	"github.com/lixiaoping4258/ymkj/internal/server"
	"github.com/lixiaoping4258/ymkj/internal/service"
)

import (
	_ "github.com/go-kratos/kratos/v2/encoding/json"
	_ "github.com/go-kratos/kratos/v2/encoding/yaml"
)

// Injectors from wire.go:

// wireApp 由 wire 生成实现。
//
// 依赖装配顺序：conf -> data(DB/Redis/Repo) -> biz(Usecase) -> service -> server -> App
// 对应原项目里那些 static 单例和 think 容器的自动解析，但这里是编译期确定的，
// 少一个依赖会直接编译不过，而不是运行时报错。
func wireApp(confServer *conf.Server, confData *conf.Data, app *conf.App, confLog *conf.Log, auth *conf.Auth, logger log.Logger) (*kratos.App, func(), error) {
	db, cleanup, err := data.NewDB(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	configRepo := data.NewConfigRepo(db)
	projectConfig := data.NewProjectConfig(logger)
	configUsecase := biz.NewConfigUsecase(configRepo, projectConfig, logger)
	client, cleanup2, err := data.NewRedis(confData, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	cache := data.NewRedisCache(client)
	tradeCalendarRepo := data.NewTradeCalendarRepo(db)
	location := data.NewLocation(app, logger)
	tradeConfigUsecase := biz.NewTradeConfigUsecase(configUsecase, cache, tradeCalendarRepo, location, logger)
	commonService := service.NewCommonService(configUsecase, tradeConfigUsecase)
	userRepo := data.NewUserRepo(db)
	userUsecase := biz.NewUserUsecase(userRepo, cache, logger)
	userService := service.NewUserService(userUsecase)
	marketPurchaseRepo := data.NewMarketPurchaseRepo(db)
	locker := data.NewRedisLocker(client)
	marketUsecase := biz.NewMarketUsecase(marketPurchaseRepo, tradeConfigUsecase, locker, logger)
	purchaseFaceRepo := data.NewPurchaseFaceRepo(db, confData)
	appFlags := data.NewAppFlags(app)
	purchaseFaceUsecase := biz.NewPurchaseFaceUsecase(purchaseFaceRepo, tradeConfigUsecase, cache, appFlags, logger)
	saleFaceRepo := data.NewSaleFaceRepo(db, confData)
	saleFaceUsecase := biz.NewSaleFaceUsecase(saleFaceRepo, logger)
	stockRepo := data.NewStockRepo(db)
	stockUsecase := biz.NewStockUsecase(stockRepo, cache, logger)
	archiveRepo := data.NewArchiveRepo(db, confData)
	rawCache := data.NewRawRedisCache(client)
	archiveUsecase := biz.NewArchiveUsecase(archiveRepo, rawCache, cache, logger)
	feeUsecase := biz.NewFeeUsecase(configUsecase, cache, app, logger)
	purchaseStateRepo := data.NewPurchaseStateRepo(db, confData, client, app)
	purchaseStateUsecase := biz.NewPurchaseStateUsecase(purchaseStateRepo, logger)
	rawKeyCache := data.NewRawCache(client)
	staleCache := biz.NewStaleCache(rawKeyCache, locker, logger)
	marketService := service.NewMarketService(marketUsecase, purchaseFaceUsecase, saleFaceUsecase, stockUsecase, archiveUsecase, feeUsecase, purchaseStateUsecase, rawKeyCache, staleCache, logger)
	idGenerator := data.NewIDGenerator(client)
	loginRepo := data.NewLoginRepo(db, confData, idGenerator, auth)
	userSessionRepo := data.NewUserSessionRepo(db)
	authConfig := data.NewAuthConfig(auth, logger)
	userTokenCache := data.NewUserTokenCache(client, authConfig)
	userTokenUsecase := biz.NewUserTokenUsecase(userSessionRepo, userRepo, userTokenCache, authConfig, logger)
	loginUsecase := biz.NewLoginUsecase(loginRepo, userTokenUsecase, idGenerator, logger)
	passwordRepo := data.NewPasswordRepo(db, confData)
	redisClient := data.NewRawRedis(client)
	captchaRepo := data.NewCaptchaRepo(confData, redisClient)
	safeCacheRepo := data.NewSafeCache(confData, redisClient)
	smsRepo := data.NewSmsRepo(db, confData)
	smsUsecase := biz.NewSmsUsecase(smsRepo, app)
	loginValidator := biz.NewLoginValidator(passwordRepo, captchaRepo, safeCacheRepo, auth, smsUsecase)
	captchaUsecase := biz.NewCaptchaUsecase(captchaRepo)
	accountService := service.NewAccountService(loginUsecase, loginValidator, captchaUsecase, logger)
	articleRepo := data.NewArticleRepo(db, confData)
	articleUsecase := biz.NewArticleUsecase(articleRepo)
	articleService := service.NewArticleService(articleUsecase)
	whitelistRepo := data.NewWhitelistRepo(db)
	whitelistUsecase := biz.NewWhitelistUsecase(whitelistRepo, cache, logger)
	httpServer := server.NewHTTPServer(confServer, auth, commonService, userService, marketService, accountService, articleService, userTokenUsecase, whitelistUsecase, logger)
	kratosApp := newApp(logger, httpServer)
	return kratosApp, func() {
		cleanup2()
		cleanup()
	}, nil
}
