# Generate configs/config.local.yaml from the xTravel .env file.
#
# Why this exists: doing it by hand bit us twice.
#   1. PowerShell treats `?` as a legal variable-name character, so
#      "$db?charset=..." silently expands an UNDEFINED variable named
#      "db?charset" to an empty string, and the DSN loses the db name.
#      Always write ${db}?charset= with braces.
#   2. PowerShell 5.1's `Set-Content -Encoding utf8` writes a BOM, which
#      makes the YAML parser choke. We use [IO.File]::WriteAllText with
#      UTF8Encoding($false) instead.
#
# Writes config.local.yaml which is gitignored. Never commit its contents.
#
# Usage:
#   pwsh -File .\scripts\gen-config.ps1
#   pwsh -File .\scripts\gen-config.ps1 -XTravelRoot D:\path\to\xTravel

param(
    [string]$XTravelRoot = 'D:\work\phpstudy_pro\WWW\xTravel',
    [string]$OutFile,
    [int]$Port = 18000
)

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
Set-Location $root
if (-not $OutFile) { $OutFile = Join-Path $root 'configs\config.local.yaml' }

$envPath = Join-Path $XTravelRoot '.env'
if (-not (Test-Path $envPath)) { throw "not found: $envPath" }

# --- parse the ThinkPHP .env (it is section based: [DATABASE] KEY = "value") ---
$env2 = @{}
$section = ''
foreach ($raw in Get-Content $envPath) {
    $line = $raw.Trim()
    if ($line -match '^\[(.+)\]$') { $section = $Matches[1].ToLower(); continue }
    if ($line -match '^#') { continue }
    if ($line -match '^([A-Za-z0-9_]+)\s*=\s*(.*)$') {
        $k = $Matches[1].ToLower()
        $v = $Matches[2].Trim().Trim('"')
        $env2["$section.$k"] = $v
        # Keys appearing before any [SECTION] header (APP_DEBUG, APP_TRACE...)
        # land under a leading dot; also index them bare.
        if ($section -eq '') { $env2[$k] = $v }
    }
}

# APP_DEBUG is not just a debug switch here: PurchaseController::index and
# PurchaseFaceLists::queryWhere both branch on it, and the "prod test user"
# path skips the trading-hours check AND drops the AppArchive.state filter.
$appDebugRaw = $env2['app_debug']
if (-not $appDebugRaw) { $appDebugRaw = $env2['.app_debug'] }
$appDebug = 'false'
if ("$appDebugRaw".ToLower() -in @('1', 'true', 'yes', 'on')) { $appDebug = 'true' }

function Need($key) {
    if (-not $env2.ContainsKey($key) -or [string]::IsNullOrWhiteSpace($env2[$key])) {
        throw "missing key in .env: $key"
    }
    return $env2[$key]
}

$dbHost = Need 'database.hostname'
$dbPort = Need 'database.hostport'
$dbName = Need 'database.database'
$dbUser = Need 'database.username'
$dbPass = Need 'database.password'
$dbPrefix = $env2['database.prefix']
if (-not $dbPrefix) { $dbPrefix = 'la_' }
$dbCharset = $env2['database.charset']
if (-not $dbCharset) { $dbCharset = 'utf8mb4' }

$rHost = Need 'redis.host'
$rPort = $env2['redis.port']; if (-not $rPort) { $rPort = '6379' }
$rPass = $env2['redis.password']
$rSel = $env2['redis.select']; if (-not $rSel) { $rSel = '0' }

$tz = $env2['app.default_timezone']; if (-not $tz) { $tz = 'Asia/Shanghai' }
$uniq = $env2['project.unique_identification']; if (-not $uniq) { $uniq = 'likeadmin' }

# --- DSN: braces are NOT optional here, see the header comment ---
$dsn = "${dbUser}:${dbPass}@tcp(${dbHost}:${dbPort})/${dbName}?charset=${dbCharset}&parseTime=True&loc=Asia%2FShanghai"

# sanity check before writing: a broken DSN fails much later and much more confusingly
if (-not $dsn.Contains("/${dbName}?")) { throw "DSN malformed (db name lost): $dsn" }
if ($dbPass -match '[/?#]') {
    Write-Warning "database password contains URL-reserved characters; the DSN may need escaping"
}

$yaml = @"
# GENERATED by scripts/gen-config.ps1 from $XTravelRoot\.env
# Contains plaintext credentials. Gitignored. Do not commit.
server:
  http:
    network: tcp
    addr: 0.0.0.0:$Port
    timeout: 5s
  grpc:
    network: tcp
    addr: 0.0.0.0:19000
    timeout: 1s

data:
  database:
    driver: mysql
    source: "$dsn"
    prefix: "$dbPrefix"
    debug: false
    max_open_conns: 50
    max_idle_conns: 10
  redis:
    network: tcp
    addr: "${rHost}:${rPort}"
    password: "$rPass"
    db: $rSel
    read_timeout: 1s
    write_timeout: 1s

app:
  name: xtravel
  env: test
  timezone: "$tz"
  # mirrors .env APP_DEBUG. NOT only a debug flag -- see conf.proto App.debug
  debug: $appDebug

# mirrors config/project.php user_token + .env [PROJECT] UNIQUE_IDENTIFICATION
auth:
  public_operations: []
  expire_duration: 604800
  be_expire_duration: 3600
  unique_identification: "$uniq"
  token_cache_prefix: "xtravel:go:"

log:
  level: debug
  format: text
  path: ./logs
"@

# UTF8 without BOM -- a BOM breaks the YAML parser
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($OutFile, $yaml, $utf8NoBom)

# verify what we actually wrote
$head = [System.IO.File]::ReadAllBytes($OutFile)
if ($head[0] -eq 239 -and $head[1] -eq 187 -and $head[2] -eq 191) { throw "BOM was written" }

$written = [System.IO.File]::ReadAllText($OutFile)
$srcLine = ($written -split "`n" | Where-Object { $_ -match 'source:' })
if ($srcLine -notmatch [regex]::Escape("/${dbName}?charset=")) { throw "written DSN looks wrong" }

Write-Host "wrote $OutFile"
Write-Host ("  db      {0}@{1}:{2}/{3}  prefix={4}" -f $dbUser, $dbHost, $dbPort, $dbName, $dbPrefix)
Write-Host ("  redis   {0}:{1} db={2}  password={3}" -f $rHost, $rPort, $rSel, [bool]$rPass)
Write-Host ("  tz/salt {0} / len={1}" -f $tz, $uniq.Length)
Write-Host ""
Write-Host "git ignored:" -NoNewline
$ci = git check-ignore -v $OutFile 2>&1
if ($ci) { Write-Host " yes" } else { Write-Host " NO -- fix .gitignore before committing" }
